package tools_test

// Shared string constants for the tools package's external test files.
// Extracted to satisfy the goconst linter, which counts repeated literals
// across the package. Grouped by purpose: config keys, JSON request keys,
// response field names, fixture values, error strings, and validation case
// names.
const (
	// Environment config keys and labels.
	envKeyDefault   = "default"
	envLabelDefault = "Default"
	envProd         = "prod"
	apiURLLinodeV4  = "https://api.linode.com/v4"
	tokenTest       = "test-token"

	// Common JSON request/response keys.
	keyConfirm           = "confirm"
	keyDescription       = "description"
	keyCertificate       = "certificate"
	keyPrivateKey        = "private_key"
	keyEmail             = "email"
	keyUsername          = "username"
	keyLabel             = "label"
	keyRegion            = "region"
	keyType              = "type"
	keyDomain            = "domain"
	keyName              = "name"
	keySize              = "size"
	keyIPv4              = "ipv4"
	keyACL               = "acl"
	keyAddress           = "address"
	keyCount             = "count"
	keyImage             = "image"
	keyMethod            = "method"
	keyTarget            = "target"
	keyRootPass          = "root_pass"
	keyRecordID          = "record_id"
	keyK8sVersion        = "k8s_version"
	keyVPCID             = "vpc_id"
	keyNodeID            = "node_id"
	keyNodePools         = "node_pools"
	keyMaster            = "master"
	keySoaEmail          = "soa_email"
	keyBucketAccess      = "bucket_access"
	keyTargetLinodeID    = "target_linode_id"
	keyIsTruncated       = "is_truncated"
	keyNextMarker        = "next_marker"
	keyKeyID             = "key_id"
	keySSHKeyID          = "sshkey_id"
	keyRDNS              = "rdns"
	keySince             = "since"
	keyPrivacyPolicy     = "privacy_policy"
	keyRegionID          = "region_id"
	keyErrors            = "errors"
	keyReason            = "reason"
	keyBetaID            = "id"
	keyEUUID             = "euuid"
	keyInvoiceID         = "invoice_id"
	keyLinodeIDs         = "linode_ids"
	keyToken             = "token"
	keyIsDefault         = "is_default"
	keyLastFour          = "last_four"
	keyEventID           = "event_id"
	keyPaymentMethodID   = "payment_method_id"
	keyPaymentID         = "payment_id"
	keyMaintenancePolicy = "maintenance_policy"
	keyPermissions       = "permissions"
	keyGlobal            = "global"
	keyAccountAccess     = "account_access"
	keyGrantLinode       = "linode"
	keyGrantLKECluster   = "lkecluster"
	keyRemoteNameserver  = "remote_nameserver"

	// Tool-specific resource ID keys.
	keyLinodeID       = "linode_id"
	keyInstanceID     = "instance_id"
	keyVolumeID       = "volume_id"
	keyDomainID       = "domain_id"
	keyDiskID         = "disk_id"
	keyClusterID      = "cluster_id"
	keyPoolID         = "pool_id"
	keySubnetID       = "subnet_id"
	keyBackupID       = "backup_id"
	keyFirewallID     = "firewall_id"
	keyNodeBalancerID = "nodebalancer_id"

	// Pagination response keys.
	keyData            = "data"
	keyPage            = "page"
	keyPageSize        = "page_size"
	keyPages           = "pages"
	keyResults         = "results"
	errPageInteger     = "page must be an integer"
	errPageSizeRange   = "page_size must be"
	errPageSizeInteger = "page_size must be an integer"

	// Linode region IDs commonly used in fixtures.
	regionUSEast         = "us-east"
	regionUSEast1        = "us-east-1"
	serviceLinodes       = "Linodes"
	serviceNodeBalancers = "NodeBalancers"
	serviceBlockStorage  = "Block Storage"
	regionUSWest         = "us-west"
	regionEUWest         = "eu-west"
	countryUS            = "us"

	// Linode instance type IDs commonly used in fixtures.
	typeG6Nanode1   = "g6-nanode-1"
	typeG6Standard1 = "g6-standard-1"
	typeG6Standard2 = "g6-standard-2"

	// Common test fixture values.
	statusActive                    = "active"
	statusEnabled                   = "enabled"
	statusOK                        = "ok"
	statusReady                     = "ready"
	statusRunning                   = "running"
	statusSuccessful                = "successful"
	statusPending                   = "pending"
	classStandard                   = "standard"
	bucketTest                      = "my-bucket"
	testCertPEM                     = "-----BEGIN CERTIFICATE-----\ntest\n-----END CERTIFICATE-----"
	testKeyPEM                      = "-----BEGIN PRIVATE KEY-----\ntest\n-----END PRIVATE KEY-----"
	keyNameTest                     = "my-key"
	testKeyLabel                    = "test-key"
	labelDataVol                    = "data-vol"
	labelBackupVol                  = "backup-vol"
	labelNew                        = "new-label"
	labelUpdatedSubnet              = "updated-subnet"
	labelProdVPC                    = "prod-vpc"
	labelTestVPC                    = "test-vpc"
	labelWebSubnet                  = "web-subnet"
	labelMyDisk                     = "my-disk"
	labelProdCluster                = "prod-cluster"
	labelTestCluster                = "test-cluster"
	domainExample                   = "example.com"
	remoteNameserverExample         = "ns1.example.com"
	hostWWW                         = "www"
	imageUbuntu2204                 = "Ubuntu 22.04"
	imageUbuntu2404                 = "Ubuntu 24.04 Disk"
	imageIDUbuntu2204               = "linode/ubuntu22.04"
	imageIDUbuntu2404               = "linode/ubuntu24.04"
	typeLinode4GB                   = "Linode 4GB"
	rootPassStrong                  = "Str0ngP@ssw0rd!"
	objectStorageKey                = "TESTKEY00000000EXAMPLE"
	httpMethodGET                   = "GET"
	idAbc123                        = "abc-123"
	caseZero                        = "zero"
	stageAlpha                      = "alpha"
	stageBeta                       = "beta"
	stageGamma                      = "gamma"
	cidrV4                          = "10.0.0.0/24"
	cidrV6                          = "2001:db8::1/128"
	ip192168_1_1                    = "192.168.1.1"
	ip192168_1_2                    = "192.168.1.2"
	ip203_0_113_1                   = "203.0.113.1"
	rdnsTestExampleOrg              = "test.example.org"
	subnetMaskFixture               = "255.255.255.0"
	notANumber                      = "not-a-number"
	boolStringTrue                  = "true"
	grantPermissionReadOnly         = "read_only"
	grantPermissionReadWrite        = "read_write"
	betaExampleOpen                 = "example_open"
	labelExampleOpenBeta            = "Example Open Beta"
	childAccountEUUID               = "A1BC2DEF-34GH-567I-J890KLMN12O34P56"
	companyAcme                     = "Acme"
	accountInvoiceID                = 12345
	accountEntityTransferToken      = "transfer-token-example"
	accountEntityTransferTokenSlash = "transfer/token"
	accountEntityTransferTokenQuery = "transfer?token"
	accountEventID                  = 123
	accountEventAction              = "linode_create"
	emailUpdatedExample             = "updated@example.com"
	maintenancePolicyMigrate        = "linode/migrate"
	nameUpdatedTest                 = "Updated"
	aclPublicRead                   = "public-read"
	aclPrivate                      = "private"
	errRegionInvalid                = "region must contain only lowercase letters, numbers, and hyphens"
	pathTraversalValue              = ".."
	errEUUIDNonEmpty                = "euuid must be a non-empty string"
	errEUUIDNoSeparators            = "euuid must not contain path separators"
	objectPhotoJPG                  = "photo.jpg"
	filesystemExt4                  = "ext4"

	// Builder-tool test fixtures: tool names + arg keys reused across
	// linode_profile_builder_test.go, linode_profile_draft_test.go, and
	// linode_profile_draft_mutate_test.go.
	toolInstanceBoot   = "linode_instance_boot"
	toolInstanceReboot = "linode_instance_reboot"
	toolHello          = "hello"
	keyTools           = "tools"
	keyAllowYolo       = "allow_yolo"
	envNonexistent     = "nonexistent"
	draftNonexistent   = "nonexistent-draft"

	// LKE Kubernetes versions.
	lkeVersion128 = "1.28"
	lkeVersion129 = "1.29"

	// LKE pool snapshot fixture used in multiple tests.
	lkePoolSnapshot = `[{"type":"g6-standard-2","count":3}]`

	// Snapshot literal (separate from lkePoolSnapshot).
	wordSnapshot = "snapshot"

	// Validation error message values.
	errLabelRequired               = "label is required"
	errSSHKeyIDPositive            = "sshkey_id must be a positive integer"
	errRegionRequired              = "region is required"
	errTypeRequired                = "type is required"
	errFirewallIDRequired          = "firewall_id is required"
	errLinodeIDRequired            = "linode_id is required"
	errAddressRequired             = "address is required"
	errAddressValidIP              = "address must be a valid IP address"
	errDomainIDRequired            = "domain_id is required"
	errDomainIDPositive            = "domain_id must be a positive integer"
	errDomainRequired              = "domain is required"
	errClusterIDRequired           = "cluster_id is required"
	errVPCIDRequired               = "vpc_id is required"
	errSubnetIDRequired            = "subnet_id is required"
	errACLMustBeOneOf              = "acl must be one of"
	errInvalidACL                  = "invalid ACL"
	errConfirmEqualsTrue           = "confirm=true"
	errForbidden                   = "forbidden"
	errGrantSectionsArray          = "grant sections must be arrays"
	errGlobalObject                = "global must be an object"
	paymentMethodCreditCard        = "credit_card"
	paymentMethodToken             = "tok_123"
	paymentMethodLastFour          = "1111"
	paymentMethodCreatedMessage    = "Payment method created successfully"
	paymentMethodDeletedMessage    = "Payment method deleted successfully"
	paymentMethodID                = "123"
	paymentMethodIDSlash           = "123/456"
	paymentMethodIDQuery           = "123?456"
	errPaymentMethodIDRequired     = "payment_method_id is required"
	errPaymentMethodIDNonEmpty     = "payment_method_id must be a non-empty string"
	errPaymentMethodIDNoSeparators = "payment_method_id must not contain path separators"
	errPaymentMethodIDPositive     = "payment_method_id must be a positive integer"
	errPaymentIDPositive           = "payment_id must be a positive integer"
	errRegionIDSlug                = "lowercase region slug"
	errBetaIDRequired              = "id is required"
	errBetaIDNonEmpty              = "id must be a non-empty string"
	errBetaIDChars                 = "id must contain only letters"
	errLinodeIDsPositiveArray      = "linode_ids must be an array of positive integers"
	accountServiceTransferToken    = "service-token-example"
	errTokenRequired               = "token is required"
	errTokenNonEmpty               = "token must be a non-empty string"
	errTokenNoSeparators           = "token must not contain path separators"
	errEventIDRequired             = "event_id is required"
	errEventIDPositive             = "event_id must be a positive integer"
	keyComments                    = "comments"

	// Validation case names used in table-driven test rows.
	caseRequiresConfirm           = "requires confirm"
	caseMissingConfirm            = "missing confirm"
	caseSlashUsername             = "slash username"
	caseQueryUsername             = "query username"
	caseDotdotUsername            = "dotdot username"
	valueSlashUsername            = "user/name"
	valueQueryUsername            = "user?name"
	valueFragmentUsername         = "user#name"
	valueDotdotUsername           = "user..name"
	casePaymentMethodConfirmFalse = "payment method confirm false"
	caseConfirmFalse              = "confirm false"
	caseMissing                   = "missing"
	caseString                    = "string"
	caseEmpty                     = "empty"
	caseSlash                     = "slash"
	caseQuery                     = "query"
	caseDotTraversal              = "dot traversal"
	caseNumeric                   = "numeric"
	caseMissingLabel              = "missing label"
	caseMissingAddress            = "missing address"
	caseMissingRegion             = "missing region"
	caseMissingType               = "missing type"
	caseMissingFirewallID         = "missing firewall_id"
	caseMissingLinodeID           = "missing linode id"
	caseMissingInstanceID         = "missing instance id"
	caseMissingVPCID              = "missing vpc id"
	caseMissingSubnetID           = "missing subnet id"
	caseMissingDomain             = "missing domain"
	caseMissingDomainID           = "missing domain id"
	caseMissingClusterID          = "missing cluster id"
	testStackScript               = "#!/bin/bash"
	keyImages                     = "images"
	testDebian12Image             = "linode/debian12"
	keyScript                     = "script"
	testStackScriptLabel          = "test-script"
)
