package tools_test

// Shared string constants for the tools package's external test files.
// Extracted to satisfy the goconst linter, which counts repeated literals
// across the package. Grouped by purpose: config keys, JSON request keys,
// response field names, fixture values, error strings, and validation case
// names.
const (
	// Environment config keys and labels.
	envKeyDefault              = "default"
	envLabelDefault            = "Default"
	envProd                    = "prod"
	apiURLLinodeV4             = "https://api.linode.com/v4"
	apiURLRejectLocalhost      = "http://127.0.0.1:1"
	ipv6RangeBase              = "2001:0db8::"
	ipv6RangeCIDR              = "2001:0db8::/64"
	ipv6RangeEscaped           = "2001:0db8::%2F64"
	ipv6RangeRouteTarget       = "2001:0db8::1"
	reservedIPv4Fixture        = "192.0.2.141"
	reservedIPAddressFixture   = "192.0.2.10"
	nodeBalancerLabelFixture   = "web-lb"
	keyIPv6Range               = "range"
	tokenTest                  = "test-token"
	imageShareGroupLabel       = "DevOps Base Images"
	errTemporaryFailure        = "temporary failure"
	errPositiveInteger         = "positive integer"
	errNotFound                = "not found"
	errImageIDPositive         = "image_id must be a positive integer"
	errImageIDRequired         = "image_id is required"
	errImageIDNonEmpty         = "image_id must be a non-empty string"
	errImageIDPathFragment     = "image_id must be a private image identifier"
	errInvalidHelpersJSON      = "invalid helpers JSON"
	errInvalidInterfacesJSON   = "invalid interfaces JSON"
	errInvalidDevicesJSON      = "invalid devices JSON"
	errConfigIDPositive        = "config_id must be a positive integer"
	errInvalidInterfaceJSON    = "invalid interface JSON"
	errInterfaceRequired       = "interface is required"
	errInterfaceJSONObject     = "interface must be a JSON object"
	errInterfaceTypeExactlyOne = "interface must define exactly one of public, vpc, or vlan"
	caseInvalidInterface       = "invalid interface"
	caseInvalidType            = "invalid type"
	caseExtraSeparator         = "extra separator"
	caseMissingInterface       = "missing interface"
	caseMissingCredentialID    = "missing credential id"
	caseZeroCredentialID       = "zero credential id"
	caseTraversalCredentialID  = "traversal credential id"
	caseNullInterface          = "null interface"
	caseZeroContactID          = "zero contact id"
	memberLabelFixture         = "Engineering"
	memberTokenFixture         = "member-token"
	invalidServiceTypeSlash    = "dbaas/postgres"
	invalidServiceTypeQuery    = "dbaas?x=1"
	caseTraversalServiceType   = "traversal service type"
	caseSeparatorServiceType   = "separator service type"
	caseSeparatorConfigID      = "separator config id"
	caseQueryServiceType       = "query service type"
	caseMissingServiceType     = "missing service type"
	caseMissingAlertID         = "missing alert id"
	caseMissingEntityIDs       = "missing entity ids"
	caseStringEntityID         = "string entity id"
	caseZeroAlertID            = "zero alert id"
	caseStringAlertID          = "string alert id"
	caseNumericServiceType     = "numeric service type"

	// Common JSON request/response keys.
	keyConfirm             = "confirm"
	keyConfirmedDryRun     = "confirmed_dry_run"
	keyConfirmBypassDryRun = "confirm_bypass_dry_run"
	keyOTPCode             = "otp_code"
	keyPort                = "port"
	keyProtocol            = "protocol"
	keySSLCert             = "ssl_cert"
	keySSLKey              = "ssl_key"
	keyAlgorithm           = "algorithm"
	keyStickiness          = "stickiness"
	keyCheck               = "check"
	keyCipherSuite         = "cipher_suite"
	keyCheckInterval       = "check_interval"
	keyCheckTimeout        = "check_timeout"
	keyCheckAttempts       = "check_attempts"
	keyCheckPath           = "check_path"
	keyCheckBody           = "check_body"
	keyCheckPassive        = "check_passive"
	valueRoundRobin        = "roundrobin"
	valueNone              = "none"
	valueRecommended       = "recommended"
	protocolHTTP           = "http"
	protocolHTTPS          = "https"
	// protocolInvalid is a value no NodeBalancer protocol enum accepts; udp is
	// now valid (it was wrongly rejected before the proto-enum migration), so
	// the invalid-protocol cases use this instead.
	protocolInvalid              = "ftp"
	keyDefaultFirewallIDs        = "default_firewall_ids"
	keyDefaultFirewallLinode     = "linode"
	keyDescription               = "description"
	keyCertificate               = "certificate"
	keyPrivateKey                = "private_key"
	keyEmail                     = "email"
	keyUsername                  = "username"
	keyRestricted                = "restricted"
	keyLabel                     = "label"
	keyCreated                   = "created"
	keyUpdated                   = "updated"
	keyRegion                    = "region"
	keyAssignments               = "assignments"
	keyRegions                   = "regions"
	keyType                      = "type"
	schemaTypeInteger            = "integer"
	keyServiceType               = "service_type"
	keyEntityIDs                 = "entity_ids"
	keyWidgets                   = "widgets"
	keyMetric                    = "metric"
	keyMetricType                = "metric_type"
	keyDomain                    = "domain"
	keyName                      = "name"
	keySize                      = "size"
	keyIPv4                      = "ipv4"
	keyACL                       = "acl"
	keyAddress                   = "address"
	keyCount                     = "count"
	keyImage                     = "image"
	keyMethod                    = "method"
	keyTarget                    = "target"
	keyRootPass                  = "root_pass"
	keyRecordID                  = "record_id"
	keyK8sVersion                = "k8s_version"
	keyVersion                   = "version"
	keyVPCID                     = "vpc_id"
	keyNodeID                    = "node_id"
	keyNodePools                 = "node_pools"
	keyMaster                    = "master"
	keySoaEmail                  = "soa_email"
	keyBucketAccess              = "bucket_access"
	keyCORSEnabled               = "cors_enabled"
	keyExpiresIn                 = "expires_in"
	keyTargetLinodeID            = "target_linode_id"
	keyKeyID                     = "key_id"
	keySSHKeyID                  = "ssh_key_id"
	keySSHKey                    = "ssh_key"
	keyRDNS                      = "rdns"
	keySince                     = "since"
	keyPrivacyPolicy             = "privacy_policy"
	keyRegionID                  = "region_id"
	keyErrors                    = "errors"
	keyReason                    = "reason"
	keyBetaID                    = "id"
	keyBetaIDPath                = "beta_id"
	keyLongviewClientID          = "client_id"
	keyCredentialID              = "credential_id"
	keyLongviewAPIKey            = "api_key"
	keyLongviewInstallCode       = "install_code"
	keyLongviewApps              = "apps"
	keyClientsIncluded           = "clients_included"
	keyPrice                     = "price"
	keyHourly                    = "hourly"
	keyMonthly                   = "monthly"
	keyLongviewAppApache         = "apache"
	keyLongviewAppNginx          = "nginx"
	longviewClientLabelFixture   = "client789"
	longviewClientCreatedFixture = "2018-01-01T00:01:01"
	longviewClientUpdatedFixture = "2018-01-02T00:01:01"
	longviewPlan10               = "longview-10"
	keyEUUID                     = "euuid"
	keyInvoiceID                 = "invoice_id"
	keyLinodeIDs                 = "linode_ids"
	keyToken                     = "token"
	keyIsDefault                 = "is_default"
	keyLastFour                  = "last_four"
	keyEventID                   = "event_id"
	keyPaymentMethodID           = "payment_method_id"
	keyPaymentID                 = "payment_id"
	keyMaintenancePolicy         = "maintenance_policy"
	keyPermissions               = "permissions"
	keyGlobal                    = "global"
	keyAccountAccess             = "account_access"
	keyGrantLinode               = "linode"
	managedLinodeSettingsGroup   = "linodes"
	managedServiceTypeURL        = "url"
	errManagedServiceIDPositive  = "service_id must be a positive integer"
	errManagedServiceIDRequired  = "service_id is required"
	caseMissingServiceID         = "missing service id"
	caseZeroServiceID            = "zero service id"
	caseNegativeServiceID        = "negative service id"
	caseStringServiceID          = "string service id"
	caseFractionalServiceID      = "fractional service id"
	caseOversizedServiceID       = "oversized service id"
	caseTraversalServiceID       = "traversal service id"
	caseSlashServiceID           = "slash service id"
	caseQueryServiceID           = "query service id"
	invalidManagedServiceSlashID = "9944/9955"
	invalidManagedServiceQueryID = "9944?x=1"
	keyGrantLKECluster           = "lkecluster"
	keyRemoteNameserver          = "remote_nameserver"
	keyValidForShareGroupUUID    = "valid_for_sharegroup_uuid"
	keyShareGroupID              = "sharegroup_id"
	keyTokenUUID                 = "token_uuid"
	keyImageID                   = "image_id"
	keyKernelID                  = "kernel_id"
	keyStackScriptID             = "stackscript_id"
	shareGroupDescription        = "shared CI images"
	shareGroupUpdated            = "2025-04-15T22:44:02"
	shareGroupCreated            = "2025-04-14T22:44:02"
	shareGroupUUIDFixture        = "e1d0e58b-f89f-4237-84ab-b82077342359"
	shareGroupLabelFixture       = "DevOps Base Images"
	shareGroupTokenUUIDFixture   = "sharegroup-token-uuid-fixture"
	shareGroupTokenGetUUID       = "00000000-0000-4000-8000-000000000001"
	invalidTokenUUID             = "not-a-uuid"
	imageShareGroupTokenCreated  = "2025-08-04T10:09:09"
	shareGroupTokenValueFixture  = "eyJhbGciOiJIUzI1NiJ9.test.signature"
	privateImage123Fixture       = "private/123"
	kernelLatestFixture          = "linode/latest-64bit"
	kernelLabelFixture           = "Latest 64 bit"
	privateImageTraversalFixture = "private/.."
	privateImageZeroFixture      = "private/0"
	configIDQueryValue           = "789?query"
	longviewClientSlashID        = "789/1"
	interfaceIDQueryValue        = "456?query"
	singleInterfaceIDsJSON       = "[101]"
	errReorderIDsArray           = "ids must be an array of positive integers"

	// Tool-specific resource ID keys.
	keyLinodeID                   = "linode_id"
	keyPrefixLength               = "prefix_length"
	keyRouteTarget                = "route_target"
	keyDevices                    = "devices"
	keyInterfaces                 = "interfaces"
	keyInterface                  = "interface"
	keyIDs                        = "ids"
	keyHelpers                    = "helpers"
	keyMemoryLimit                = "memory_limit"
	keyKernel                     = "kernel"
	keyInstanceID                 = "instance_id"
	keyVolumeID                   = "volume_id"
	testVolumeLabel               = "vol"
	testPublicIPv4                = "8.8.8.8"
	keyDomainID                   = "domain_id"
	keyDiskID                     = "disk_id"
	keyConfigID                   = "config_id"
	keyInterfaceID                = "interface_id"
	toolLinodeInstanceConfigList  = "linode_instance_config_list"
	keyClusterID                  = "cluster_id"
	keyPoolID                     = "pool_id"
	keySubnetID                   = "subnet_id"
	keyProxyProtocol              = "proxy_protocol"
	keyUDPCheckPort               = "udp_check_port"
	valueProxyV2                  = "v2"
	keyBackupID                   = "backup_id"
	keyFirewallID                 = "firewall_id"
	keyInbound                    = "inbound"
	keyOutbound                   = "outbound"
	keyFirewallDeviceID           = "device_id"
	firewallDeviceLabelFixture    = "web-01"
	policyAccept                  = "ACCEPT"
	caseMissingNodeBalancerID     = "missing nodebalancer id"
	caseSeparatorNodeBalancerID   = "separator nodebalancer id"
	caseQueryNodeBalancerID       = "query nodebalancer id"
	caseTraversalNodeBalancerID   = "traversal nodebalancer id"
	caseZeroConfigID              = "zero config id"
	caseMissingNodeID             = "missing node id"
	caseNegativeNodeBalancerID    = "negative nodebalancer id"
	nodeBalancerNodeLabelWeb1     = "web-1"
	caseMissingFirewallPathID     = "missing firewall id"
	caseZeroFirewallPathID        = "zero firewall id"
	caseSlashFirewallPathID       = "slash firewall id"
	caseQueryFirewallPathID       = "query firewall id"
	caseTraversalFirewallPathID   = "traversal firewall id"
	caseMissingFirewallDeviceID   = "missing device id"
	caseZeroFirewallDeviceID      = "zero device id"
	caseSlashFirewallDeviceID     = "slash device id"
	caseQueryFirewallDeviceID     = "query device id"
	caseTraversalFirewallDeviceID = "traversal device id"
	errFirewallIDPositive         = "firewall_id must be a positive integer"
	errFirewallDeviceIDPositive   = "device id must be a positive integer"
	keyNodeBalancerID             = "nodebalancer_id"
	keyVPCConfigID                = "vpc_config_id"
	caseFractionalLinodeID        = "fractional linode id"
	caseNegativeInterfaceID       = "negative interface id"
	caseSeparatorLinodeID         = "separator linode id"
	pathSeparatorLinodeID         = "123/.."
	labelWebFirewall              = "web-firewall"

	// Pagination response keys.
	keyData                               = "data"
	keyPage                               = "page"
	keyPageSize                           = "page_size"
	keyPages                              = "pages"
	keyResults                            = "results"
	errPageInteger                        = "page must be an integer"
	errPageSizeRange                      = "page_size must be"
	errPageSizeInteger                    = "page_size must be an integer"
	errConfigIDRequired                   = "config_id is required"
	errConfigIDInteger                    = "config_id must be a positive integer"
	errConfigIDMin                        = "config_id must be a positive integer"
	errNodeIDRequired                     = "node_id is required"
	errNodeIDInteger                      = "node_id must be a positive integer"
	errInterfaceIDPositive                = "interface_id must be a positive integer"
	errInterfaceIDRequired                = "interface_id is required"
	errInterfaceIDInteger                 = "interface_id must be a positive integer"
	errInterfaceIDMinOne                  = "interface_id must be a positive integer"
	errStackScriptIDInteger               = "stackscript_id must be a positive integer"
	errLongviewClientIDPositive           = "client_id must be a positive integer"
	errLongviewSubscriptionIDNoSeparators = "subscription_id must not contain path separators"

	// Linode region IDs commonly used in fixtures.
	regionUSEast         = "us-east"
	regionLabelNewark    = "Newark, NJ"
	regionIDSlashValue   = "us/east"
	regionIDQueryValue   = "us-east?x=1"
	vlanLabelApp         = "app-vlan"
	ipv6RangeFixture     = "2001:0db8::"
	ipv6RouteTarget      = "2001:db8::1"
	apiURLLoopbackClosed = "http://127.0.0.1:1"
	singleRegionJSON     = `["us-east"]`
	regionUSEast1        = "us-east-1"
	serviceLinodes       = "Linodes"
	serviceNodeBalancers = "NodeBalancers"
	serviceBlockStorage  = "Block Storage"
	regionUSWest         = "us-west"
	regionEUWest         = "eu-west"
	countryUS            = "us"

	// Linode instance type IDs commonly used in fixtures.
	typeG6Nanode1   = "g6-nanode-1"
	typeG6Standard1 = "g6-standard-1"
	typeG6Standard2 = "g6-standard-2"

	// Unknown-field drop pin: proto read tools must drop any API field their
	// message does not model, so success tests inject a keyNotInProto field with
	// value valNotInProto and assert the key is absent from the proto-canonical
	// output. keyNotInProto is the map-literal key form; struct-bodied fixtures use
	// a json:"not_in_proto" tag instead.
	keyNotInProto = "not_in_proto"
	valNotInProto = "dropped"

	// Common test fixture values.
	statusActive                    = "active"
	statusAvailable                 = "available"
	statusEnabled                   = "enabled"
	statusOK                        = "ok"
	statusReady                     = "ready"
	statusRunning                   = "running"
	statusSuccessful                = "successful"
	statusPending                   = "pending"
	classStandard                   = "standard"
	bucketTest                      = "my-bucket"
	testCertPEM                     = "-----BEGIN CERTIFICATE-----\ntest\n-----END CERTIFICATE-----"
	testKeyPEM                      = "-----BEGIN PRIVATE KEY-----\ntest\n-----END PRIVATE KEY-----"
	keyNameTest                     = "my-key"
	testKeyLabel                    = "test-key"
	labelDataVol                    = "data-vol"
	labelBackupVol                  = "backup-vol"
	labelNew                        = "new-label"
	labelUpdatedSubnet              = "updated-subnet"
	labelProdVPC                    = "prod-vpc"
	labelTestVPC                    = "test-vpc"
	labelWebSubnet                  = "web-subnet"
	labelMyDisk                     = "my-disk"
	labelBootConfig                 = "boot-config"
	configKernelLatest              = "linode/latest-64bit"
	configDeviceSlotSDA             = "sda"
	configDevicesSDAJSON            = `{"sda":{"disk_id":456}}`
	jsonObjectEmpty                 = `{}`
	labelProdCluster                = "prod-cluster"
	labelTestCluster                = "test-cluster"
	domainExample                   = "example.com"
	remoteNameserverExample         = "ns1.example.com"
	domainZoneTTL                   = "$TTL 864000"
	hostWWW                         = "www"
	imageUbuntu2204                 = "Ubuntu 22.04"
	imageUbuntu2404                 = "Ubuntu 24.04 Disk"
	imageIDUbuntu2204               = "linode/ubuntu22.04"
	imageIDUbuntu2404               = "linode/ubuntu24.04"
	privateImage12345Fixture        = "private/12345"
	shareGroupUUIDExample           = "1533863e-16a4-47b5-b829-ac0f35c13278"
	typeManualImage                 = "manual"
	typeLinode4GB                   = "Linode 4GB"
	rootPassStrong                  = "Str0ngP@ssw0rd!"
	objectStorageKey                = "TESTKEY00000000EXAMPLE"
	httpMethodGET                   = "GET"
	idAbc123                        = "abc-123"
	caseZero                        = "zero"
	caseNegative                    = "negative"
	caseNoUpdateFields              = "no update fields"
	caseEmptyLabel                  = "empty label"
	caseQueryLinodeID               = "query linode id"
	caseMissingShareGroupID         = "missing sharegroup id"
	caseZeroShareGroupID            = "zero sharegroup id"
	caseTraversalShareGroupID       = "traversal sharegroup id"
	caseMissingImageID              = "missing image id"
	caseTraversalImageID            = "traversal image id"
	caseQueryImageID                = "query image id"
	shareGroupIDQueryValue          = "123?query"
	stageAlpha                      = "alpha"
	stageBeta                       = "beta"
	stageGamma                      = "gamma"
	cidrV4                          = "10.0.0.0/24"
	cidrV4Secondary                 = "192.168.1.0/24"
	cidrV6                          = "2001:db8::1/128"
	privateIPv4AddressOne           = "192.168.1.1"
	privateIPv4AddressTwo           = "192.168.1.2"
	testNetIPv4AddressOne           = "203.0.113.1"
	testNetIPv4AddressTen           = "203.0.113.10"
	rdnsTestExampleOrg              = "test.example.org"
	subnetMaskFixture               = "255.255.255.0"
	notANumber                      = "not-a-number"
	boolStringTrue                  = "true"
	grantPermissionReadOnly         = "read_only"
	grantPermissionReadWrite        = "read_write"
	betaExampleOpen                 = "example_open"
	labelExampleOpenBeta            = "Example Open Beta"
	childAccountEUUID               = "A1BC2DEF-34GH-567I-J890KLMN12O34P56"
	companyAcme                     = "Acme"
	accountInvoiceID                = 12345
	accountEntityTransferToken      = "transfer-token-example"
	accountEntityTransferTokenSlash = "transfer/token"
	accountEntityTransferTokenQuery = "transfer?token"
	accountEventID                  = 123
	accountEventAction              = "linode_create"
	emailUpdatedExample             = "updated@example.com"
	maintenancePolicyMigrate        = "linode/migrate"
	nameUpdatedTest                 = "Updated"
	aclPublicRead                   = "public-read"
	aclPrivate                      = "private"
	errRegionInvalid                = "region must contain only lowercase letters, numbers, and hyphens"
	pathTraversalValue              = ".."
	macAddressFixture               = "22:00:AB:CD:EF:01"
	pathSeparatorValue              = "1/2"
	querySeparatorValue             = "1?x=2"
	errShareGroupIDPositive         = "sharegroup_id must be a positive integer"
	errShareGroupIDRequired         = "sharegroup_id is required"
	errEUUIDNonEmpty                = "euuid must be a non-empty string"
	errEUUIDNoSeparators            = "euuid must not contain path separators"
	objectPhotoJPG                  = "photo.jpg"
	filesystemExt4                  = "ext4"

	tokenUUIDWithSlash    = "token/uuid"
	tokenUUIDWithQuery    = "token?uuid"
	tokenUUIDWithFragment = "token#uuid"
	tokenUUIDWithDotdot   = "token..uuid"

	// Builder-tool test fixtures: tool names + arg keys reused across
	// linode_profile_builder_test.go, linode_profile_draft_test.go, and
	// linode_profile_draft_mutate_test.go.
	toolInstanceBoot   = "linode_instance_boot"
	toolInstanceReboot = "linode_instance_reboot"
	toolHello          = "hello"
	keyTools           = "tools"
	keyAllowYolo       = "allow_yolo"
	envNonexistent     = "nonexistent"
	draftNonexistent   = "nonexistent-draft"

	// LKE Kubernetes versions.
	lkeVersion128       = "1.28"
	lkeVersion129       = "1.29"
	lkeVersionWithSlash = "1.29/edge"
	lkeVersionWithQuery = "1.29?edge"
	lkeVersionTraversal = "1.29..edge"

	// LKE pool snapshot fixture used in multiple tests.
	lkePoolSnapshot = `[{"type":"g6-standard-2","count":3}]`

	// Snapshot literal (separate from lkePoolSnapshot).
	wordSnapshot = "snapshot"

	// Validation error message values.
	errLabelRequired               = "label is required"
	errVolumeIDRequired            = "volume_id is required"
	errVolumeIDPositive            = "volume_id must be a positive integer"
	errLabelNoSeparators           = "label must not contain"
	errLabelString                 = "label must be a string"
	errCredentialIDPositive        = "credential_id must be a positive integer"
	errCredentialIDRequired        = "credential_id is required"
	errTokenIDRequired             = "token_id is required"
	errContactIDRequired           = "contact_id is required"
	caseNonStringLabel             = "non-string label"
	errSSHKeyIDPositive            = "ssh_key_id must be a positive integer"
	errRegionRequired              = "region is required"
	errRegionIDRequired            = "region_id is required"
	errRegionIDNonEmpty            = "region_id must be a non-empty string"
	errTypeRequired                = "type is required"
	errFirewallIDRequired          = "firewall_id is required"
	errLinodeIDRequired            = "linode_id is required"
	errLinodeIDInteger             = "linode_id must be a positive integer"
	errLinodeIDPositive            = "linode_id must be a positive integer"
	errIPv6RangePrefixRange        = "prefix_length must be an integer between 1 and 128"
	errLinodeIDMin                 = "linode_id must be a positive integer"
	errAddressRequired             = "address is required"
	errAddressValidIP              = "address must be a valid IP address"
	caseMalformedAddress           = "malformed address"
	testInvalidIPValue             = "not-an-ip"
	errDomainIDRequired            = "domain_id is required"
	errDomainIDPositive            = "domain_id must be a positive integer"
	errDomainRequired              = "domain is required"
	errClusterIDRequired           = "cluster_id is required"
	errVPCIDRequired               = "vpc_id is required"
	errSubnetIDRequired            = "subnet_id is required"
	errACLMustBeOneOf              = "acl must be one of"
	errInvalidACL                  = "invalid ACL"
	errConfirmEqualsTrue           = "confirm=true"
	errLabelNonEmpty               = "label must be a non-empty string"
	errAlertDefinitionSeverity     = "severity must be an integer from 0 through 3"
	errAlertDefinitionChannels     = "channel_ids must be a non-empty array of positive integers"
	errAlertDefinitionEntityIDs    = "entity_ids must be an array of non-empty strings"
	monitorCriteriaAll             = "ALL"
	caseFalseConfirmRejected       = "false confirm rejected"
	caseStringConfirmRejected      = "string confirm rejected"
	caseNumericConfirmRejected     = "numeric confirm rejected"
	errImageShareTokenNoSeparators = "token_uuid must not contain"
	errTokenUUIDNonEmpty           = "token_uuid must be a non-empty string"
	errForbidden                   = "forbidden"
	errGrantSectionsArray          = "grant sections must be arrays"
	errGlobalObject                = "global must be an object"
	paymentMethodCreditCard        = "credit_card"
	paymentMethodToken             = "tok_123"
	paymentMethodLastFour          = "1111"
	paymentMethodCreatedMessage    = "Payment method created successfully"
	paymentMethodDeletedMessage    = "Payment method deleted successfully"
	paymentMethodID                = float64(123)
	paymentMethodIDSlash           = "123/456"
	paymentMethodIDQuery           = "123?456"
	errPaymentMethodIDRequired     = "payment_method_id is required"
	errPaymentMethodIDInteger      = "payment_method_id must be a positive integer"
	errPaymentMethodIDPositive     = "payment_method_id must be a positive integer"
	errPaymentIDPositive           = "payment_id must be a positive integer"
	errRegionIDSlug                = "lowercase region slug"
	errRegionsLowercaseSlug        = "regions entries must be lowercase region slugs"
	errBetaIDRequired              = "id is required"
	errBetaIDNonEmpty              = "id must be a non-empty string"
	errBetaIDChars                 = "id must contain only letters"
	errLinodeIDsPositiveArray      = "linode_ids must be an array of positive integers"
	accountServiceTransferToken    = "service-token-example"
	errTokenRequired               = "token is required"
	errTokenNonEmpty               = "token must be a non-empty string"
	errTokenNoSeparators           = "token must not contain path separators"
	errValidForShareGroupUUID      = "valid_for_sharegroup_uuid is required"
	imageShareGroupCreated         = "2025-04-14T22:44:02"
	purposePublic                  = "public"
	purposeVPC                     = "vpc"
	policyDrop                     = "DROP"
	firewallRuleLabelAllowHTTPS    = "allow-https"
	keySlug                        = "slug"
	errEventIDRequired             = "event_id is required"
	errEventIDPositive             = "event_id must be a positive integer"
	keyComments                    = "comments"

	// Validation case names used in table-driven test rows.
	caseRequiresConfirm           = "requires confirm"
	caseMissingConfirm            = "missing confirm"
	caseMissingConfigID           = "missing config id"
	caseNegativeConfigID          = "negative config id"
	caseSlashLinodeID             = "slash linode id"
	caseTraversalLinodeID         = "traversal linode id"
	caseSlashConfigID             = "slash config id"
	caseQueryConfigID             = "query config id"
	caseTraversalConfigID         = "traversal config id"
	caseMissingInterfaceID        = "missing interface id"
	caseSlashInterfaceID          = "slash interface id"
	caseZeroInterfaceID           = "zero interface id"
	caseQueryInterfaceID          = "query interface id"
	caseTraversalInterfaceID      = "traversal interface id"
	caseUnknownInterfaceField     = "unknown interface field"
	caseInvalidInterfacePurpose   = "invalid interface purpose"
	caseSlashShareGroupID         = "slash sharegroup id"
	caseQueryShareGroupID         = "query sharegroup id"
	caseSlashUsername             = "slash username"
	caseQueryUsername             = "query username"
	caseDotdotUsername            = "dotdot username"
	valueSlashUsername            = "user/name"
	valueQueryUsername            = "user?name"
	valueFragmentUsername         = "user#name"
	valueDotdotUsername           = "user..name"
	casePaymentMethodConfirmFalse = "payment method confirm false"
	caseConfirmFalse              = "confirm false"
	caseMissing                   = "missing"
	caseString                    = "string"
	caseEmpty                     = "empty"
	caseSlash                     = "slash"
	caseQuery                     = "query"
	pathQueryValue                = "123?query"
	caseDotTraversal              = "dot traversal"
	caseFragment                  = "fragment"
	caseDotdot                    = "dotdot"
	caseNotUUID                   = "not_uuid"
	caseNumeric                   = "numeric"
	caseMissingLabel              = "missing label"
	caseMissingVolumeID           = "missing volume id"
	caseMissingAddress            = "missing address"
	caseMissingRegion             = "missing region"
	caseBlankRegion               = "blank region"
	caseMissingType               = "missing type"
	caseMissingFirewallID         = "missing firewall_id"
	caseMissingLinodeID           = "missing linode id"
	caseZeroLinodeID              = "zero linode id"
	caseNegativeLinodeID          = "negative linode id"
	caseMissingInstanceID         = "missing instance id"
	caseMissingVPCID              = "missing vpc id"
	caseMissingSubnetID           = "missing subnet id"
	caseMissingDomain             = "missing domain"
	caseMissingDomainID           = "missing domain id"
	caseMissingClusterID          = "missing cluster id"
	caseInvalidPageSizeLow        = "invalid page size low"
	caseInvalidPageSizeHigh       = "invalid page size high"
	testStackScript               = "#!/bin/bash"
	testStackScriptWithWhitespace = " #!/bin/bash\necho hello\n "
	testStackScriptID             = float64(456)
	keyImages                     = "images"
	imagePrivate15Fixture         = "private/15"
	imagePrivate15JSON            = `[{"id":"private/15"}]`
	testDebian12Image             = "linode/debian12"
	keyScript                     = "script"
	testStackScriptLabel          = "test-script"
	testRenamedLabel              = "renamed"
	errStackScriptImagesValid     = "images entries must be valid image IDs"
)

const (
	errTagsMust = "tags must"
)

const (
	keyEnvironment = "environment"
)

// Repeated literals extracted to satisfy goconst.
const (
	tcAccount                                    = "/account"
	tcAccountOauthClientsClient123               = "/account/oauth-clients/client-123"
	tcAccountOauthClientsClient123Thumbnail      = "/account/oauth-clients/client-123/thumbnail"
	tcAccountPaymentMethods123                   = "/account/payment-methods/123"
	tcAccountServiceTransfersServiceTokenExample = "/account/service-transfers/service-token-example"
	tcDestroys                                   = "destroys"
	tcDevSda                                     = "/dev/sda"
	tcFrequency                                  = "frequency"
	tcGETLkeClusters123                          = "GET /lke/clusters/123"
	tcImagesSharegroups1234                      = "/images/sharegroups/1234"
	tcLinodeInstanceShutdown                     = "linode_instance_shutdown"
	tcLinodeInstances123Configs                  = "/linode/instances/123/configs"
	tcLinodeInstances123Configs789               = "/linode/instances/123/configs/789"
	tcLinodeInstances123Configs789Interfaces456  = "/linode/instances/123/configs/789/interfaces/456"
	tcLinodeInstances123Disks                    = "/linode/instances/123/disks"
	tcLinodeInstances123Disks10                  = "/linode/instances/123/disks/10"
	tcLinodeInstances123Firewalls                = "/linode/instances/123/firewalls"
	tcLinodeInstances123Interfaces               = "/linode/instances/123/interfaces"
	tcLinodeInstances123Interfaces456            = "/linode/instances/123/interfaces/456"
	tcLinodeInstances123Ips                      = "/linode/instances/123/ips"
	tcLinodeInstances123Ips20301131              = "/linode/instances/123/ips/203.0.113.1"
	tcLit                                        = "203.0.113.0/24"
	tcLongviewClients789                         = "/longview/clients/789"
	tcNetworkingFirewalls123Devices              = "/networking/firewalls/123/devices"
	tcNetworkingFirewalls123Devices456           = "/networking/firewalls/123/devices/456"
	tcNetworkingFirewalls123Rules                = "/networking/firewalls/123/rules"
	tcNetworkingFirewalls789                     = "/networking/firewalls/789"
	tcNetworkingFirewallsSettings                = "/networking/firewalls/settings"
	tcNetworkingIpv6Ranges                       = "/networking/ipv6/ranges"
	tcNetworkingIpv6Ranges20010db82F64           = "/networking/ipv6/ranges/2001:0db8::%2F64"
	tcNetworkingVlans                            = "/networking/vlans"
	tcNodebalancers123Configs                    = "/nodebalancers/123/configs"
	tcNodebalancers123Configs456                 = "/nodebalancers/123/configs/456"
	tcNodebalancers123Configs456Nodes            = "/nodebalancers/123/configs/456/nodes"
	tcNodebalancers123Configs456Nodes789         = "/nodebalancers/123/configs/456/nodes/789"
	tcNodebalancers123Firewalls                  = "/nodebalancers/123/firewalls"
	tcNodebalancers444                           = "/nodebalancers/444"
	tcObjectStorageBucketsUsEast1MyBucket        = "/object-storage/buckets/us-east-1/my-bucket"
	tcObjectStorageBucketsUsEast1MyBucketSsl     = "/object-storage/buckets/us-east-1/my-bucket/ssl"
	tcObjectStorageKeys42                        = "/object-storage/keys/42"
	tcPlacementGroups                            = "/placement/groups"
	tcPlacementGroups528                         = "/placement/groups/528"
	tcProd                                       = " prod "
	tcProfileApps12345                           = "/profile/apps/12345"
	tcProfileDevices12345                        = "/profile/devices/12345"
	tcProfilePhoneNumber                         = "/profile/phone-number"
	tcProfilePreferences                         = "/profile/preferences"
	tcProfileSecurityQuestions                   = "/profile/security-questions"
	tcProfileSshkeys123                          = "/profile/sshkeys/123"
	tcProfileTokens                              = "/profile/tokens"
	tcProfileTokens12345                         = "/profile/tokens/12345"
	tcPublicAccess                               = "public_access"
	tcScopeRead                                  = "scope:read"
	tcSupportTickets                             = "/support/tickets"
	tcTags                                       = "/tags"
	tcVolumes333                                 = "/volumes/333"
	tcVpcs123                                    = "/vpcs/123"
	tcVpcs123Subnets10                           = "/vpcs/123/subnets/10"
)

// Additional repeated map-key literals extracted to satisfy goconst.
const (
	tcHourOfDay       = "hour_of_day"
	tcPublicInterface = "public_interface"
	tcVPCInterface    = "vpc_interface"
)

const tcWeekly = "weekly"

// Repeated literals extracted to satisfy goconst.
const (
	tcForbidden    = "403_forbidden"
	tcRateLimit    = "429_rate_limit"
	tcServerError  = "500_server_error"
	tcUnauthorized = "401_unauthorized"
)

// Repeated error-message literals extracted to satisfy goconst.
const (
	tcServerErrorMsg  = "server error"
	tcInvalidTokenMsg = "invalid token"
	tcRateLimitMsg    = "rate limit"
)

// Repeated literals extracted to satisfy goconst.
const (
	tcAllowedEnvironments = "allowed_environments"
	tcAllowedTools        = "allowed_tools"
	tcBackups             = "backups"
	tcBackupsEnabled      = "backups_enabled"
	tcCloudInit           = "cloud_init"
	tcCustomUpload        = "custom upload"
	tcNetworkHelper       = "network_helper"
	tcRequiredTokenScopes = "required_token_scopes"
)

// Repeated literals extracted to satisfy goconst.
const (
	tcAction          = "action"
	tcInstance        = "instance"
	tcLinodeDomainGet = "linode_domain_get"
	tcManaged         = "managed"
)

// goconst composite-context literals.
const (
	tcKind = "kind"
)

// Repeated literals extracted to satisfy goconst.
const (
	tcHealth = "/health"
	tcIpv6   = "ipv6"
)
