package linode_test

// Shared string constants for the linode package's external test files.
// Extracted to satisfy goconst across client_test.go, errors_test.go,
// retry_test.go, and retry_wrappers_test.go.
const (
	// JSON pagination keys returned by the Linode API.
	keyData            = "data"
	keyDescription     = "description"
	keyExample         = "example"
	keyPage            = "page"
	keyPages           = "pages"
	keyResults         = "results"
	keyPageSize        = "page_size"
	keyVPCID           = "vpc_id"
	keySubnetID        = "subnet_id"
	keyIPv4Range       = "ipv4_range"
	cidrV4             = "10.0.0.0/24"
	keyNodeBalancerID  = "nodebalancer_id"
	keyConfigID        = "config_id"
	keyNodeID          = "node_id"
	keyPort            = "port"
	keyProtocol        = "protocol"
	keyAlgorithm       = "algorithm"
	protocolHTTPS      = "https"
	valueRoundRobin    = "roundrobin"
	keyAddress         = "address"
	nodeLabelWeb1      = "web-1"
	keyErrors          = "errors"
	linode123Label     = "linode123"
	keyReason          = "reason"
	keyClientsIncluded = "clients_included"
	keyPrice           = "price"
	keyHourly          = "hourly"
	keyMonthly         = "monthly"

	errTemporaryFailure         = "temporary failure"
	longviewClientCreated       = "2018-01-01T00:01:01"
	longviewClientUpdated       = "2018-01-02T00:01:01"
	longviewPlan10              = "longview-10"
	errNotFound                 = "not found"
	imageShareGroupTokenCreated = "2025-08-04T10:09:09"

	// Common JSON field names used in test fixtures.
	keyID          = "id"
	keyLabel       = "label"
	keyStatus      = "status"
	keyMode        = "mode"
	keySeverity    = "severity"
	keyThreshold   = "threshold"
	keySSHKey      = "ssh_key"
	keyType        = "type"
	keyServiceType = "service_type"
	keyWidgets     = "widgets"
	keyMetric      = "metric"
	keyMetricType  = "metric_type"
	keyToken       = "token"
	keyDomain      = "domain"
	keyIsDefault   = "is_default"
	keyLastFour    = "last_four"
	// Account settings fixture values.
	maintenancePolicyMigrate = "linode/migrate"

	// Account beta fixture values.
	betaExampleOpen      = "example_open"
	labelExampleOpenBeta = "Example Open Beta"

	// Child account fixture values.
	childAccountEUUID = "A1BC2DEF-34GH-567I-J890KLMN12O34P56"
	companyAcme       = "Acme"
	accountInvoiceID  = 12345

	// Common region IDs used in API response fixtures.
	regionUSEast               = "us-east"
	vlanLabelApp               = "app-vlan"
	ipv6RangeFixture           = "2001:0db8::"
	ipv6RangeCIDR              = "2001:0db8::/64"
	ipv6RangeEscaped           = "2001:0db8::%2F64"
	ipv6RouteTarget            = "2001:db8::1"
	serviceLinodes             = "Linodes"
	serviceNodeBalancers       = "NodeBalancers"
	nodeBalancerNodeAddress    = "192.0.2.10:80"
	nodeBalancerNodeModeAccept = "accept"
	nodeBalancerNodeStatusUP   = "UP"
	keyWeight                  = "weight"

	// fwLabelNew is the firewall label reused across the retry-wrapper tests.
	fwLabelNew                   = "new-fw"
	paymentMethodCreditCard      = "credit_card"
	paymentMethodToken           = "tok_123"
	domainExample                = "example.com"
	remoteNameserverExample      = "ns1.example.com"
	shareGroupUUIDFixture        = "e1d0e58b-f89f-4237-84ab-b82077342359"
	shareGroupLabelFixture       = "DevOps Base Images"
	shareGroupDescriptionFixture = "shared CI images"
	shareGroupUUIDExample        = "1533863e-16a4-47b5-b829-ac0f35c13278"
	shareGroupCreatedFixture     = "2025-04-14T22:44:02"
	shareGroupUpdatedFixture     = "2025-04-15T22:44:02"
	shareGroupTokenUUIDFixture   = "sharegroup-token-uuid-fixture"
	shareGroupTokenValueFixture  = "sample-sharegroup-membership-token"
	memberLabelFixture           = "Engineering"
	memberTokenFixture           = "member-token"
	imageLinuxDebianFixture      = "Linux Debian"
	privateImage15Fixture        = "private/15"
	privateImage123Fixture       = "private/123"
	privateImage12345Fixture     = "private/12345"
	sharedImage1Fixture          = "shared/1"
	imageStatusAvailableFixture  = "available"
	statusEnabledFixture         = "enabled"
	typeManualImage              = "manual"
	keyCreated                   = "created"
	keyUpdated                   = "updated"
	labelBootConfig              = "boot-config"
	configDeviceSlotSDA          = "sda"
	configKernelLatest           = "linode/latest-64bit"
	purposePublic                = "public"
	purposeVPC                   = "vpc"
	policyDrop                   = "DROP"
	policyAccept                 = "ACCEPT"
	protocolTCP                  = "TCP"
	firewallRuleLabelAllowHTTPS  = "allow-https"
	macAddressFixture            = "22:00:AB:CD:EF:01"
	pathTraversalDotDot          = ".."
	lkeTierStandard              = "standard"
	lkeVersion129                = "1.29"
	lkeVersionWithSlash          = "1.29/edge"
)

// Fixture labels and endpoint paths extracted so inline comparisons across the
// external test files don't trip goconst.
const (
	dataVolumeLabel          = "data-volume"
	placementGroupLabel      = "pg-east"
	networkTransferPriceID   = "network_transfer"
	firewallRulesFingerprint = "997dd135"

	endpointRegionUSEast              = "/regions/us-east"
	endpointRegionUSEastAvailability  = "/regions/us-east/availability"
	endpointRegionsAvailability       = "/regions/availability"
	endpointPlacementGroup123         = "/placement/groups/123"
	endpointFirewallHistoryRule2      = "/networking/firewalls/123/history/rules/2"
	endpointInstanceTransferPath      = "/linode/instances/123/transfer"
	endpointInstanceTransferYearMonth = "/linode/instances/123/transfer/2024/1"
	endpointInstanceStatsPath         = "/linode/instances/123/stats"
	endpointInstanceStatsYearMonth    = "/linode/instances/123/stats/2024/8"
	endpointInstanceFirewallsPath     = "/linode/instances/123/firewalls"

	authHeaderTestToken = "Bearer test-token"
	instanceStatsTitle  = "linode.com - my-linode (linode123456) - day (5 min avg)"
)

// Repeated literals extracted to satisfy goconst.
const (
	tcABCDEF02                                       = "22:00:AB:CD:EF:02"
	tcAccountAgreements                              = "/account/agreements"
	tcAccountBetas                                   = "/account/betas"
	tcAccountCancel                                  = "/account/cancel"
	tcAccountChildAccounts                           = "/account/child-accounts"
	tcAccountChildAccountsA1BC2DEF34GH567IJ890KLMN12 = "/account/child-accounts/A1BC2DEF-34GH-567I-J890KLMN12O34P56"
	tcAccountEvents                                  = "/account/events"
	tcAccountEvents123                               = "/account/events/123"
	tcAccountInvoices                                = "/account/invoices"
	tcAccountInvoices12345                           = "/account/invoices/12345"
	tcAccountInvoices12345Items                      = "/account/invoices/12345/items"
	tcAccountLogins                                  = "/account/logins"
	tcAccountLogins123                               = "/account/logins/123"
	tcAccountNotifications                           = "/account/notifications"
	tcAccountOauthClients                            = "/account/oauth-clients"
	tcAccountOauthClientsClient2F1233Fquery          = "/account/oauth-clients/client%2F123%3Fquery"
	tcAccountPaymentMethods                          = "/account/payment-methods"
	tcAccountPaymentMethods123                       = "/account/payment-methods/123"
	tcAccountPayments                                = "/account/payments"
	tcAccountPayments654                             = "/account/payments/654"
	tcAccountPromoCodes                              = "/account/promo-codes"
	tcAccountServiceTransfers                        = "/account/service-transfers"
	tcAccountServiceTransfersServiceTokenExample     = "/account/service-transfers/service-token-example"
	tcAccountSettings                                = "/account/settings"
	tcAccountSettingsManagedEnable                   = "/account/settings/managed-enable"
	tcAccountTransfer                                = "/account/transfer"
	tcAccountUsers                                   = "/account/users"
	tcAccountUsersUser2Fname3Fquery                  = "/account/users/user%2Fname%3Fquery"
	tcApplicationJSON                                = "application/json"
	tcAuto                                           = "auto"
	tcBetas                                          = "/betas"
	tcCommon                                         = "common"
	tcDeployBase                                     = "deploy-base"
	tcExampleApp                                     = "example-app"
	tcExampleClient                                  = "example-client"
	tcExampleCom123                                  = "; example.com [123]"
	tcHTTPSExampleComBeta                            = "https://example.com/beta"
	tcImagesSharegroups123                           = "/images/sharegroups/123"
	tcImagesSharegroups123Members                    = "/images/sharegroups/123/members"
	tcImagesSharegroupsTokens2E2E                    = "/images/sharegroups/tokens/%2E%2E"
	tcInvoice12345                                   = "Invoice #12345"
	tcInvoice987                                     = "Invoice 987"
	tcLinodeCreate                                   = "linode_create"
	tcLinodeInstances123Configs                      = "/linode/instances/123/configs"
	tcLinodeInstances123Configs456                   = "/linode/instances/123/configs/456"
	tcLinodeInstances123Configs456Interfaces         = "/linode/instances/123/configs/456/interfaces"
	tcLinodeInstances123Configs789                   = "/linode/instances/123/configs/789"
	tcLinodeInstances123Configs789Interfaces456      = "/linode/instances/123/configs/789/interfaces/456"
	tcLinodeInstances123Interfaces                   = "/linode/instances/123/interfaces"
	tcLinodeInstances123Interfaces456                = "/linode/instances/123/interfaces/456"
	tcLinodeInstances123Volumes                      = "/linode/instances/123/volumes"
	tcLinodeStackscripts123                          = "/linode/stackscripts/123"
	tcLit                                            = "11/2024"
	tcLongviewClients789                             = "/longview/clients/789"
	tcMainSt                                         = "123 Main St"
	tcMonitorToken                                   = "monitor-token"
	tcNanode1GB                                      = "Nanode 1GB"
	tcNodebalancers123Configs456                     = "/nodebalancers/123/configs/456"
	tcNodebalancers123Configs456Nodes                = "/nodebalancers/123/configs/456/nodes"
	tcNodebalancers123Configs456Nodes789             = "/nodebalancers/123/configs/456/nodes/789"
	tcNodebalancers444Stats                          = "/nodebalancers/444/stats"
	tcObjectStorageCancel                            = "/object-storage/cancel"
	tcPGMiamiFailover                                = "PG_Miami_failover"
	tcPage2PageSize50                                = "page=2&page_size=50"
	tcPlacementGroups                                = "/placement/groups"
	tcPlacementGroups528Assign                       = "/placement/groups/528/assign"
	tcPlacementGroups789Unassign                     = "/placement/groups/789/unassign"
	tcProfileApps                                    = "/profile/apps"
	tcProfileApps12345                               = "/profile/apps/12345"
	tcProfileDevices                                 = "/profile/devices"
	tcProfileDevices12345                            = "/profile/devices/12345"
	tcProfileLogins                                  = "/profile/logins"
	tcProfileLogins123                               = "/profile/logins/123"
	tcProfilePhoneNumber                             = "/profile/phone-number"
	tcProfilePreferences                             = "/profile/preferences"
	tcProfileSecurityQuestions                       = "/profile/security-questions"
	tcProfileTfaDisable                              = "/profile/tfa-disable"
	tcProfileTfaEnableConfirm                        = "/profile/tfa-enable-confirm"
	tcProfileTokens                                  = "/profile/tokens"
	tcProfileTokens12345                             = "/profile/tokens/12345"
	tcRecovered                                      = "recovered"
	tcScheduledMaintenance                           = "Scheduled maintenance"
	tcSharedUbuntu                                   = "shared-ubuntu"
	tcSupportTickets                                 = "/support/tickets"
	tcSupportTickets11111                            = "/support/tickets/11111"
	tcSupportTickets11111Close                       = "/support/tickets/11111/close"
	tcSupportTickets11111Replies                     = "/support/tickets/11111/replies"
	tcSupportTickets123Attachments                   = "/support/tickets/123/attachments"
	tcSupportTickets123Replies                       = "/support/tickets/123/replies"
	tcTagsProd                                       = "/tags/prod"
	tcTestFw                                         = "test-fw"
	tcTestuser                                       = "testuser"
	tcTicketCreate                                   = "ticket_create"
	tcTicketOpen                                     = "ticket-open"
	tcTokenQueryFrag                                 = "token/..?query#frag"
	tcUpdated                                        = "Updated"
	tcUpdatedExampleCom                              = "updated@example.com"
	tcUpdatedFw                                      = "updated-fw"
	tcUserNameQuery                                  = "user/name?query"
	tcVolumes333Clone                                = "/volumes/333/clone"
	tcWeAreInvestigatingThisTicket                   = "We are investigating this ticket."
)

// Repeated literals extracted to satisfy goconst.
const (
	tcPermissions = "permissions"
)
