package main

import (
	"fmt"
	"slices"
	"sort"
	"strings"

	"google.golang.org/protobuf/reflect/protoreflect"

	linodev1 "github.com/chadit/LinodeMCP/go/internal/genpb/linode/mcp/v1"
	"github.com/chadit/LinodeMCP/go/internal/goname"
	"github.com/chadit/LinodeMCP/go/internal/linoderoute"
)

// generatedHeader marks every emitted file. `make proto` wipes and rewrites the
// tree on every run, so an edit to a generated file does not survive.
const generatedHeader = "// Code generated by go/cmd/toolgen from the linode.mcp.v1 proto contract. DO NOT EDIT."

// Import paths the emitted code can need. Each emitter reports the ones it used
// and the file writes the union.
const (
	importContext     = "context"
	importJSON        = "encoding/json"
	importErrors      = "errors"
	importFmt         = "fmt"
	importMCP         = "github.com/mark3labs/mcp-go/mcp"
	importConfig      = "github.com/chadit/LinodeMCP/go/internal/config"
	importGenpb       = "linodev1 \"github.com/chadit/LinodeMCP/go/internal/genpb/linode/mcp/v1\""
	importLinode      = "github.com/chadit/LinodeMCP/go/internal/linode"
	importLinoderoute = "github.com/chadit/LinodeMCP/go/internal/linoderoute"
	importProfiles    = "github.com/chadit/LinodeMCP/go/internal/profiles"
	importProto       = "google.golang.org/protobuf/proto"
	importStructpb    = "google.golang.org/protobuf/types/known/structpb"
	importTime        = "time"
	importTools       = "github.com/chadit/LinodeMCP/go/internal/tools"
	importToolschemas = "github.com/chadit/LinodeMCP/go/internal/toolschemas"
	importTwostage    = "github.com/chadit/LinodeMCP/go/internal/twostage"
)

// errorPlaceholder is the one message-template name that is not an input field:
// it stands for the failure being reported.
const errorPlaceholder = "error"

// nilLiteral is what an emitted argument reads as when the tool has nothing to
// pass there: no path value, no body.
const nilLiteral = "nil"

// emptyLiteral is the emitted empty string, which stands for both an argument
// nobody supplied and a query the tool publishes nothing for.
const emptyLiteral = `""`

// textType is the emitted Go type for a value that arrives as text, which is
// what a label reads as whether it addresses a resource or filters a page.
const textType = "string"

// importToolvalidate is taken by every file holding a handler the emitter
// writes the body of, since each one asks the contract for its rules first.
const importToolvalidate = "github.com/chadit/LinodeMCP/go/internal/toolvalidate"

// importToolwalk is taken only by a file holding a tool that declares a walk
// over one of its open-object arguments.
const importToolwalk = "github.com/chadit/LinodeMCP/go/internal/toolwalk"

// source is one emitted file under construction.
type source struct {
	imports map[string]struct{}
	body    strings.Builder
}

func newSource() *source {
	return &source{imports: make(map[string]struct{})}
}

// need records an import the emitted code takes.
func (s *source) need(paths ...string) {
	for _, path := range paths {
		s.imports[path] = struct{}{}
	}
}

// writef appends a line of emitted code.
func (s *source) writef(format string, args ...any) {
	fmt.Fprintf(&s.body, format+"\n", args...)
}

// render assembles the finished file. The caller runs the result through
// go/format, so the indentation written here does not have to be exact.
func (s *source) render(pkg string) string {
	paths := make([]string, 0, len(s.imports))
	for path := range s.imports {
		paths = append(paths, path)
	}

	sort.Strings(paths)

	var file strings.Builder

	file.Grow(s.body.Len() + len(generatedHeader))
	file.WriteString(generatedHeader)
	file.WriteString("\n\npackage ")
	file.WriteString(pkg)
	file.WriteString("\n\nimport (\n")
	writeImportBlock(&file, paths)
	file.WriteString(")\n\n")
	file.WriteString(s.body.String())

	return file.String()
}

// writeImportBlock writes imports in the two groups goimports keeps, standard
// library first. Emitting them already grouped is what lets the generated tree
// pass the same format gate as hand-written code.
func writeImportBlock(file *strings.Builder, paths []string) {
	standard, external := splitImports(paths)

	// Each entry writes its path plus a tab, quotes, and a newline.
	const perImportOverhead = 4

	total := len(paths) * perImportOverhead
	for _, path := range paths {
		total += len(path)
	}

	file.Grow(total)

	for _, path := range standard {
		writeImportLine(file, path)
	}

	if len(standard) > 0 && len(external) > 0 {
		file.WriteString("\n")
	}

	for _, path := range external {
		writeImportLine(file, path)
	}
}

// splitImports separates standard-library paths from the rest. A dot in the
// first segment names a host, which every non-standard module path begins with.
func splitImports(paths []string) ([]string, []string) {
	standard := make([]string, 0, len(paths))
	external := make([]string, 0, len(paths))

	for _, path := range paths {
		head, _, _ := strings.Cut(strings.Trim(importPath(path), "\""), "/")
		if strings.Contains(head, ".") {
			external = append(external, path)

			continue
		}

		standard = append(standard, path)
	}

	return standard, external
}

// writeImportLine writes one indented import entry. The parts go in separately
// rather than concatenated, which is what keeps the builder from allocating a
// joined string per import only to copy it straight back out.
func writeImportLine(file *strings.Builder, path string) {
	file.WriteString("\t")
	file.WriteString(importLine(path))
	file.WriteString("\n")
}

// importLine quotes a bare import path. An aliased entry already carries its
// own quotes, so it passes through as written.
func importLine(path string) string {
	if strings.Contains(path, "\"") {
		return path
	}

	return "\"" + path + "\""
}

// importPath strips an alias from an import entry, leaving the quoted path.
func importPath(entry string) string {
	if alias, path, aliased := strings.Cut(entry, " "); aliased {
		_ = alias

		return path
	}

	return entry
}

// checkTierDeclarations refuses a declaration whose tier has no place to act on
// it. Each one would otherwise be dropped during emission, which reads as the
// tool having been given something it never received.
func checkTierDeclarations(tool *contract) error {
	rewrites := len(tool.Normalizes) > 0 || tool.Fold != nil
	if rewrites && (tool.Tier == tierList ||
		tool.Tier == tierSubresourceList || tool.Tier == tierDestroy) {
		return fmt.Errorf("%w: %s", errNoNormalizePoint, tool.Name)
	}

	if err := checkTransportTier(tool); err != nil {
		return err
	}

	// The stand-in reaches the reported body through the tier's own driver, and
	// only the acknowledge one carries it. On another tier Python would report
	// the value the call sends while Go stood in for it, which is the one thing
	// a declaration read by both must never do.
	if len(tool.PreviewStandIns) > 0 && tool.Tier != tierAcknowledge {
		return fmt.Errorf("%w: %s", errPreviewStandInTier, tool.Name)
	}

	// A removal reads its ids through tools.DestroyID, which answers three
	// sentences of its own, so a reader here would be dropped rather than
	// applied.
	if len(tool.Readers) > 0 && tool.Tier == tierDestroy {
		return fmt.Errorf("%w: %s", errReaderOnDestroy, tool.Name)
	}

	return nil
}

// checkTransportTier holds a declared transport to a tier with somewhere to put
// its answer. The acknowledge, get and body-read tiers assemble theirs rather
// than decoding one. The destroy tier assembles the same way and takes the
// removal arm alone: every other arm hands back measurements a destroy response
// has no member for.
func checkTransportTier(tool *contract) error {
	if !tool.transported() {
		return nil
	}

	if tool.Tier == tierDestroy {
		if tool.Transport.Kind == transportPresignRemove {
			return nil
		}

		return fmt.Errorf("%w: %s", errUngatedExecute, tool.Name)
	}

	if tool.Transport.Kind == transportPresignRemove {
		return fmt.Errorf("%w: %s", errUngatedExecute, tool.Name)
	}

	if tool.Tier != tierAcknowledge && tool.Tier != tierGet && tool.Tier != tierBodyRead {
		return fmt.Errorf("%w: %s", errUngatedExecute, tool.Name)
	}

	return nil
}

// emitTool writes one tool's factory and handler.
func emitTool(out *source, tool *contract) error {
	if err := checkTierDeclarations(tool); err != nil {
		return err
	}

	switch tool.Tier {
	case tierMeta:
		return emitMeta(out, tool)
	case tierGet:
		return emitGet(out, tool)
	case tierList, tierSubresourceList:
		return emitList(out, tool)
	case tierMarkerList:
		return emitMarkerList(out, tool)
	case tierBodyRead:
		return emitBodyRead(out, tool)
	case tierWrite:
		return emitWrite(out, tool)
	case tierAcknowledge:
		return emitAcknowledge(out, tool)
	case tierDestroy:
		return emitDestroy(out, tool)
	case tierUnknown:
	}

	return fmt.Errorf("%w: %s", errUnsupportedTier, tool.Name)
}

// emitGet writes a tool that fetches one resource and serializes it.
func emitGet(out *source, tool *contract) error {
	if tool.ErrorMessage == "" {
		return fmt.Errorf("%w: %s", errNoErrorMessage, tool.Name)
	}

	// A preview with no gate over it is a shape this tier does not write: the
	// confirm argument is what says the read is gated, and without it there is
	// nothing to hold the fetch back while the preview branch answers.
	if tool.DryRun && !tool.Confirm {
		return fmt.Errorf("%w: %s", errNoReadPreview, tool.Name)
	}

	if tool.DryRun && tool.ConfirmMessage == "" {
		return fmt.Errorf("%w: %s", errNoConfirmMessage, tool.Name)
	}

	out.need(importContext, importFmt, importMCP, importConfig,
		importProfiles, importTools, importToolschemas)

	// A free-form read fills no generated message, so the file takes the
	// generated types only for the reads that decode into one.
	if !tool.StructResponse {
		out.need(importGenpb)
	}

	factory := factoryName(tool.Name)
	handler := handlerName(tool.Name)

	out.writef("// %s builds %s, which %s", factory, tool.Name, describeRoute(tool))
	out.writef("func %s(cfg *config.Config) (mcp.Tool, profiles.Capability, tools.Handler) {", factory)
	out.writef("\ttool := mcp.NewToolWithRawSchema(")
	out.writef("\t\t%s,", goStringLiteral(tool.Name))
	out.writef("\t\t%s,", goStringLiteral(tool.Description))
	out.writef("\t\ttoolschemas.Schema(%s),", goStringLiteral(tool.InputMessage))
	out.writef("\t)")
	out.writef("")
	out.writef("\thandler := func(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {")
	out.writef("\t\treturn %s(ctx, &request, cfg)", handler)
	out.writef("\t}")
	out.writef("")
	out.writef("\treturn tool, profiles.%s, handler", capabilityConstant(tool.Capability))
	out.writef("}")
	out.writef("")

	if err := emitGetHandler(out, tool, handler); err != nil {
		return err
	}

	if !tool.DryRun {
		return nil
	}

	return emitGetPreview(out, tool)
}

// emitGetHandler writes the body behind a single-resource factory.
func emitGetHandler(out *source, tool *contract, handler string) error {
	ordered, err := tool.orderedPathFields()
	if err != nil {
		return err
	}

	failure, err := tool.formatMessage(tool.ErrorMessage)
	if err != nil {
		return err
	}

	out.writef("func %s(ctx context.Context, request *mcp.CallToolRequest, cfg *config.Config) (*mcp.CallToolResult, error) {", handler)

	emitGatedReadOpening(out, tool)
	emitNormalize(out, tool)
	emitConstraintCheck(out, tool)

	for _, entry := range ordered {
		if err := emitRequiredPathArg(out, tool, &entry); err != nil {
			return err
		}
	}

	// A failure sentence can name a query argument, which nothing above has read
	// into a local: the query builder reads them straight out of the request.
	emitPathArgReads(out, namedLocals(tool.Query, failure.args))

	// A gated read has already asked, ahead of the reads above, for the reason
	// emitGatedReadOpening gives.
	if tool.ConfirmMessage != "" && !tool.DryRun {
		out.writef("\tif result := tools.RequireConfirm(request, %s); result != nil {",
			goStringLiteral(tool.ConfirmMessage))
		out.writef("\t\treturn result, nil")
		out.writef("\t}")
		out.writef("")
	}

	// A transport that owns the call takes no query: the routes needing one
	// answer with something a decode can place, so nothing reaches this branch
	// with parameters to build.
	if !tool.transported() {
		if err := emitGetQuery(out, tool); err != nil {
			return err
		}
	}

	out.writef("\tclient, err := tools.ClientForRequest(request, cfg)")
	out.writef("\tif err != nil {")
	out.writef("\t\treturn mcp.NewToolResultError(err.Error()), nil")
	out.writef("\t}")
	out.writef("")

	if tool.transported() {
		return emitAssembledRead(out, tool, ordered, failure)
	}

	if tool.StructResponse {
		return emitStructFetch(out, tool, ordered, failure)
	}

	out.writef("\tresponse := &linodev1.%s{}", tool.ResponseGo.TypeName)
	out.writef("")

	emitGetFetch(out, tool, ordered)

	out.writef("\t\treturn mcp.NewToolResultError(fmt.Sprintf(%s)), nil", failure.call("err"))
	out.writef("\t}")
	out.writef("")
	out.writef("\treturn %s", getResult(tool))
	out.writef("}")
	out.writef("")

	return nil
}

// emitAssembledRead writes the tail of a read whose call its transport makes:
// the OAuth client thumbnail route answers with raw PNG bytes, so there is
// nothing to decode and the answer is built from what the transfer brought back
// beside the ids the call was addressed by.
func emitAssembledRead(out *source, tool *contract, ordered []field, failure formatted) error {
	out.need(importGenpb)

	emitTransportCall(out, tool, pathValuesLiteral(ordered))
	out.writef("\t\treturn mcp.NewToolResultError(fmt.Sprintf(%s)), nil", failure.call("err"))
	out.writef("\t}")
	out.writef("")
	out.writef("\treturn tools.MarshalProtoToolResponse(&linodev1.%s{", tool.ResponseGo.TypeName)

	for index := range tool.Echoes {
		echo := &tool.Echoes[index]

		value, err := echoValue(tool.Name, echo)
		if err != nil {
			return err
		}

		out.writef("\t\t%s: %s,", echo.GoName, value)
	}

	if err := emitTransportMembers(out, tool); err != nil {
		return err
	}

	out.writef("\t})")
	out.writef("}")
	out.writef("")

	return nil
}

// emitGetFetch writes the call a read makes, opening the failure branch its
// caller closes. A read restoring explicit nulls keeps the body it decoded,
// because protojson emits no member for the ones the API sent as null.
func emitGetFetch(out *source, tool *contract, ordered []field) {
	if len(tool.ExplicitNulls) == 0 {
		out.writef("\tif err := client.CallProtoRouteQuery(ctx, %s, %s, query, response); err != nil {",
			goStringLiteral(tool.Name), pathValuesLiteral(ordered))

		return
	}

	out.writef("\traw, err := client.CallProtoRouteQueryRaw(ctx, %s, %s, query, response)",
		goStringLiteral(tool.Name), pathValuesLiteral(ordered))
	out.writef("\tif err != nil {")
}

// emitGatedReadOpening writes the two branches a gated read opens with: the
// preview a dry run answers, and the gate the fetch waits behind.
//
// The gate is asked before the arguments are read for the reason the write
// tiers ask it there: a caller who has not confirmed learns nothing about
// whether their arguments would have been accepted, which for a read whose
// whole answer is a secret is the point of having a gate at all.
func emitGatedReadOpening(out *source, tool *contract) {
	if !tool.DryRun {
		return
	}

	out.writef("\tif tools.IsDryRun(request) {")
	out.writef("\t\treturn %s(ctx, request, cfg)", previewName(tool.Name))
	out.writef("\t}")
	out.writef("")
	out.writef("\tif result := tools.RequireConfirm(request, %s); result != nil {",
		goStringLiteral(tool.ConfirmMessage))
	out.writef("\t\treturn result, nil")
	out.writef("\t}")
	out.writef("")
}

// emitStructFetch writes the tail of a read whose API body has no proto model:
// the object is decoded as it arrived and answered as it arrived, since there
// is no message to place it in and nothing to reorder it by.
//
// The serializer is handed the failure sentence with its trailing error trimmed
// off, because it appends the conversion error itself. Both ways this read can
// fail therefore report the same sentence.
func emitStructFetch(out *source, tool *contract, ordered []field, failure formatted) error {
	prefix, err := tool.structFailPrefix()
	if err != nil {
		return err
	}

	out.writef("\traw, err := client.CallRouteObject(ctx, %s, %s, query)",
		goStringLiteral(tool.Name), pathValuesLiteral(ordered))
	out.writef("\tif err != nil {")
	out.writef("\t\treturn mcp.NewToolResultError(fmt.Sprintf(%s)), nil", failure.call("err"))
	out.writef("\t}")
	out.writef("")
	out.writef("\treturn tools.MarshalStructToolResponse(raw, %s)", prefix.literal())
	out.writef("}")
	out.writef("")

	return nil
}

// emitGetPreview writes the dry-run branch of a gated read: the same argument
// checks, and the call reported rather than made.
func emitGetPreview(out *source, tool *contract) error {
	ordered, err := tool.orderedPathFields()
	if err != nil {
		return err
	}

	path, err := tool.pathExpression(out)
	if err != nil {
		return err
	}

	out.writef("// %s answers %s's dry run: the same checks, and the call reported", previewName(tool.Name), tool.Name)
	out.writef("// rather than made.")
	out.writef("func %s(ctx context.Context, request *mcp.CallToolRequest, cfg *config.Config) (*mcp.CallToolResult, error) {",
		previewName(tool.Name))

	emitNormalize(out, tool)
	emitConstraintCheck(out, tool)

	for _, entry := range ordered {
		if err := emitRequiredPathArg(out, tool, &entry); err != nil {
			return err
		}
	}

	if tool.declaresPreview() {
		emitDeclaredPreview(out, tool, ordered, goStringLiteral(tool.Method), path, nilLiteral)
		out.writef("}")
		out.writef("")

		return nil
	}

	// A read sends nothing, so the preview reports the route alone.
	out.writef("\treturn tools.RunDryRunPreviewWithBody(ctx, request, cfg, %s, %s, %s, nil, nil)",
		goStringLiteral(tool.Name), goStringLiteral(tool.Method), path)
	out.writef("}")
	out.writef("")

	return nil
}

// emitGetQuery writes the query a single-resource call carries. Nearly every
// read carries none, and the ones that do split the same two ways a collection
// does: the page controls a route publishes, and the parameters it filters on.
//
// A read with no query still declares the empty local, because its call site
// passes one either way.
func emitGetQuery(out *source, tool *contract) error {
	if len(tool.Query) == 0 {
		out.writef("\tquery := \"\"")
		out.writef("")

		return nil
	}

	return emitQueryBuild(out, tool)
}

// emitQueryBuild writes the query a call carries out of the arguments the tool
// publishes for it, for the call sites that have at least one. A tool with none
// declares no local: a mutation names the query variant of its routed primitive
// only when there is a query, so an empty one there would go unread.
func emitQueryBuild(out *source, tool *contract) error {
	page, forwarded := splitPageControls(tool.Query)

	if len(page) > 0 && len(page) != pageControlCount {
		return fmt.Errorf("%w: %s publishes %s alone, and the page controls are read as a pair",
			errUnsupportedQuery, tool.Name, queryNames(page))
	}

	out.need(importTools)

	if len(page) > 0 {
		out.writef("\tquery, message := tools.StandardPageQuery(request)")
		out.writef("\tif message != \"\" {")
		out.writef("\t\treturn mcp.NewToolResultError(message), nil")
		out.writef("\t}")
		out.writef("")
	}

	if len(page) == 0 {
		out.writef("\tquery := tools.WithQueryArguments(request, \"\", %s)", queryArgumentList(forwarded))
		out.writef("")

		return nil
	}

	if len(forwarded) > 0 {
		out.writef("\tquery = tools.WithQueryArguments(request, query, %s)", queryArgumentList(forwarded))
		out.writef("")
	}

	return nil
}

// getResult is the answer a single-resource read serializes. A tool whose
// declared response is its own envelope answers with the decoded resource
// inside that envelope, which is the shape both languages have always shipped
// for it, so the wrapper is filled here rather than dropped.
func getResult(tool *contract) string {
	if len(tool.ExplicitNulls) > 0 {
		return "tools.MarshalProtoToolResponseRestoringNulls(response" + marshalTail(tool, "")
	}

	if tool.WrapperField == "" {
		return "tools.MarshalProtoToolResponse(response)"
	}

	return fmt.Sprintf("tools.MarshalProtoToolResponse(&linodev1.%s{%s: response})",
		tool.WrapperType, tool.WrapperField)
}

// pageControlCount is how many arguments the standard page is read from.
const pageControlCount = 2

// splitPageControls separates the standard page controls from the parameters a
// route filters on.
func splitPageControls(query []field) ([]field, []field) {
	page := make([]field, 0, pageControlCount)
	forwarded := make([]field, 0, len(query))

	for _, entry := range query {
		if isPaginationParam(entry.ProtoName) {
			page = append(page, entry)

			continue
		}

		forwarded = append(forwarded, entry)
	}

	return page, forwarded
}

// queryArgumentList renders the forwarded arguments as the variadic names the
// query builder reads them under.
func queryArgumentList(forwarded []field) string {
	names := make([]string, 0, len(forwarded))
	for _, entry := range forwarded {
		names = append(names, goStringLiteral(entry.ProtoName))
	}

	return strings.Join(names, ", ")
}

// queryNames lists query arguments for a refusal.
func queryNames(query []field) string {
	names := make([]string, 0, len(query))
	for _, entry := range query {
		names = append(names, entry.ProtoName)
	}

	return strings.Join(names, ", ")
}

// emitConstraintCheck writes the call that evaluates the rules the tool's input
// message declares. It is written for every tool rather than only the ones that
// declare rules, so declaring one is a proto edit and nothing else; the seam
// answers immediately for a message with none.
func emitConstraintCheck(out *source, tool *contract) {
	out.need(importToolvalidate)
	out.writef("\tif message := toolvalidate.Check(%s, request.GetArguments()); message != \"\" {",
		goStringLiteral(tool.InputMessage))
	out.writef("\t\treturn mcp.NewToolResultError(message), nil")
	out.writef("\t}")
	out.writef("")

	emitArgumentRefusals(out, tool)
}

// emitArgumentRefusals writes the whole-map refusals every tool answers, the
// allowlist and sentences left to the engine so the list drivers answer alike.
//
// They sit beside the rules because both answer for a value no rule sees: an
// undeclared argument is dropped before the rules run, so without this the
// call succeeds over a value the API never saw.
func emitArgumentRefusals(out *source, tool *contract) {
	out.need(importTools, importMCP)
	out.writef("\tif message := tools.CheckArgumentRefusals(%s, %s, request.GetArguments()); message != \"\" {",
		goStringLiteral(tool.InputMessage), goStringLiteral(tool.Name))
	out.writef("\t\treturn mcp.NewToolResultError(message), nil")
	out.writef("\t}")
	out.writef("")
}

// goNameList is a run of argument names as Go string literals.
func goNameList(names []string) string {
	quoted := make([]string, 0, len(names))
	for _, name := range names {
		quoted = append(quoted, goStringLiteral(name))
	}

	return strings.Join(quoted, ", ")
}

// emitNormalize writes a tool's argument rewrite, which runs before anything
// reads an argument so every later read sees one value.
func emitNormalize(out *source, tool *contract) {
	if len(tool.Normalizes) == 0 && tool.Fold == nil {
		return
	}

	out.need(importTools)

	rendering := normalizeRendering()
	for _, rewrite := range tool.Normalizes {
		out.writef("\ttools.%s(request, %s)",
			rendering[rewrite.Transform].Go, goNameList(rewrite.Fields))
	}

	if tool.Fold != nil {
		out.writef("\ttools.FoldIntList(request, %s, %s, %s)",
			goStringLiteral(tool.Fold.Source), goStringLiteral(tool.Fold.Target),
			goStringLiteral(tool.Fold.Key))
	}

	out.writef("")
}

// emitPathArgReads writes path parameter reads without checks, for the locals a
// failure sentence names that nothing above has read.
func emitPathArgReads(out *source, ordered []field) {
	if len(ordered) == 0 {
		return
	}

	for _, entry := range ordered {
		reader, zero, ok := pathArgReader(entry.Kind)
		if !ok {
			continue
		}

		out.writef("\t%s := request.%s(%s, %s)", entry.GoLocal, reader, goStringLiteral(entry.ProtoName), zero)
	}

	out.writef("")
}

// emitRequiredPathArg writes the read and the required check for one path
// parameter. A missing value would address the collection instead of the
// resource in it, so the check is not optional.
//
// A field declaring a shared reader is checked by that reader instead. The
// difference is the sentence: the derived check below answers "is required" for
// every way a value can be unusable, where the readers separate an absent
// argument from a present one that is not an id. Both read the local the rest
// of the handler goes on to use, so only the refusal wording differs.
func emitRequiredPathArg(out *source, tool *contract, entry *field) error {
	if declared, ok := tool.Readers[entry.ProtoName]; ok {
		return emitReaderCheck(out, tool, declared, entry)
	}

	reader, zero, ok := pathArgReader(entry.Kind)
	if !ok {
		return fmt.Errorf("%w: %s is %s", errUnsupportedPathKind, entry.ProtoName, entry.Kind)
	}

	out.writef("\t%s := request.%s(%s, %s)", entry.GoLocal, reader, goStringLiteral(entry.ProtoName), zero)
	out.writef("\tif %s == %s {", entry.GoLocal, zero)
	out.writef("\t\treturn mcp.NewToolResultError(%s), nil", goStringLiteral(entry.ProtoName+" is required"))
	out.writef("\t}")
	out.writef("")

	return nil
}

// readerCall is the Go expression one declared reader is spelled as, taking the
// tool and the field so a membership check can read its declared vocabulary.
// Each member maps to the function that already answers its sentences, so the
// wording is whatever that function has always said.
func readerCall(tool *contract, declared linodev1.ArgumentReader, entry *field) (string, bool) {
	argument := goStringLiteral(entry.ProtoName)
	sentences := tool.Sentences[entry.ProtoName]

	switch declared {
	case linodev1.ArgumentReader_ARGUMENT_READER_POSITIVE_ID:
		if sentences != nil {
			return fmt.Sprintf("tools.DeclaredIDArgument(request, %s, 0, %s, %s)", argument,
				goStringLiteral(sentences.GetAbsent()), goStringLiteral(sentences.GetRefused())), true
		}

		return fmt.Sprintf("tools.RequiredIDArgument(request, %s)", argument), true
	case linodev1.ArgumentReader_ARGUMENT_READER_BOUNDED_ID:
		if sentences != nil {
			return fmt.Sprintf("tools.DeclaredIDArgument(request, %s, tools.MaxJSONSafeID, %s, %s)", argument,
				goStringLiteral(sentences.GetAbsent()), goStringLiteral(sentences.GetRefused())), true
		}

		return fmt.Sprintf(
			"tools.RequiredBoundedIDArgument(request, %s, tools.MaxJSONSafeID)", argument,
		), true
	case linodev1.ArgumentReader_ARGUMENT_READER_PATH_SAFE_TEXT:
		if sentences != nil {
			return fmt.Sprintf("tools.DeclaredPathSafeArgument(request, %s, %s, %s, %s)", argument,
				goStringLiteral(sentences.GetAbsent()), goStringLiteral(sentences.GetUnusable()),
				goStringLiteral(sentences.GetRefused())), true
		}

		return fmt.Sprintf("tools.RequiredPathSafeArgument(request, %s)", argument), true
	case linodev1.ArgumentReader_ARGUMENT_READER_FRAGMENT_SAFE_TEXT:
		return fmt.Sprintf("tools.DeclaredFragmentSafeArgument(request, %s, %s, %s, %s)", argument,
			goStringLiteral(sentences.GetAbsent()), goStringLiteral(sentences.GetUnusable()),
			goStringLiteral(sentences.GetRefused())), true
	case linodev1.ArgumentReader_ARGUMENT_READER_SERVICE_TYPE_SLUG:
		return slugReaderCall("ServiceTypeSlug", argument, sentences), true
	case linodev1.ArgumentReader_ARGUMENT_READER_REGION_SLUG:
		return slugReaderCall("RegionSlug", argument, sentences), true
	case linodev1.ArgumentReader_ARGUMENT_READER_BETA_SLUG:
		return slugReaderCall("BetaSlug", argument, sentences), true
	case linodev1.ArgumentReader_ARGUMENT_READER_FREE_TEXT:
		if sentences != nil {
			return fmt.Sprintf("tools.DeclaredFreeText(request, %s, %s, %s)", argument,
				goStringLiteral(sentences.GetAbsent()), goStringLiteral(sentences.GetUnusable())), true
		}

		return fmt.Sprintf("tools.FreeTextArgument(request, %s)", argument), true
	case linodev1.ArgumentReader_ARGUMENT_READER_ENUM_MEMBER:
		return memberChoiceCall(tool, entry), true
	// The presence family is not spelled here: each member reads the argument
	// map beside the body build rather than a path slot, so
	// emitBodyPresenceChecks writes them.
	case linodev1.ArgumentReader_ARGUMENT_READER_PRESENT,
		linodev1.ArgumentReader_ARGUMENT_READER_PRESENT_TEXT,
		linodev1.ArgumentReader_ARGUMENT_READER_PRESENT_BOOL,
		linodev1.ArgumentReader_ARGUMENT_READER_PRESENT_STRING,
		linodev1.ArgumentReader_ARGUMENT_READER_ID_LIST,
		linodev1.ArgumentReader_ARGUMENT_READER_UNSPECIFIED:
		return "", false
	}

	return "", false
}

// slugReaderCall is the Go expression one named format reader is spelled as.
// The three slug members answer the same three arms through the same shape, so
// the member picks the function and the declaration fills the wording.
func slugReaderCall(reader, argument string, sentences *linodev1.ReaderMessage) string {
	if sentences == nil {
		return fmt.Sprintf("tools.%sArgument(request, %s)", reader, argument)
	}

	return fmt.Sprintf("tools.Declared%s(request, %s, %s, %s, %s)", reader, argument,
		goStringLiteral(sentences.GetAbsent()), goStringLiteral(sentences.GetUnusable()),
		goStringLiteral(sentences.GetRefused()))
}

// memberChoiceCall is the Go expression a membership check is spelled as: the
// shared reader handed the raw argument name, whether the field is required,
// and the vocabulary the contract resolved for it. The helper composes the
// sentences from those names, so no wording is restated here.
func memberChoiceCall(tool *contract, entry *field) string {
	members := tool.Members[entry.ProtoName]
	quoted := make([]string, 0, len(members))

	for _, member := range members {
		quoted = append(quoted, goStringLiteral(member))
	}

	if sentences := tool.Sentences[entry.ProtoName]; sentences != nil {
		return fmt.Sprintf("tools.DeclaredMemberChoice(request, %s, %t, %s, %s, %s)",
			goStringLiteral(entry.ProtoName), !entry.Presence,
			goStringLiteral(sentences.GetAbsent()), goStringLiteral(sentences.GetRefused()),
			strings.Join(quoted, ", "))
	}

	return fmt.Sprintf("tools.MemberChoiceArgument(request, %s, %t, %s)",
		goStringLiteral(entry.ProtoName), !entry.Presence, strings.Join(quoted, ", "))
}

// idListCall is the Go expression an id-list check is spelled as.
func idListCall(tool *contract, entry *field) string {
	argument := goStringLiteral(entry.ProtoName)

	if sentences := tool.Sentences[entry.ProtoName]; sentences != nil {
		return fmt.Sprintf("tools.DeclaredIDList(request, %s, %s, %s, %s)", argument,
			goStringLiteral(sentences.GetAbsent()), goStringLiteral(sentences.GetUnusable()),
			goStringLiteral(sentences.GetRefused()))
	}

	return fmt.Sprintf("tools.IDListArgument(request, %s)", argument)
}

// presenceCall is the Go expression a PRESENT_TEXT or PRESENT_BOOL check is
// spelled as, kind naming which of the two. Both read the same two arms, so
// one spelling covers them and the member picks the reader.
func presenceCall(tool *contract, kind string, entry *field) string {
	argument := goStringLiteral(entry.ProtoName)

	if sentences := tool.Sentences[entry.ProtoName]; sentences != nil {
		return fmt.Sprintf("tools.DeclaredPresent%s(request, %s, %t, %s, %s)", kind, argument,
			!entry.Presence, goStringLiteral(sentences.GetAbsent()), goStringLiteral(sentences.GetUnusable()))
	}

	return fmt.Sprintf("tools.Present%sArgument(request, %s, %t)", kind, argument, !entry.Presence)
}

// emitBodyPresenceChecks writes the argument-map check each BODY field
// declaring a reader asks for: PRESENT's presence question, or ENUM_MEMBER's
// membership one. It is a separate emission point from the path readers because
// the question is about the arguments the caller sent, not about a value the
// request carries, and because a body field has no path slot to be read into.
func emitBodyPresenceChecks(out *source, tool *contract) error {
	for _, entry := range tool.Body {
		declared, ok := tool.Readers[entry.ProtoName]
		if !ok {
			continue
		}

		switch declared {
		case linodev1.ArgumentReader_ARGUMENT_READER_PRESENT:
			out.need(importTools, importMCP)
			out.writef("\tif message := tools.RequiredPresentArgument(request, %s); message != \"\" {",
				goStringLiteral(entry.ProtoName))
		case linodev1.ArgumentReader_ARGUMENT_READER_PRESENT_TEXT:
			out.need(importTools, importMCP)
			out.writef("\tif message := %s; message != \"\" {", presenceCall(tool, "Text", &entry))
		case linodev1.ArgumentReader_ARGUMENT_READER_PRESENT_BOOL:
			out.need(importTools, importMCP)
			out.writef("\tif message := %s; message != \"\" {", presenceCall(tool, "Bool", &entry))
		case linodev1.ArgumentReader_ARGUMENT_READER_PRESENT_STRING:
			out.need(importTools, importMCP)
			out.writef("\tif message := %s; message != \"\" {", presenceCall(tool, "String", &entry))
		case linodev1.ArgumentReader_ARGUMENT_READER_ID_LIST:
			out.need(importTools, importMCP)
			out.writef("\tif message := %s; message != \"\" {", idListCall(tool, &entry))
		case linodev1.ArgumentReader_ARGUMENT_READER_ENUM_MEMBER:
			out.need(importTools, importMCP)
			out.writef("\tif _, message := %s; message != \"\" {", memberChoiceCall(tool, &entry))
		case linodev1.ArgumentReader_ARGUMENT_READER_UNSPECIFIED,
			linodev1.ArgumentReader_ARGUMENT_READER_POSITIVE_ID,
			linodev1.ArgumentReader_ARGUMENT_READER_BOUNDED_ID,
			linodev1.ArgumentReader_ARGUMENT_READER_PATH_SAFE_TEXT,
			linodev1.ArgumentReader_ARGUMENT_READER_FRAGMENT_SAFE_TEXT,
			linodev1.ArgumentReader_ARGUMENT_READER_SERVICE_TYPE_SLUG,
			linodev1.ArgumentReader_ARGUMENT_READER_REGION_SLUG,
			linodev1.ArgumentReader_ARGUMENT_READER_BETA_SLUG,
			linodev1.ArgumentReader_ARGUMENT_READER_FREE_TEXT:
			return fmt.Errorf("%w: %s declares %s", errUnsupportedReader, entry.ProtoName, declared)
		default:
			return fmt.Errorf("%w: %s declares %s", errUnsupportedReader, entry.ProtoName, declared)
		}

		out.writef("\t\treturn mcp.NewToolResultError(message), nil")
		out.writef("\t}")
		out.writef("")
	}

	return nil
}

// emitObjectWalks writes the call that evaluates the open-object walks the
// tool's input message declares. Only the message name travels: the walker
// reads the declaration from the descriptor, the same way the rule check above
// it does, so declaring a walk is a proto edit and nothing else.
//
// It sits after the per-field readers and before the cross-field any-of
// question, which is the order the hand-written checks it replaced answered in:
// each argument
// answers for its own shape, then for what is inside it, then the call answers
// for naming nothing.
func emitObjectWalks(out *source, tool *contract) {
	if !tool.Walks {
		return
	}

	out.need(importToolwalk, importMCP)
	out.writef("\tif message := toolwalk.Check(%s, request.GetArguments()); message != \"\" {",
		goStringLiteral(tool.InputMessage))
	out.writef("\t\treturn mcp.NewToolResultError(message), nil")
	out.writef("\t}")
	out.writef("")
}

// emitAnyOfCheck writes the message-level require_any_of check, after the
// per-field presence checks and before the body is built, which is the order
// the hand-written checks it replaced answered in. The sentence travels as a
// literal because
// the contract resolved it already, derived or declared.
func emitAnyOfCheck(out *source, tool *contract) {
	if tool.AnyOf == nil {
		return
	}

	quoted := make([]string, 0, len(tool.AnyOf.Fields))
	for _, name := range tool.AnyOf.Fields {
		quoted = append(quoted, goStringLiteral(name))
	}

	out.need(importTools, importMCP)
	out.writef("\tif message := tools.RequireAnyArgument(request, %s, %s); message != \"\" {",
		goStringLiteral(tool.AnyOf.Message), strings.Join(quoted, ", "))
	out.writef("\t\treturn mcp.NewToolResultError(message), nil")
	out.writef("\t}")
	out.writef("")
}

// emitReaderCheck writes the call to the shared reader one argument declares.
// The reader answers the value beside the sentence, so this both checks the
// argument and reads the local, which is why it stands in for the whole derived
// read-and-check rather than sitting beside it.
func emitReaderCheck(out *source, tool *contract, declared linodev1.ArgumentReader, entry *field) error {
	call, known := readerCall(tool, declared, entry)
	if !known {
		return fmt.Errorf("%w: %s declares %s", errUnsupportedReader, entry.ProtoName, declared)
	}

	out.need(importTools, importMCP)
	out.writef("\t%s, message := %s", entry.GoLocal, call)
	out.writef("\tif message != \"\" {")
	out.writef("\t\treturn mcp.NewToolResultError(message), nil")
	out.writef("\t}")
	out.writef("")

	return nil
}

// pathArgReader names the request accessor a path parameter is read through and
// the zero value that means the caller omitted it. Linode addresses resources by
// integer id or by label, so a route segment carries nothing else.
//
// An enum reads as a string because that is what a segment carries and what the
// caller sends: /lke/tiers/{tier}/versions takes "standard", not the number the
// generated Go enum holds it under.
func pathArgReader(kind protoreflect.Kind) (string, string, bool) {
	if kind == protoreflect.Int32Kind || kind == protoreflect.Int64Kind {
		return "GetInt", "0", true
	}

	if kind == protoreflect.StringKind || kind == protoreflect.EnumKind {
		return "GetString", emptyLiteral, true
	}

	return "", "", false
}

// emitList writes a tool that fetches a page of a collection. Both list tiers
// share this body, differing only in the driver they call and whether a path id
// travels with the fetch.
func emitList(out *source, tool *contract) error {
	out.need(importContext, importMCP, importConfig, importGenpb,
		importLinode, importProfiles, importTools)

	subresource := tool.Tier == tierSubresourceList
	restoring := len(tool.ExplicitNulls) > 0

	ordered, err := tool.orderedPathFields()
	if err != nil {
		return err
	}

	factory := factoryName(tool.Name)

	out.writef("// %s builds %s, which %s", factory, tool.Name, describeRoute(tool))
	out.writef("func %s(cfg *config.Config) (mcp.Tool, profiles.Capability, tools.Handler) {", factory)

	driver := "tools.NewGeneratedListTool"

	if subresource {
		driver = "tools.NewGeneratedSubresourceListTool"
	}

	// The null-restoring driver reads its path the same way whether or not the
	// collection is nested, so one call shape covers both and a top-level page
	// hands it no readers.
	if restoring {
		driver = "tools.NewGeneratedNullListTool"
	}

	out.writef("\ttool, handler := %s(", driver)

	out.writef("\t\tcfg,")
	out.writef("\t\t%s,", goStringLiteral(tool.Name))
	out.writef("\t\t%s,", goStringLiteral(tool.Description))
	out.writef("\t\t%s,", goStringLiteral(tool.InputMessage))

	if err := emitListFailure(out, tool, ordered); err != nil {
		return err
	}

	emitListValidate(out, tool)

	if subresource || restoring {
		if err := emitListPath(out, tool, ordered); err != nil {
			return err
		}
	}

	if restoring {
		emitNullListFetch(out, tool)
		out.writef("\t\t[]string{%s},", nullNameList(tool.ExplicitNulls))
		emitListAssemble(out, tool)
		out.writef("\t)")
		out.writef("")
		out.writef("\treturn tool, profiles.%s, handler", capabilityConstant(tool.Capability))
		out.writef("}")
		out.writef("")

		return nil
	}

	emitListFetch(out, tool)
	emitListFilters(out, tool)
	emitListAssemble(out, tool)

	out.writef("\t)")
	out.writef("")
	out.writef("\treturn tool, profiles.%s, handler", capabilityConstant(tool.Capability))
	out.writef("}")
	out.writef("")

	return nil
}

// emitMarkerList writes a collection whose route pages by a cursor. It shares
// the list tier's opening (failure sentence, declared check, path readers) and
// diverges at the fetch, which carries the cursor back, and at the assembly,
// which reports it.
func emitMarkerList(out *source, tool *contract) error {
	out.need(importContext, importMCP, importConfig, importGenpb,
		importLinode, importProfiles, importTools)

	ordered, err := tool.orderedPathFields()
	if err != nil {
		return err
	}

	factory := factoryName(tool.Name)

	out.writef("// %s builds %s, which %s", factory, tool.Name, describeRoute(tool))
	out.writef("func %s(cfg *config.Config) (mcp.Tool, profiles.Capability, tools.Handler) {", factory)
	out.writef("\ttool, handler := tools.NewGeneratedMarkerListTool(")
	out.writef("\t\tcfg,")
	out.writef("\t\t%s,", goStringLiteral(tool.Name))
	out.writef("\t\t%s,", goStringLiteral(tool.Description))
	out.writef("\t\t%s,", goStringLiteral(tool.InputMessage))

	if err := emitListFailure(out, tool, ordered); err != nil {
		return err
	}

	emitListValidate(out, tool)

	if err := emitListPath(out, tool, ordered); err != nil {
		return err
	}

	emitMarkerFetch(out, tool)
	emitMarkerEchoes(out, tool)
	emitMarkerAssemble(out, tool)

	out.writef("\t)")
	out.writef("")
	out.writef("\treturn tool, profiles.%s, handler", capabilityConstant(tool.Capability))
	out.writef("}")
	out.writef("")

	return nil
}

// emitMarkerFetch writes the closure that fetches the cursor-paged body. No page
// controls travel: this route's bound is one of the forwarded arguments.
func emitMarkerFetch(out *source, tool *contract) {
	element := "*linodev1." + tool.ElementGo.TypeName

	out.writef("\t\tfunc(ctx context.Context, client *linode.Client, request *mcp.CallToolRequest, values []any) ([]%s, linode.ListMarkerPage, error) {",
		element)
	out.writef("\t\t\treturn linode.ListProtoRouteMarker(ctx, client, %s, values, %s,",
		goStringLiteral(tool.Name), forwardedQueryExpression(out, tool))
	out.writef("\t\t\t\tfunc() %s { return &linodev1.%s{} })", element, tool.ElementGo.TypeName)
	out.writef("\t\t},")
}

// emitMarkerEchoes writes the arguments the answer reports it was narrowed by.
func emitMarkerEchoes(out *source, tool *contract) {
	if len(tool.Echoed) == 0 {
		out.writef("\t\tnil,")

		return
	}

	out.writef("\t\t[]string{%s},", queryArgumentList(tool.Echoed))
}

// emitMarkerAssemble writes the closure that packs the page and its cursor into
// the response envelope. The marker travels only when the route handed one out,
// so a complete listing carries no resume point a caller could act on.
func emitMarkerAssemble(out *source, tool *contract) {
	element := "*linodev1." + tool.ElementGo.TypeName
	envelope := "linodev1." + tool.ResponseGo.TypeName

	echo := ", filter *string"
	assign := tool.FilterField + ": filter, "

	if tool.FilterField == "" {
		echo = ", _ *string"
		assign = ""
	}

	out.writef("\t\tfunc(items []%s, count int32%s, cursor linode.ListMarkerPage) *%s {",
		element, echo, envelope)
	out.writef("\t\t\treturn &%s{%s: count, %s%s: cursor.IsTruncated, %s: tools.TextOrAbsent(cursor.NextMarker), %s: items}",
		envelope, tool.CountField, assign, tool.TruncatedField, tool.NextMarkerField, tool.EnvelopeField)
	out.writef("\t\t},")
}

// emitListFailure writes the tool's own failure sentence, or nil when it
// declares none and the shared list sentence answers instead.
//
// A collection that declares error_message means to say something its family's
// callers recognize, and answering the shared sentence over that declaration
// was the prose drift this closes: the emitter used to pass nothing and the
// declaration went unread.
func emitListFailure(out *source, tool *contract, ordered []field) error {
	if tool.ErrorMessage == "" {
		out.writef("\t\tnil,")

		return nil
	}

	failure, err := tool.formatMessage(tool.ErrorMessage)
	if err != nil {
		return err
	}

	named := namedLocals(ordered, failure.args)

	out.need(importFmt, importMCP)

	// The ids the template names are read here rather than passed in: the
	// driver read them to fill the route, and handing them along would put the
	// same value in two places for a sentence that only reports it. A sentence
	// naming none takes the request as a blank, since the seam still passes it.
	parameter := "request"
	if len(named) == 0 {
		parameter = "_"
	}

	out.writef("\t\tfunc(%s *mcp.CallToolRequest, err error) string {", parameter)
	emitPathArgReads(out, named)
	out.writef("\t\t\treturn fmt.Sprintf(%s)", failure.call("err"))
	out.writef("\t\t},")

	return nil
}

// namedLocals keeps the path fields a rendered template actually reads, so a
// sentence naming none does not leave the closure with unused reads.
func namedLocals(ordered []field, args []string) []field {
	named := make([]field, 0, len(ordered))

	for _, entry := range ordered {
		if slices.Contains(args, entry.GoLocal) {
			named = append(named, entry)
		}
	}

	return named
}

// emitListValidate names the presence check a collection's query flags get, or
// nil when it declares none.
func emitListValidate(out *source, tool *contract) {
	flags := queryPresenceFields(tool)
	if len(flags) == 0 {
		out.writef("\t\tnil,")

		return
	}

	out.need(importTools)
	out.writef("\t\tfunc(request *mcp.CallToolRequest) string {")

	for index := range flags {
		out.writef("\t\t\tif message := %s; message != \"\" {", presenceCall(tool, "Bool", &flags[index]))
		out.writef("\t\t\t\treturn message")
		out.writef("\t\t\t}")
		out.writef("")
	}

	out.writef("\t\t\treturn \"\"")
	out.writef("\t\t},")
}

// queryPresenceFields are the query flags a tool asks the presence question of.
// A collection reads them here rather than beside its body because a list tool
// has no body to read: the flag travels in the query string, and whether the
// caller sent one is still a question only the argument map answers.
func queryPresenceFields(tool *contract) []field {
	flags := make([]field, 0, len(tool.Query))

	for _, entry := range tool.Query {
		if tool.Readers[entry.ProtoName] == linodev1.ArgumentReader_ARGUMENT_READER_PRESENT_BOOL {
			flags = append(flags, entry)
		}
	}

	return flags
}

// emitListPath writes the readers for a sub-resource list's path parameters, in
// route-template order. Every one is written, not just the first: a collection
// nested two deep (/linode/instances/{linode_id}/configs/{config_id}/interfaces)
// fills both slots, and a route left half-filled addresses something else.
func emitListPath(out *source, tool *contract, ordered []field) error {
	// A top-level collection reaches here only through the null-restoring
	// driver, which reads its path the same way whether the route has slots or
	// not. Nothing to read is nil rather than an empty literal.
	if len(ordered) == 0 {
		out.writef("\t\t%s,", nilLiteral)

		return nil
	}

	out.writef("\t\t[]tools.ListPathValue{")

	for _, entry := range ordered {
		// A declared reader owns the whole slot: it reads the id and answers the
		// sentence, which is the same pair the routed tiers get. Without this arm
		// the declaration would be dropped here and the derived check below would
		// answer in its place, which is the wording the tool just stopped saying.
		if declared, ok := tool.Readers[entry.ProtoName]; ok {
			if err := emitListReaderValue(out, tool, declared, &entry); err != nil {
				return err
			}

			continue
		}

		reader, zero, ok := pathArgReader(entry.Kind)
		if !ok {
			return fmt.Errorf("%w: %s is %s", errUnsupportedPathKind, entry.ProtoName, entry.Kind)
		}

		out.writef("\t\t\tfunc(request *mcp.CallToolRequest) (any, string) {")
		out.writef("\t\t\t\t%s := request.%s(%s, %s)", entry.GoLocal, reader,
			goStringLiteral(entry.ProtoName), zero)

		out.writef("\t\t\t\tif %s == %s {", entry.GoLocal, zero)
		out.writef("\t\t\t\t\treturn nil, %s", goStringLiteral(entry.ProtoName+" is required"))
		out.writef("\t\t\t\t}")

		out.writef("")
		out.writef("\t\t\t\treturn %s, \"\"", entry.GoLocal)
		out.writef("\t\t\t},")
	}

	out.writef("\t\t},")

	return nil
}

// emitListReaderValue writes one path slot of a sub-resource list whose id
// declares a shared reader. The list driver takes a value beside a sentence,
// which is the pair the reader already answers with, so the slot is the reader
// call and nothing else.
func emitListReaderValue(out *source, tool *contract, declared linodev1.ArgumentReader, entry *field) error {
	call, known := readerCall(tool, declared, entry)
	if !known {
		return fmt.Errorf("%w: %s declares %s", errUnsupportedReader, entry.ProtoName, declared)
	}

	out.need(importTools, importMCP)
	out.writef("\t\t\tfunc(request *mcp.CallToolRequest) (any, string) {")
	out.writef("\t\t\t\t%s, message := %s", entry.GoLocal, call)
	out.writef("\t\t\t\tif message != \"\" {")
	out.writef("\t\t\t\t\treturn nil, message")
	out.writef("\t\t\t\t}")
	out.writef("")
	out.writef("\t\t\t\treturn %s, \"\"", entry.GoLocal)
	out.writef("\t\t\t},")

	return nil
}

// emitListFetch writes the closure that fetches one page. A sub-resource list
// hands the path values it read straight to the routed call, which fills the
// template's slots from them in the same order.
func emitListFetch(out *source, tool *contract) {
	element := "*linodev1." + tool.ElementGo.TypeName

	if tool.Tier == tierSubresourceList {
		out.writef("\t\tfunc(ctx context.Context, client *linode.Client, request *mcp.CallToolRequest, values []any, page, pageSize int) ([]%s, error) {",
			element)
		out.writef("\t\t\treturn linode.ListProtoRoute(ctx, client, %s, values, %s, page, pageSize,",
			goStringLiteral(tool.Name), forwardedQueryExpression(out, tool))
	}

	if tool.Tier != tierSubresourceList {
		out.writef("\t\tfunc(ctx context.Context, client *linode.Client, request *mcp.CallToolRequest, page, pageSize int) ([]%s, error) {",
			element)
		out.writef("\t\t\treturn linode.ListProtoRoute(ctx, client, %s, nil, %s, page, pageSize,",
			goStringLiteral(tool.Name), forwardedQueryExpression(out, tool))
	}

	out.writef("\t\t\t\tfunc() %s { return &linodev1.%s{} })", element, tool.ElementGo.TypeName)
	out.writef("\t\t},")
}

// emitNullListFetch writes the fetch a null-restoring collection makes: the
// raw primitive, which hands each element's body back beside the message it
// decoded into. The path values travel whether or not the route has slots, so
// the closure reads the same for a nested collection and a top-level one.
func emitNullListFetch(out *source, tool *contract) {
	element := "*linodev1." + tool.ElementGo.TypeName

	out.writef("\t\tfunc(ctx context.Context, client *linode.Client, request *mcp.CallToolRequest, values []any, page, pageSize int) ([]%s, []json.RawMessage, error) {",
		element)
	out.writef("\t\t\treturn linode.ListProtoRouteRaw(ctx, client, %s, values, %s, page, pageSize,",
		goStringLiteral(tool.Name), forwardedQueryExpression(out, tool))
	out.writef("\t\t\t\tfunc() %s { return &linodev1.%s{} })", element, tool.ElementGo.TypeName)
	out.writef("\t\t},")

	out.need(importJSON)
}

// nullNameList renders the declared null keys as the string literals the driver
// reads them under.
func nullNameList(names []string) string {
	quoted := make([]string, 0, len(names))
	for _, name := range names {
		quoted = append(quoted, goStringLiteral(name))
	}

	return strings.Join(quoted, ", ")
}

// forwardedQueryExpression renders the query the route itself filters on. A
// collection whose arguments the element can all answer sends none, which is
// nearly all of them.
func forwardedQueryExpression(out *source, tool *contract) string {
	if len(tool.Forwarded) == 0 {
		return emptyLiteral
	}

	out.need(importTools)

	return fmt.Sprintf(`tools.WithQueryArguments(request, "", %s)`, queryArgumentList(tool.Forwarded))
}

// emitListFilters writes the client-side filters derived from the query arguments.
func emitListFilters(out *source, tool *contract) {
	element := "*linodev1." + tool.ElementGo.TypeName

	if len(tool.Filters) == 0 {
		out.writef("\t\tnil,")

		return
	}

	out.writef("\t\t[]tools.ListFilter[%s]{", element)

	for _, filter := range tool.Filters {
		constructor, result := filterConstructor(filter)

		out.writef("\t\t\t%s(%s, %s,", constructor,
			goStringLiteral(filter.Param), goStringLiteral(filter.Description))
		out.writef("\t\t\t\tfunc(item %s) %s { return item.%s() }),", element, result, filter.Getter)
	}

	out.writef("\t\t},")
}

// filterConstructor names the seam call one filter is built through and the type
// its accessor answers with. A flag is compared against the "true" or "false"
// the caller sends, since every filter argument arrives as text.
func filterConstructor(filter listFilter) (string, string) {
	if filter.Kind == protoreflect.BoolKind {
		return "tools.NewBoolFilter", typeWordBool
	}

	switch filter.Match {
	case linodev1.ListFilterSpec_MATCH_CONTAINS:
		return "tools.NewContainsFilter", textType
	case linodev1.ListFilterSpec_MATCH_MEMBER:
		return "tools.NewMemberFilter", "[]string"
	case linodev1.ListFilterSpec_MATCH_UNSPECIFIED:
	}

	return "tools.NewFieldFilter", textType
}

// emitListAssemble writes the closure that packs the filtered page into the
// response envelope the contract names.
func emitListAssemble(out *source, tool *contract) {
	element := "*linodev1." + tool.ElementGo.TypeName
	envelope := "linodev1." + tool.ResponseGo.TypeName

	// An envelope with no filter member takes the echo nowhere. The parameter
	// is still declared because the driver passes one, and discarding it here
	// is what says the tool advertises no filter rather than dropping one.
	echo := ", filter *string"
	assign := tool.FilterField + ": filter, "

	if tool.FilterField == "" {
		echo = ", _ *string"
		assign = ""
	}

	out.writef("\t\tfunc(items []%s, count int32%s) *%s {", element, echo, envelope)
	out.writef("\t\t\treturn &%s{%s: count, %s%s: items}",
		envelope, tool.CountField, assign, tool.EnvelopeField)
	out.writef("\t\t},")
}

// pathValuesLiteral renders the path values a routed call fills its template
// with, in the order the template declares its slots.
func pathValuesLiteral(ordered []field) string {
	if len(ordered) == 0 {
		return nilLiteral
	}

	names := make([]string, 0, len(ordered))
	for _, entry := range ordered {
		names = append(names, entry.GoLocal)
	}

	return "[]any{" + strings.Join(names, ", ") + "}"
}

// describeRoute is the sentence each emitted doc comment ends with, so the
// generated file names the route without a proto lookup. A meta tool has none
// to name, which is the fact worth stating there instead.
func describeRoute(tool *contract) string {
	if tool.Meta {
		return "answers from local state and reaches no Linode route."
	}

	return fmt.Sprintf("calls %s %s.", tool.Method, routePath(tool))
}

// routePath is the path a doc comment names. A tool on a non-default surface
// names the segment its call actually addresses, so the generated file states
// the base the client will pick rather than implying the default one.
func routePath(tool *contract) string {
	if tool.Surface == linoderoute.DefaultSurfaceSegment {
		return tool.PathTemplate
	}

	return "/" + tool.Surface + tool.PathTemplate
}

// factoryName is the exported factory a tool registers through:
// linode_domain_get becomes NewLinodeDomainGetTool.
func factoryName(tool string) string {
	return "New" + exportedToolName(tool) + "Tool"
}

// handlerName is the function a factory's closure delegates to. The "handle"
// prefix is load-bearing: cmd/write-proto-dump recognizes a handler by it when
// it classifies the read, write, and input surfaces.
func handlerName(tool string) string {
	return "handle" + exportedToolName(tool)
}

// exportedToolName renders a tool name in Go's exported spelling, through the
// same table the generated tree's factory and handler names come from.
func exportedToolName(tool string) string {
	return goname.Exported(tool)
}

// capabilityConstant maps a declared capability to the profiles constant the
// server registers a tool under.
func capabilityConstant(capability linodev1.ToolCapability) string {
	switch capability {
	case linodev1.ToolCapability_TOOL_CAPABILITY_READ:
		return "CapRead"
	case linodev1.ToolCapability_TOOL_CAPABILITY_WRITE:
		return "CapWrite"
	case linodev1.ToolCapability_TOOL_CAPABILITY_DESTROY:
		return "CapDestroy"
	case linodev1.ToolCapability_TOOL_CAPABILITY_ADMIN:
		return "CapAdmin"
	case linodev1.ToolCapability_TOOL_CAPABILITY_META,
		linodev1.ToolCapability_TOOL_CAPABILITY_UNSPECIFIED:
	}

	return "CapMeta"
}
