package main_test

import (
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"testing"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/reflect/protoregistry"

	linodev1 "github.com/chadit/LinodeMCP/go/internal/genpb/linode/mcp/v1"
	"github.com/chadit/LinodeMCP/go/internal/linoderoute"
)

// Emitter inputs, relative to this package directory because go test runs
// with that directory as cwd.
const (
	handwrittenFile = "../../../docs/contracts/handwritten-tools.txt"
	manifestFile    = "../../../docs/contracts/tools-manifest.txt"
	schemaDir       = "../../internal/toolschemas/data"
)

const generatedHeader = "// Code generated by go/cmd/toolgen"

// The two gate calls a tier that changes nothing must never emit.
const (
	dryRunGate  = "tools.IsDryRun("
	confirmGate = "tools.RequireConfirm("
)

// The line a mutation answers through when the decode already placed every
// member, which is the whole answer for the bare and the decoded shapes alike.
const marshalPayload = "return tools.MarshalProtoToolResponse(payload)"

// runGen emits into a temp tree using the same invocation `make proto` uses,
// since what the build depends on is the files written, not how they are chosen.
func runGen(t *testing.T) string {
	t.Helper()

	out := t.TempDir()

	cmd := exec.CommandContext(t.Context(), "go", "run", ".",
		"-languages", writeLanguages(t, "go"),
		"-handwritten", handwrittenFile,
		"-out", out, "-answers-out", t.TempDir(), "-schemas", schemaDir)

	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("toolgen failed: %v\n%s", err, output)
	}

	return out
}

// runGenFrom emits the cohort a custom hand-written list leaves, for the tools
// the real list still claims.
func runGenFrom(t *testing.T, handwritten string) string {
	t.Helper()

	out := t.TempDir()

	cmd := exec.CommandContext(t.Context(), "go", "run", ".",
		"-languages", writeLanguages(t, "go"),
		"-handwritten", handwritten,
		"-out", out, "-answers-out", t.TempDir(), "-schemas", schemaDir)

	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("toolgen failed: %v\n%s", err, output)
	}

	return out
}

func readGenerated(t *testing.T, dir, name string) string {
	t.Helper()

	raw, err := os.ReadFile(filepath.Join(dir, name))
	if err != nil {
		t.Fatalf("read %s: %v", name, err)
	}

	return string(raw)
}

// readNames reads one of the repo's one-name-per-line contracts.
func readNames(t *testing.T, path string) []string {
	t.Helper()

	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}

	names := make([]string, 0)

	for line := range strings.SplitSeq(string(raw), "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}

		names = append(names, trimmed)
	}

	return names
}

// writeLanguages writes a languages registry naming the given languages, in
// the three-field shape docs/contracts/languages.txt carries.
//
// One run emits every registered language, so a case that reads only the Go
// tree registers only Go: pointing at the real registry would render the Python
// tree through the formatter on every one of them.
func writeLanguages(t *testing.T, names ...string) string {
	t.Helper()

	lines := make([]string, 0, len(names)+1)
	lines = append(lines, "# Registry for one test run.")

	for _, name := range names {
		lines = append(lines, name+"\t"+name+"\tdump")
	}

	path := filepath.Join(t.TempDir(), "languages.txt")
	if err := os.WriteFile(path, []byte(strings.Join(lines, "\n")+"\n"), 0o600); err != nil {
		t.Fatalf("write languages registry: %v", err)
	}

	return path
}

// writeHandwritten writes a hand-written list built from the real one.
//
// Every failure case here is a change to that list rather than a list of its
// own, because the list is now the whole surface minus the cohort: a short
// invented list would put 400-odd unrelated tools into the cohort and fail on
// whichever one the emitter reached first.
func writeHandwritten(t *testing.T, names []string) string {
	t.Helper()

	path := filepath.Join(t.TempDir(), "handwritten.txt")
	if err := os.WriteFile(path, []byte(strings.Join(names, "\n")+"\n"), 0o600); err != nil {
		t.Fatalf("write hand-written list: %v", err)
	}

	return path
}

// alsoGenerated drops one name from the hand-written list whether or not the
// list still claims it, so a case whose subject is the emitted shape keeps
// proving the same thing the day its tool moves. Its counterpart, which
// promoted a still-hand-written tool to prove a refusal, is gone: no name is
// left on the list to promote, and each case that used one now reads its rule
// off the emitted tree.
func alsoGenerated(t *testing.T, tool string) []string {
	t.Helper()

	return slices.DeleteFunc(readNames(t, handwrittenFile),
		func(name string) bool { return name == tool })
}

func runGenExpectingFailure(t *testing.T, handwritten string) string {
	t.Helper()

	cmd := exec.CommandContext(t.Context(), "go", "run", ".",
		"-languages", writeLanguages(t, "go"),
		"-handwritten", handwritten,
		"-out", t.TempDir(), "-answers-out", t.TempDir(), "-schemas", schemaDir)

	output, err := cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("toolgen succeeded, want a failure:\n%s", output)
	}

	return string(output)
}

// A language the registry names and no arm renders fails by name, before any
// tree is written: emitting the arms it recognized and reporting success is how
// a registered language quietly ships nothing.
func TestRefusesARegisteredLanguageWithNoRendererArm(t *testing.T) {
	t.Parallel()

	out := t.TempDir()

	cmd := exec.CommandContext(t.Context(), "go", "run", ".",
		"-languages", writeLanguages(t, "go", "rust"),
		"-handwritten", handwrittenFile,
		"-out", out, "-answers-out", t.TempDir(), "-schemas", schemaDir)

	output, err := cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("toolgen succeeded, want a failure:\n%s", output)
	}

	if !strings.Contains(string(output), "rust") {
		t.Errorf("the failure does not name the unserved language:\n%s", output)
	}

	written, err := os.ReadDir(out)
	if err != nil {
		t.Fatalf("read output directory: %v", err)
	}

	if len(written) > 0 {
		t.Errorf("the run wrote %d file(s) before refusing the registry", len(written))
	}
}

// A registry the emitter reads as empty stops the run. Emitting no tree while
// reporting success is how a build keeps shipping yesterday's one.
func TestRefusesALanguagesRegistryThatNamesNothing(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "languages.txt")
	if err := os.WriteFile(path, []byte("# a note\n\n"), 0o600); err != nil {
		t.Fatalf("write languages registry: %v", err)
	}

	cmd := exec.CommandContext(t.Context(), "go", "run", ".",
		"-languages", path,
		"-handwritten", handwrittenFile,
		"-out", t.TempDir(), "-answers-out", t.TempDir(), "-schemas", schemaDir)

	output, err := cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("toolgen succeeded, want a failure:\n%s", output)
	}

	if !strings.Contains(string(output), "names no language") {
		t.Errorf("the failure does not say the registry named nothing:\n%s", output)
	}
}

// A comment or a blank line in a contract list is not a tool name, so the
// cohort a decorated list leaves is the cohort the plain one leaves.
func TestReadsAContractListPastCommentsAndBlanks(t *testing.T) {
	t.Parallel()

	names := readNames(t, handwrittenFile)
	decorated := append([]string{"# a note", ""}, names...)

	plain := readGenerated(t, runGenFrom(t, writeHandwritten(t, names)), "registry.gen.go")
	noted := readGenerated(t, runGenFrom(t, writeHandwritten(t, decorated)), "registry.gen.go")

	if plain != noted {
		t.Error("a comment and a blank line moved the emitted cohort")
	}
}

// The emitted text is what ships, so this reads it directly and pins every
// part a single-resource contract produces.
func TestEmitsTheReadFactoryTheContractDescribes(t *testing.T) {
	t.Parallel()

	source := readGenerated(t, runGen(t), "domain.gen.go")

	for _, want := range []string{
		`func NewLinodeDomainGetTool(cfg *config.Config) (mcp.Tool, profiles.Capability, tools.Handler)`,
		`"linode_domain_get",`,
		`"Gets detailed information about a specific domain by its ID.",`,
		`toolschemas.Schema("linode.mcp.v1.DomainGetInput")`,
		`return tool, profiles.CapRead, handler`,
		`client.CallProtoRouteQuery(ctx, "linode_domain_get", []any{domainID}, query, response)`,
		`"Failed to retrieve domain %d: %v", domainID, err`,
		`return tools.MarshalProtoToolResponse(response)`,
	} {
		if !strings.Contains(source, want) {
			t.Errorf("emitted source is missing %q", want)
		}
	}
}

// The route names record_id last, so path values have to reach the call in
// that order no matter how the message declares them.
func TestEmitsPathValuesInRouteOrder(t *testing.T) {
	t.Parallel()

	source := readGenerated(t, runGen(t), "domain.gen.go")

	want := `client.CallProtoRouteQuery(ctx, "linode_domain_record_get", []any{domainID, recordID}, query, response)`
	if !strings.Contains(source, want) {
		t.Errorf("emitted source is missing %q", want)
	}
}

// Pins the derivation that replaces a hand-written assemble function per
// family: the repeated field of the response message is the collection, and
// its name is the field the envelope fills.
func TestEmitsTheListEnvelopeTheResponseDescribes(t *testing.T) {
	t.Parallel()

	source := readGenerated(t, runGen(t), "domain.gen.go")

	for _, want := range []string{
		`return &linodev1.DomainListResponse{Count: count, Filter: filter, Domains: items}`,
		`return &linodev1.DomainRecordListResponse{Count: count, Filter: filter, Records: items}`,
	} {
		if !strings.Contains(source, want) {
			t.Errorf("emitted source is missing %q", want)
		}
	}
}

// The other list derivation: a query argument names the element field it
// filters, and a "_contains" suffix asks for substring matching over the field
// its name prefixes.
func TestEmitsFiltersDerivedFromQueryArguments(t *testing.T) {
	t.Parallel()

	source := readGenerated(t, runGen(t), "domain.gen.go")

	for _, want := range []string{
		`tools.NewContainsFilter("domain_contains"`,
		`func(item *linodev1.Domain) string { return item.GetDomain() })`,
		`tools.NewFieldFilter("type"`,
		`func(item *linodev1.Domain) string { return item.GetType() })`,
	} {
		if !strings.Contains(source, want) {
			t.Errorf("emitted source is missing %q", want)
		}
	}
}

// The generated tree reaches no hand-written body at all: every argument check
// the surface makes is a rule, a declared reader, or an object walk, which is
// what docs/contracts/hand-validator-counts.txt records as zero. The population
// this counts is the emitted files rather than the calls, because the calls are
// meant to be none and a guard on an empty set would fail on the state the
// migration was for.
func TestTheGoTreeReachesNoHandWrittenBody(t *testing.T) {
	t.Parallel()

	dir := runGen(t)

	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read emitted tree: %v", err)
	}

	for _, entry := range entries {
		source := readGenerated(t, dir, entry.Name())
		for line := range strings.SplitSeq(source, "\n") {
			if strings.Contains(line, "toolhooks.") {
				t.Errorf("%s reaches a hand-written body: %s", entry.Name(), strings.TrimSpace(line))
			}
		}
	}

	if len(entries) == 0 {
		t.Fatal("found no emitted files, so this measured nothing")
	}
}

// The emitted files are gitignored and rewritten whole, so the header is all a
// reader who finds one has to tell them not to edit it.
func TestEveryEmittedFileCarriesTheGeneratedHeader(t *testing.T) {
	t.Parallel()

	dir := runGen(t)

	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read emitted tree: %v", err)
	}

	if len(entries) == 0 {
		t.Fatal("emitted tree is empty")
	}

	for _, entry := range entries {
		source := readGenerated(t, dir, entry.Name())
		if !strings.HasPrefix(source, generatedHeader) {
			t.Errorf("%s does not open with the generated-by header", entry.Name())
		}
	}
}

// A factory nothing registers passes every gate that reads the contract and is
// still missing from the running server.
func TestRegistryListsEveryGeneratedFactory(t *testing.T) {
	t.Parallel()

	registry := readGenerated(t, runGen(t), "registry.gen.go")

	for _, want := range []string{
		"NewLinodeDomainGetTool,",
		"NewLinodeDomainListTool,",
		"NewLinodeDomainRecordGetTool,",
		"NewLinodeDomainRecordListTool,",
	} {
		if !strings.Contains(registry, want) {
			t.Errorf("registry is missing %q", want)
		}
	}
}

// Typo guard on the hand-written list. An entry naming nothing exempts nothing
// from the generator while reading as though it exempts something, which is
// exactly what a misspelled or renamed tool leaves behind.
func TestRefusesAHandwrittenEntryTheContractDoesNotDeclare(t *testing.T) {
	t.Parallel()

	names := append(readNames(t, handwrittenFile), "linode_domain_get_typo")

	output := runGenExpectingFailure(t, writeHandwritten(t, names))

	if !strings.Contains(output, "does not declare") {
		t.Errorf("failure does not name the cause:\n%s", output)
	}
}

// A free-form read answers with the object it decoded, since there is no
// message to place it in. linode_profile_preferences_get is one of the three
// such routes, alongside the two database engine configs.
func TestEmitsTheFreeFormReadAsTheObjectItDecoded(t *testing.T) {
	t.Parallel()

	dir := runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile)))
	source := readGenerated(t, dir, "profile.gen.go")

	if !strings.Contains(source, `raw, err := client.CallRouteObject(ctx, "linode_profile_preferences_get", nil, query)`) {
		t.Errorf("free-form read does not decode the body as an object:\n%s", source)
	}

	if !strings.Contains(source, `tools.MarshalStructToolResponse(raw, "Failed to retrieve profile preferences")`) {
		t.Errorf("free-form read does not answer with the decoded object:\n%s", source)
	}
}

// Both ways a free-form read can fail report one sentence: the serializer words
// a conversion failure by appending the error to the prefix it is handed, so
// the prefix is the declared error_message with its own error trimmed off.
func TestFreeFormReadWordsBothFailuresTheSameWay(t *testing.T) {
	t.Parallel()

	dir := runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile)))
	source := readGenerated(t, dir, "profile.gen.go")

	if !strings.Contains(source, `fmt.Sprintf("Failed to retrieve profile preferences: %v", err)`) {
		t.Errorf("free-form read does not report the declared failure:\n%s", source)
	}
}

// readRouteCall is the call a read makes and no other tier does: a mutation
// sends its body through CallProtoRouteBody, and a list runs through its own
// driver. Pairing it with the dry-run branch is what names the gated-read tier,
// where the preview comment alone would have swept in the acknowledge tier,
// which words its preview the same way.
const readRouteCall = "client.CallProtoRouteQuery("

// A read advertising a preview has to hold its fetch back behind something
// while the preview branch answers, or the dry run answers by making the call
// it previews. The confirm argument is that gate, and the emitter refuses a
// read declaring one without the other.
//
// This reads the rule off the tree rather than off a specimen: every read
// declaring dry_run now declares confirm too, so there is no tool left to drop
// from the hand-written list and be refused. The same shape the meta-answer and
// destroy state-fetch cases took when their last specimens migrated.
func TestEveryEmittedReadPreviewIsGated(t *testing.T) {
	t.Parallel()

	dir := runGen(t)

	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read emitted tree: %v", err)
	}

	var gated int

	for _, entry := range entries {
		source := readGenerated(t, dir, entry.Name())

		for _, read := range readHandlers(source) {
			if !strings.Contains(read.body, dryRunGate) {
				continue
			}

			gated++

			confirm := strings.Index(read.body, confirmGate)
			client := strings.Index(read.body, "tools.ClientForRequest(")

			if confirm < 0 || confirm > client {
				t.Errorf("%s reaches its client without asking the gate first:\n%s", read.name, read.body)
			}
		}
	}

	// The two database credentials reads and linode_managed_credential_get, so
	// a scan that stopped finding reads cannot pass by measuring nothing.
	const gatedReads = 3

	if gated != gatedReads {
		t.Errorf("found %d gated read(s), want %d", gated, gatedReads)
	}
}

// emittedHandler is one generated handler: the name it is declared under and
// the body under it.
type emittedHandler struct {
	name string
	body string
}

// readHandlers returns every emitted read handler the source declares.
func readHandlers(source string) []emittedHandler {
	var found []emittedHandler

	for _, block := range strings.Split(source, "\nfunc handle")[1:] {
		name, _, cut := strings.Cut(block, "(")
		if !cut {
			continue
		}

		body, _, _ := strings.Cut(block, "\n}\n")
		if strings.Contains(body, readRouteCall) {
			found = append(found, emittedHandler{name: "handle" + name, body: body})
		}
	}

	return found
}

// A routeless tool lands on the meta tier and nowhere else. Every other tier
// builds a request, and a contract with no route to build one against answers
// each of the mutation tests the way the acknowledge tier does, so without the
// branch this pins, hello would be emitted as a mutation that calls nothing.
//
// The declared-sentence shape is what hello proves: the sentence its contract
// declares,
// over the argument the template names, with the default that template carries.
func TestEmitsTheMetaShellForARoutelessTool(t *testing.T) {
	t.Parallel()

	source := readGenerated(t, runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile))), "version.gen.go")
	handler := handlerBody(t, source, "handleHello")

	for _, want := range []string{
		"case <-ctx.Done():",
		`toolvalidate.Check("linode.mcp.v1.HelloInput"`,
		`tools.MarshalProtoToolResponse(&linodev1.HelloResponse{`,
		`fmt.Sprintf("Hello, %s! LinodeMCP server is running and ready.", request.GetString("name", "World"))`,
	} {
		if !strings.Contains(handler, want) {
			t.Errorf("meta handler does not carry %q:\n%s", want, handler)
		}
	}

	// The acknowledge tier's marks. A meta tool reaching one of them would be
	// gating and previewing a call it never makes.
	for _, unwanted := range []string{dryRunGate, confirmGate, "tools.ClientForRequest("} {
		if strings.Contains(handler, unwanted) {
			t.Errorf("meta handler fell through to %q:\n%s", unwanted, handler)
		}
	}
}

// A meta tool answers through a declared local operation or through the
// sentence its contract declares. With neither, the emitted handler has nothing
// to return, so the emitter refuses it.
//
// This reads that refusal off the tree rather than off a specimen: every meta
// tool the contract declares now names one or the other, so there is no tool
// left to drop from the hand-written list and be refused. The same shape the
// destroy state-fetch case took when its last specimen migrated.
func TestEveryEmittedMetaToolNamesItsAnswer(t *testing.T) {
	t.Parallel()

	dir := runGen(t)

	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read emitted tree: %v", err)
	}

	var handlers int

	for _, entry := range entries {
		source := readGenerated(t, dir, entry.Name())

		for _, handler := range metaHandlers(t, source) {
			handlers++

			if strings.Contains(handler, "tools.") {
				continue
			}

			if strings.Contains(handler, "fmt.Sprintf(") {
				continue
			}

			t.Errorf("%s emits a meta handler that answers with neither an operation nor a sentence:\n%s",
				entry.Name(), handler)
		}
	}

	// Every meta tool the contract declares, so a scan that stopped finding
	// them cannot pass by measuring nothing.
	const metaTools = 17

	if handlers != metaTools {
		t.Errorf("found %d meta handler(s), want %d", handlers, metaTools)
	}
}

// metaMarker is the sentence the emitter writes above a factory that reaches no
// Linode route, and nothing else carries it. Keying on it is what makes this
// read exactly the meta tier: matching handler bodies by their shape instead
// swept in the destroys, which reach their route through a helper rather than
// through the client call this would have filtered on.
const metaMarker = "answers from local state and reaches no Linode route"

// metaHandlers returns the body of every emitted meta handler, found through
// the factory that names it.
func metaHandlers(t *testing.T, source string) []string {
	t.Helper()

	var bodies []string

	for line := range strings.SplitSeq(source, "\n") {
		if !strings.Contains(line, metaMarker) {
			continue
		}

		factory, _, found := strings.Cut(strings.TrimPrefix(line, "// "), " builds ")
		if !found {
			t.Fatalf("meta marker on an unreadable comment: %s", line)
		}

		handler := "func handle" + strings.TrimSuffix(strings.TrimPrefix(factory, "New"), "Tool") + "("

		_, after, split := strings.Cut(source, handler)
		if !split {
			t.Fatalf("no handler named %s for the factory %s", handler, factory)
		}

		body, _, closed := strings.Cut(after, "\n}\n")
		if !closed {
			t.Fatalf("handler %s never closes", handler)
		}

		bodies = append(bodies, body)
	}

	return bodies
}

// Zero-measurement guard: a list claiming the whole surface leaves nothing to
// generate, and every check the emitter and the ratchet make is scoped to what
// is generated, so all of them would pass over nothing.
func TestRefusesAHandwrittenListThatClaimsEveryTool(t *testing.T) {
	t.Parallel()

	output := runGenExpectingFailure(t, writeHandwritten(t, readNames(t, manifestFile)))

	if !strings.Contains(output, "nothing to generate") {
		t.Errorf("failure does not name the cause:\n%s", output)
	}
}

// A mutation whose route answers with a page of a collection is decoded through
// the list envelope, not into the declared response. The API sends the
// replacement's result as {data, page, pages, results}, which carries none of
// FirewallListResponse's members, so decoding into it directly reports zero
// firewalls assigned over a replacement that already happened.
//
// linode_instance_firewall_update is the specimen and its NodeBalancer twin is
// the only other tool of the shape.
func TestEmitsAPagedMutationThroughTheListEnvelope(t *testing.T) {
	t.Parallel()

	dir := runGenFrom(t, writeHandwritten(t, alsoGenerated(t, "linode_instance_firewall_update")))
	handler := handlerBody(t, readGenerated(t, dir, "firewall.gen.go"), "handleLinodeInstanceFirewallUpdate")

	for _, want := range []string{
		`items, err := linode.ListProtoRouteBody(ctx, client, "linode_instance_firewall_update", []any{linodeID}, query, body,`,
		`func() *linodev1.Firewall { return &linodev1.Firewall{} })`,
		`return tools.MarshalProtoToolResponse(&linodev1.FirewallListResponse{Count: tools.ClampListCount(items), Firewalls: items})`,
	} {
		if !strings.Contains(handler, want) {
			t.Errorf("paged mutation does not carry %q:\n%s", want, handler)
		}
	}

	// The single-resource decode is what answered zero before this tier existed.
	if strings.Contains(handler, "CallProtoRouteBody(") {
		t.Errorf("paged mutation decodes its page as one resource:\n%s", handler)
	}
}

// A mutation forwards the query arguments it publishes, and its preview reports
// the route it would have called rather than the bare path: the page controls
// decide which assignments come back, so a preview omitting them describes a
// different request from the one the live branch makes.
func TestEmitsTheQueryAMutationPublishes(t *testing.T) {
	t.Parallel()

	source := readGenerated(t,
		runGenFrom(t, writeHandwritten(t, alsoGenerated(t, "linode_instance_firewall_update"))),
		"firewall.gen.go")

	handler := handlerBody(t, source, "handleLinodeInstanceFirewallUpdate")
	if !strings.Contains(handler, "query, message := tools.StandardPageQuery(request)") {
		t.Errorf("mutation does not build the query it publishes:\n%s", handler)
	}

	preview := handlerBody(t, source, "previewLinodeInstanceFirewallUpdate")

	want := `tools.PathWithQuery(fmt.Sprintf("/linode/instances/%d/firewalls", linodeID), query)`
	if !strings.Contains(preview, want) {
		t.Errorf("preview does not report the query the call carries:\n%s", preview)
	}
}

// handlerBody scopes a check to one emitted function, so it cannot be
// satisfied by text belonging to another handler.
func handlerBody(t *testing.T, source, name string) string {
	t.Helper()

	start := strings.Index(source, "func "+name+"(")
	if start < 0 {
		t.Fatalf("emitted source declares no %s", name)
	}

	rest := source[start:]

	before, _, closed := strings.Cut(rest, "\n}\n")
	if !closed {
		return rest
	}

	return before
}

// The two branches of a mutation gate in opposite orders, and both orders
// matter. A dry run has nothing to confirm, so it validates first. A live call
// gates first, so a caller who has not confirmed learns nothing about whether
// their arguments would have been accepted.
func TestEmitsTheWriteOrderingContract(t *testing.T) {
	t.Parallel()

	source := readGenerated(t, runGen(t), "domain.gen.go")

	live := handlerBody(t, source, "handleLinodeDomainCreate")

	confirm := strings.Index(live, "tools.RequireConfirm(")
	validate := strings.Index(live, domainTypeCheck)

	if confirm < 0 || validate < 0 {
		t.Fatalf("live branch is missing a gate or a check:\n%s", live)
	}

	if confirm > validate {
		t.Errorf("live branch validates before it gates on confirm:\n%s", live)
	}

	preview := handlerBody(t, source, "previewLinodeDomainCreate")
	if strings.Contains(preview, "tools.RequireConfirm(") {
		t.Errorf("dry-run branch gates on confirm:\n%s", preview)
	}

	if !strings.Contains(preview, domainTypeCheck) {
		t.Errorf("dry-run branch skips the argument check:\n%s", preview)
	}
}

// domainTypeCheck is the membership check DomainCreateInput's type field
// declares, spelled the way the emitter writes it: the vocabulary comes from
// the enum descriptor, sentinel excluded, in number order.
const domainTypeCheck = `tools.MemberChoiceArgument(request, "type", true, "master", "slave")`

// A field declaring ARGUMENT_READER_ENUM_MEMBER is checked through the shared
// membership reader at every seam that reads arguments: a required body member,
// an optional one, a routed path slot, and a list path slot. The vocabulary is
// emitted from the declaration, so the enum and the reader_values spellings are
// both pinned here.
func TestEmitsTheMembershipReaderAtEverySeam(t *testing.T) {
	t.Parallel()

	dir := runGen(t)

	domain := readGenerated(t, dir, "domain.gen.go")
	if !strings.Contains(handlerBody(t, domain, "handleLinodeDomainCreate"), domainTypeCheck) {
		t.Errorf("required body enum is not checked through the membership reader")
	}

	optional := `tools.MemberChoiceArgument(request, "type", false, "master", "slave")`
	if !strings.Contains(handlerBody(t, domain, "handleLinodeDomainUpdate"), optional) {
		t.Errorf("optional body enum is not checked through the membership reader")
	}

	tag := `tools.MemberChoiceArgument(request, "tag", false, "issue", "issuewild", "iodef")`
	if !strings.Contains(handlerBody(t, domain, "handleLinodeDomainRecordUpdate"), tag) {
		t.Errorf("optional CAA tag is not checked through the membership reader")
	}

	firewall := readGenerated(t, dir, "firewall.gen.go")
	slug := `slug, message := tools.MemberChoiceArgument(request, "slug", true, "public", "vpc")`

	if !strings.Contains(handlerBody(t, firewall, "handleLinodeFirewallTemplateGet"), slug) {
		t.Errorf("routed path enum is not read through the membership reader")
	}

	tiers := readGenerated(t, dir, "lke_tier_version.gen.go")
	tier := `tier, message := tools.MemberChoiceArgument(request, "tier", true, "standard", "enterprise")`

	if !strings.Contains(tiers, tier) {
		t.Errorf("list path enum is not read through the membership reader")
	}

	placement := readGenerated(t, dir, "placement.gen.go")
	values := `tools.MemberChoiceArgument(request, "placement_group_type", true, "anti_affinity:local")`

	if !strings.Contains(handlerBody(t, placement, "handleLinodePlacementGroupCreate"), values) {
		t.Errorf("declared reader_values are not checked through the membership reader")
	}

	policy := `tools.MemberChoiceArgument(request, "placement_group_policy", true, "flexible", "strict")`
	if !strings.Contains(handlerBody(t, placement, "handleLinodePlacementGroupCreate"), policy) {
		t.Errorf("policy enum is not checked through the membership reader")
	}
}

// TestEmitsThePresenceReadersAtEverySeam holds the presence family to the same
// bar as the membership reader: each retired hand-written sentence now comes
// from a declared reader, and an any-of sentence rides the message as data.
func TestEmitsThePresenceReadersAtEverySeam(t *testing.T) {
	t.Parallel()

	dir := runGen(t)

	account := readGenerated(t, dir, "account.gen.go")
	update := handlerBody(t, account, "handleLinodeAccountOauthClientUpdate")

	for _, want := range []string{
		`tools.PresentTextArgument(request, "label", false)`,
		`tools.PresentBoolArgument(request, "public", false)`,
		`tools.RequireAnyArgument(request, "at least one of label, redirect_uri, or public is required", "label", "redirect_uri", "public")`,
	} {
		if !strings.Contains(update, want) {
			t.Errorf("OAuth client update does not read %s", want)
		}
	}

	create := `tools.PresentTextArgument(request, "label", true)`
	if !strings.Contains(handlerBody(t, account, "handleLinodeAccountOauthClientCreate"), create) {
		t.Errorf("required OAuth client label is not read through the presence reader")
	}

	accountUpdate := handlerBody(t, account, "handleLinodeAccountUpdate")
	if !strings.Contains(accountUpdate, "at least one account field is required") {
		t.Errorf("account update does not carry its own any-of sentence")
	}

	ip := readGenerated(t, dir, "ip.gen.go")
	share := `tools.RequiredPresentArgument(request, "ips")`

	if !strings.Contains(handlerBody(t, ip, "handleLinodeNetworkingIPShare"), share) {
		t.Errorf("the shared IP list is not read through the acknowledge reader")
	}
}

// Both branches build the body through one function, so a preview cannot
// advertise a body the live call would reject, or the other way round.
func TestBothWriteBranchesShareOneBodyBuilder(t *testing.T) {
	t.Parallel()

	source := readGenerated(t, runGen(t), "domain.gen.go")

	for _, name := range []string{"handleLinodeDomainCreate", "previewLinodeDomainCreate"} {
		if !strings.Contains(handlerBody(t, source, name), "linodeDomainCreateBody(request)") {
			t.Errorf("%s does not build its body through the shared builder", name)
		}
	}
}

// The body is written in proto field-declaration order, which is the order it
// reaches the wire. Python assembles the same body the same way, so the two
// languages send identical bytes for one call.
func TestEmitsTheBodyInProtoFieldOrder(t *testing.T) {
	t.Parallel()

	source := readGenerated(t, runGen(t), "domain.gen.go")
	body := handlerBody(t, source, "linodeDomainCreateBody")

	want := []string{
		`body.PutString("domain")`,
		`body.PutString("type")`,
		`body.SetString("soa_email")`,
		`body.SetString("description")`,
		`body.SetInt("ttl_sec")`,
		`body.SetStringList("axfr_ips")`,
		`body.SetInt("expire_sec")`,
		`body.SetString("group")`,
		`body.SetStringList("master_ips")`,
		`body.SetInt("refresh_sec")`,
		`body.SetInt("retry_sec")`,
		`body.SetString("status")`,
		`body.SetTags("tags")`,
	}

	previous := -1

	for _, line := range want {
		found := strings.Index(body, line)
		if found < 0 {
			t.Fatalf("body builder is missing %s:\n%s", line, body)
		}

		if found < previous {
			t.Errorf("%s is emitted out of proto field order:\n%s", line, body)
		}

		previous = found
	}
}

// A field without proto3 `optional` travels on every call, and one with it
// travels only when the caller supplied it. Reading that off the declaration is
// what makes an explicit "" or 0 reach the API instead of being dropped.
func TestEmitsPresenceFromTheFieldDeclaration(t *testing.T) {
	t.Parallel()

	source := readGenerated(t, runGen(t), "domain.gen.go")

	// domain is declared without `optional` on create and with it on update,
	// so the same field name proves both halves of the rule.
	if !strings.Contains(handlerBody(t, source, "linodeDomainCreateBody"), `body.PutString("domain")`) {
		t.Error("create writes its required domain by presence, want unconditionally")
	}

	if !strings.Contains(handlerBody(t, source, "linodeDomainUpdateBody"), `body.SetString("domain")`) {
		t.Error("update writes its optional domain unconditionally, want by presence")
	}
}

// The prose a mutation reports comes from the contract, filled from the
// resource the API answered with before the call's own arguments: a create
// echoes the label actually stored, an update reports the id it was addressed
// by.
func TestEmitsTheSuccessMessageFromTheContract(t *testing.T) {
	t.Parallel()

	source := readGenerated(t, runGen(t), "domain.gen.go")

	created := handlerBody(t, source, "handleLinodeDomainCreate")
	want := `"Domain '%s' (ID: %d) created successfully", payload.GetDomain(), payload.GetId()`

	if !strings.Contains(created, want) {
		t.Errorf("create does not report the declared success message:\n%s", created)
	}

	updated := handlerBody(t, source, "handleLinodeDomainUpdate")
	if !strings.Contains(updated, `"Domain %d modified successfully", domainID`) {
		t.Errorf("update does not fill its success message from the path id:\n%s", updated)
	}
}

// A preview reports the call the tool would have made, resolved from the route
// rather than written out beside it, so a renamed path cannot leave the preview
// naming the old one.
func TestEmitsThePreviewCallFromTheRoute(t *testing.T) {
	t.Parallel()

	source := readGenerated(t, runGen(t), "domain.gen.go")

	preview := handlerBody(t, source, "previewLinodeDomainUpdate")
	want := `tools.RunDeclaredStatePreview(ctx, request, cfg, "linode_domain_update", "PUT", fmt.Sprintf("/domains/%d", domainID),`

	if !strings.Contains(preview, want) {
		t.Errorf("preview does not report the resolved call:\n%s", preview)
	}
}

// The destroy tier emits a configuration rather than a handler body, and the
// field names in it are load-bearing: cmd/write-proto-dump reads SuccessProto
// at this literal to decide whether the tool is proto-routed, so an
// indirection here would silently reclassify the tool as legacy.
func TestEmitsTheDestroyConfigurationTheContractDescribes(t *testing.T) {
	t.Parallel()

	source := readGenerated(t, runGen(t), "domain.gen.go")

	body := handlerBody(t, source, "handleLinodeDomainDelete")

	for _, want := range []string{
		`tools.RunDestructiveActionWithID(ctx, request, cfg, &tools.DestructiveActionByID{`,
		`ToolName:       "linode_domain_delete",`,
		`IDParam:        "domain_id",`,
		`Method:         "DELETE",`,
		`PathPattern:    "/domains/%d",`,
		`ConfirmMessage: "This operation is destructive and deletes all DNS records. Set confirm=true to proceed.",`,
		`SuccessProto:   successLinodeDomainDelete,`,
		`state := &linodev1.Domain{}`,
		`return client.CallRoute(ctx, "linode_domain_delete", []any{domainID})`,
		`declared, err := tools.DeclaredStateOf(state)`,
		`return tools.RunDependencyWalks(ctx, client, []tools.WalkSpec{`,
		`"linode_domain_record_list"`,
		`Filter: &tools.WalkSpecFilter{`,
		`"NS record for {name}"`,
		`WhenPositive: "total",`,
		`HashIgnore: twostage.HashIgnoreFields("Domain"),`,
	} {
		if !strings.Contains(body, want) {
			t.Errorf("emitted destroy is missing %q:\n%s", want, body)
		}
	}
}

// A delete answers with an empty body, so its own answer is built from the call
// rather than decoded: the declared sentence over the ids it was addressed by.
func TestEmitsTheDestroyIDEchoFromTheCall(t *testing.T) {
	t.Parallel()

	source := readGenerated(t, runGen(t), "domain.gen.go")

	body := handlerBody(t, source, "successLinodeDomainDelete")

	for _, want := range []string{
		`func successLinodeDomainDelete(domainID int) proto.Message`,
		`Message:  fmt.Sprintf("Domain %d and all its records removed successfully", domainID),`,
		`DomainId: tools.IDToInt32(domainID),`,
	} {
		if !strings.Contains(body, want) {
			t.Errorf("emitted id echo is missing %q:\n%s", want, body)
		}
	}
}

// A destroy with no dependency walk previews the call and the state alone, so
// the field is left off rather than emitted nil: the driver reads its absence.
func TestEmitsNoDependencyWalkWhenNoneIsDeclared(t *testing.T) {
	t.Parallel()

	source := readGenerated(t, runGen(t), "sshkey.gen.go")

	body := handlerBody(t, source, "handleLinodeSshkeyDelete")
	if strings.Contains(body, "DependencyWalk") {
		t.Errorf("emitted destroy names a walk its contract does not declare:\n%s", body)
	}

	if !strings.Contains(body, `client.CallProtoRouteState(ctx, "linode_sshkey_get", []any{sshKeyID}, "", state)`) {
		t.Errorf("emitted destroy does not reach its state fetch:\n%s", body)
	}
}

// Three mutations answer with the bare API resource rather than a {message,
// resource} envelope. There is no member to place the body in and no prose
// field to report over it, so the tool answers with the decoded resource the
// way a read does, which is what the hand-written tool it replaces returns.
func TestEmitsTheBareResourceAMutationAnswersWith(t *testing.T) {
	t.Parallel()

	// The tool is in the real cohort now, so the real list proves the shape.
	dir := runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile)))
	body := handlerBody(t, readGenerated(t, dir, "placement.gen.go"), "handleLinodePlacementGroupUpdate")

	for _, want := range []string{
		`payload := &linodev1.PlacementGroup{}`,
		`client.CallProtoRouteBody(ctx, "linode_placement_group_update", []any{groupID}, body, "placement group update", payload)`,
		marshalPayload,
	} {
		if !strings.Contains(body, want) {
			t.Errorf("emitted mutation is missing %q:\n%s", want, body)
		}
	}

	if strings.Contains(body, "WriteResponse") {
		t.Errorf("emitted mutation wraps its answer in an envelope it does not declare:\n%s", body)
	}
}

// A mutation that declares explicit_null_fields keeps the raw body it decoded,
// because the decoded message no longer says which of its absent members the API
// sent as null.
func TestEmitsTheExplicitNullRestorationAMutationDeclares(t *testing.T) {
	t.Parallel()

	dir := runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile)))
	body := handlerBody(t, readGenerated(t, dir, "ip.gen.go"), "handleLinodeNetworkingReservedIPCreate")

	nulls := `[]string{"assigned_entity", "gateway", "interface_id", "linode_id", "rdns", "vpc_nat_1_1"}`

	for _, want := range []string{
		`raw, err := client.CallProtoRouteBodyRaw(ctx, "linode_networking_reserved_ip_create", nil, body, "networking reserved ip create", payload)`,
		`return tools.MarshalProtoToolResponseRestoringNulls(payload, raw, "", ` + nulls + `)`,
	} {
		if !strings.Contains(body, want) {
			t.Errorf("emitted mutation is missing %q:\n%s", want, body)
		}
	}
}

// The bare shape is the write tier in every respect but its answer, so it keeps
// the gate a mutation is reached through: a live call confirms first, and the
// dry run it delegates to has nothing to confirm.
func TestBareResourceMutationKeepsTheWriteGate(t *testing.T) {
	t.Parallel()

	source := readGenerated(t,
		runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile))),
		"placement.gen.go")

	live := handlerBody(t, source, "handleLinodePlacementGroupUpdate")

	confirm := strings.Index(live, `tools.RequireConfirm(request, "This updates a placement group. Set confirm=true to proceed.")`)
	preview := strings.Index(live, "previewLinodePlacementGroupUpdate(ctx, request, cfg)")

	if confirm < 0 || preview < 0 {
		t.Fatalf("live branch is missing its gate or its preview:\n%s", live)
	}

	if preview > confirm {
		t.Errorf("live branch gates on confirm before it answers a dry run:\n%s", live)
	}

	if strings.Contains(handlerBody(t, source, "previewLinodePlacementGroupUpdate"), "tools.RequireConfirm(") {
		t.Error("dry-run branch gates on confirm")
	}
}

// A free-form map declaring body_root IS the request body: PUT
// /profile/preferences reads {"theme":"dark"}, and nesting it under the member
// name posts a body the API ignores while reporting success.
func TestEmitsTheHoistedBodyThePreferencesUpdateDeclares(t *testing.T) {
	t.Parallel()

	source := readGenerated(t, runGen(t), "profile.gen.go")

	build := handlerBody(t, source, "linodeProfilePreferencesUpdateBody")
	if want := `body.SetObjectRoot("preferences")`; !strings.Contains(build, want) {
		t.Errorf("the hoisted body is not written through the root setter (%q):\n%s", want, build)
	}

	if strings.Contains(build, `body.SetObject("preferences")`) {
		t.Errorf("the map is still nested under its own member:\n%s", build)
	}
}

// A mutation whose answer carries values beside its resource decodes into its
// own envelope, because that is the only shape that reads both: POST
// /images/upload answers {image, upload_to}, and decoding into Image alone
// reads neither member.
func TestEmitsTheResponseBodyMembersTheUploadDeclares(t *testing.T) {
	t.Parallel()

	dir := runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile)))
	body := handlerBody(t, readGenerated(t, dir, "image.gen.go"), "handleLinodeImageUpload")

	for _, want := range []string{
		`payload := &linodev1.ImageUploadWriteResponse{}`,
		`client.CallProtoRouteBody(ctx, "linode_image_upload", nil, body, "image upload", payload)`,
		// The sentence reaches through the member the decode filled, since the
		// envelope itself carries no id to name.
		`payload.Message = fmt.Sprintf("Image upload '%s' (%s) created successfully", ` +
			`payload.GetImage().GetLabel(), payload.GetImage().GetId())`,
		marshalPayload,
	} {
		if !strings.Contains(body, want) {
			t.Errorf("emitted mutation is missing %q:\n%s", want, body)
		}
	}

	if strings.Contains(body, "Image: payload") {
		t.Errorf("emitted mutation wraps a resource the decode already placed:\n%s", body)
	}
}

// The same shape with no resource member at all: the scratch code and its expiry
// are the whole answer. Without the declaration the tool lands on the
// acknowledge tier, which decodes nothing and would report both empty.
func TestEmitsTheScalarOnlyResponseBodyTheTfaConfirmDeclares(t *testing.T) {
	t.Parallel()

	const tool = "linode_profile_tfa_enable_confirm"

	dir := runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile)))
	body := handlerBody(t, readGenerated(t, dir, "profile.gen.go"), "handleLinodeProfileTfaEnableConfirm")

	for _, want := range []string{
		`payload := &linodev1.ProfileTfaEnableConfirmResponse{}`,
		`client.CallProtoRouteBody(ctx, "` + tool + `", nil, body, "profile tfa enable confirm", payload)`,
		`payload.Message = fmt.Sprintf("Profile two-factor authentication enabled successfully")`,
		marshalPayload,
	} {
		if !strings.Contains(body, want) {
			t.Errorf("emitted mutation is missing %q:\n%s", want, body)
		}
	}

	if strings.Contains(body, "run_acknowledge") || strings.Contains(body, "Scratch:") {
		t.Errorf("emitted mutation assembles members the API answered with:\n%s", body)
	}
}

// A response carrying a warning field promises a client the notice that sits
// beside a secret it will never see again, and the declared sentence is what
// fills it. The refusal behind this, a warning field with no sentence declared,
// has no tool left to fire on: the key create declares its own and the update
// answers with an envelope carrying no warning at all. It is pinned in the
// Python emitter's unit test, which builds the contract to refuse rather than
// asking for a tool written to be refused.
//
// linode_object_storage_key_create is the positive case its own refusal named:
// {message, key, warning}, all three filled from one call.
func TestFillsTheDeclaredWarningBesideTheSecretItSitsWith(t *testing.T) {
	t.Parallel()

	source := readGenerated(t, runGen(t), "object_storage.gen.go")

	live := handlerBody(t, source, "handleLinodeObjectStorageKeyCreate")

	for _, want := range []string{
		`&linodev1.ObjectStorageKeyCreateResponse{`,
		`Warning: "IMPORTANT: The secret_key below is shown ONLY ONCE. Save it now - it cannot be retrieved later."`,
		`Key:     payload,`,
	} {
		if !strings.Contains(live, want) {
			t.Errorf("the key create does not answer with %q:\n%s", want, live)
		}
	}

	// The sibling shares neither the envelope nor the notice: an update
	// re-reads no secret, so a warning there would promise one that does not
	// exist.
	update := handlerBody(t, source, "handleLinodeObjectStorageKeyUpdate")
	if strings.Contains(update, "Warning:") {
		t.Errorf("the key update answers with a warning it never had:\n%s", update)
	}
}

// An assembled answer is filled by name, so a member naming no argument would
// reach a client as a zero over a change already made. The alias exists for the
// member the API spells its own way; without one declared, the mismatch is a
// refusal rather than a guess.
//
// linode_instance_disk_resize is the shape: its answer carries new_size_mb and
// the argument is size. It declares echo_argument, so this is the positive
// case, and the refusal behind it is pinned by the unit test on readWriteScalars
// rather than by a tool written to be refused.
func TestFillsAResponseMemberFromTheArgumentItsAliasNames(t *testing.T) {
	t.Parallel()

	source := readGenerated(t,
		runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile))), "instance_disk.gen.go")

	live := handlerBody(t, source, "handleLinodeInstanceDiskResize")
	if want := `NewSizeMb: tools.IDToInt32(size)`; !strings.Contains(live, want) {
		t.Errorf("the aliased member is not filled from its argument (%q):\n%s", want, live)
	}
}

// A destroy with no state read has nothing to preview or hash, and serving it
// would answer a dry run and a plan with an empty resource rather than say so.
// The emitter refuses one, and this reads that refusal off the tree rather than
// off a specimen: every destroy the contract declares now declares its read, so
// there is no tool left to drop from the hand-written list and be refused.
func TestEveryEmittedDestroyNamesItsStateFetch(t *testing.T) {
	t.Parallel()

	dir := runGen(t)

	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read emitted tree: %v", err)
	}

	var removals int

	for _, entry := range entries {
		source := readGenerated(t, dir, entry.Name())

		for _, literal := range destroyLiterals(source) {
			removals++

			if !strings.Contains(literal, "FetchState:") {
				t.Errorf("%s emits a removal that names no state fetch:\n%s", entry.Name(), literal)
			}
		}
	}

	if removals == 0 {
		t.Fatal("the emitted tree holds no removals, so this case proves nothing")
	}
}

// A removal that declares no state_route reads its state through the GET
// declared beside it on the same route, rather than through a hand-written step
// per delete. The synthesized fetch names that sibling and reaches no
// hand-written body.
func TestDestroyWithoutADeclaredRouteReadsItsSibling(t *testing.T) {
	t.Parallel()

	dir := runGen(t)

	synthesized := handlerBody(t,
		readGenerated(t, dir, "monitor_stream.gen.go"),
		"handleLinodeMonitorStreamDestinationDelete")

	for _, want := range []string{
		"state := &linodev1.MonitorStreamDestination{}",
		`client.CallProtoRouteState(ctx, "linode_monitor_stream_destination_get", []any{destinationID}, "", state)`,
		"return tools.ProjectDeclaredState(raw, state)",
	} {
		if !strings.Contains(synthesized, want) {
			t.Errorf("the synthesized state fetch is missing %q:\n%s", want, synthesized)
		}
	}

	if strings.Contains(synthesized, "toolhooks.") {
		t.Errorf("a synthesized state fetch still reaches a hand-written body:\n%s", synthesized)
	}

	// The VLAN delete is the specimen for the declared scan: its state is a
	// whole-collection read matched on region and label together, worded into
	// the not-found sentence.
	scanned := handlerBody(t, readGenerated(t, dir, "vlan.gen.go"), "handleLinodeVlanDelete")

	for _, want := range []string{
		`tools.FetchCollectionScan(ctx, client, "linode_vlan_list", []any{},`,
		"func(item *linodev1.VLAN) bool { return item.GetRegion() == regionID && item.GetLabel() == label },",
		`fmt.Sprintf("region='%v', label='%v'", regionID, label))`,
	} {
		if !strings.Contains(scanned, want) {
			t.Errorf("the emitted scan fetch is missing %q:\n%s", want, scanned)
		}
	}
}

// Every synthesized fetch reads the route its own removal removes, which is the
// resolution rule stated as an invariant over the whole tree: a sibling picked
// off a neighboring route would preview a resource the delete never touches.
// Read off the emitted text rather than off one specimen, so a future
// mis-resolution anywhere fails here.
func TestEverySynthesizedStateFetchReadsItsOwnRoute(t *testing.T) {
	t.Parallel()

	dir := runGen(t)

	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read emitted tree: %v", err)
	}

	var synthesized int

	routes := declaredStateRoutes(t)

	for _, entry := range entries {
		for _, literal := range destroyLiterals(readGenerated(t, dir, entry.Name())) {
			sibling, found := synthesizedStateRead(literal)
			if !found {
				continue
			}

			// A declared route is deliberately not the removal's own: a share
			// group token delete reads its parent group rather than the
			// credential. It is held to the route it names instead.
			if want, declares := routes[removalTool(literal)]; declares {
				if sibling != want {
					t.Errorf("%s declares state_route %s but reads through %s",
						removalTool(literal), want, sibling)
				}

				continue
			}

			synthesized++

			route, routeErr := linoderoute.For(sibling)
			if routeErr != nil {
				t.Errorf("a removal reads state through %s, which declares no route: %v",
					sibling, routeErr)

				continue
			}

			// The removal's pattern carries its surface, so the sibling's
			// template is read with its own. Comparing them surface and all
			// pins the stronger invariant: a preview that fetched state from
			// one base while the removal addressed another would describe a
			// resource it is not about to delete.
			segment, segErr := linoderoute.SurfaceSegment(route.Surface)
			if segErr != nil {
				t.Errorf("state read %s declares a surface this build cannot address: %v",
					sibling, segErr)

				continue
			}

			read := route.Template
			if segment != linoderoute.DefaultSurfaceSegment {
				read = "/" + segment + read
			}

			if route.Method != http.MethodGet || slotless(read) != slotless(removalPath(literal)) {
				t.Errorf("a removal of %s reads state through %s %s (%s)",
					removalPath(literal), route.Method, read, sibling)
			}
		}
	}

	if synthesized == 0 {
		t.Fatal("no removal synthesizes its state fetch, so this case proves nothing")
	}
}

// synthesizedStateRead is the tool a removal's state fetch reads through, and
// whether it synthesized one at all. A removal naming a hook has no such call.
func synthesizedStateRead(literal string) (string, bool) {
	for _, call := range []string{`client.CallProtoRoute(ctx, "`, `client.CallProtoRouteState(ctx, "`} {
		_, rest, found := strings.Cut(literal, call)
		if !found {
			continue
		}

		tool, _, closed := strings.Cut(rest, `"`)

		return tool, closed
	}

	return "", false
}

// removalTool is the tool name a destroy literal carries, which is what pairs
// the emitted fetch with the declaration it came from.
func removalTool(literal string) string {
	_, rest, found := strings.Cut(literal, "ToolName:")
	if !found {
		return ""
	}

	_, quoted, opened := strings.Cut(rest, `"`)
	if !opened {
		return ""
	}

	name, _, _ := strings.Cut(quoted, `"`)

	return name
}

// declaredStateRoutes maps every removal that names the read its state comes
// from to that read, which is the one case the route invariant above does not
// hold.
func declaredStateRoutes(t *testing.T) map[string]string {
	t.Helper()

	declaredMessages := make([]protoreflect.MessageDescriptor, 0)

	// Collected under the registry's read lock and read after it is released,
	// for the reason walkMessages does the same: Options() unmarshals lazily
	// through that same lock, and a read lock is not reentrant.
	protoregistry.GlobalFiles.RangeFiles(func(file protoreflect.FileDescriptor) bool {
		messages := file.Messages()
		for i := range messages.Len() {
			declaredMessages = append(declaredMessages, messages.Get(i))
		}

		return true
	})

	found := make(map[string]string, len(declaredMessages))

	for _, message := range declaredMessages {
		options := message.Options()

		route, _ := proto.GetExtension(options, linodev1.E_ToolRoute).(*linodev1.ToolRoute)
		declared, _ := proto.GetExtension(options, linodev1.E_StateRoute).(*linodev1.StateRoute)

		if route.GetTool() != "" && declared.GetTool() != "" {
			found[route.GetTool()] = declared.GetTool()
		}
	}

	return found
}

// slotless replaces every filled slot with one marker, so a route template and
// the Sprintf pattern emitted from it compare equal. The contract spells a slot
// {destination_id} and the pattern spells the same slot %d or %s, and neither
// spelling is the fact under test: the segments around them are.
func slotless(path string) string {
	return pathSlot.ReplaceAllString(path, "*")
}

// pathSlot is a filled slot in either spelling: the contract's {name} and the
// %d or %s an emitted Sprintf pattern carries in its place.
var pathSlot = regexp.MustCompile(`\{[a-z][a-z0-9_]*\}|%[ds]`)

// removalPath is the route a removal's configuration names: a Sprintf pattern
// on the single-id wrapper, the same pattern inside a built expression on every
// other removal.
func removalPath(literal string) string {
	for _, key := range []string{"PathPattern:", "Path:"} {
		_, rest, found := strings.Cut(literal, key)
		if !found {
			continue
		}

		_, quoted, opened := strings.Cut(rest, `"`)
		if !opened {
			continue
		}

		text, _, closed := strings.Cut(quoted, `"`)
		if !closed {
			continue
		}

		return text
	}

	return ""
}

// destroyLiterals cuts out each removal configuration in one emitted file, from
// the driver call to the closing brace of the literal it is handed.
func destroyLiterals(source string) []string {
	var literals []string

	for _, driver := range []string{
		"tools.RunDestructiveAction(ctx, request, cfg, &tools.DestructiveAction{",
		"tools.RunDestructiveActionWithID(ctx, request, cfg, &tools.DestructiveActionByID{",
	} {
		rest := source
		for {
			start := strings.Index(rest, driver)
			if start < 0 {
				break
			}

			rest = rest[start:]

			literal, _, closed := strings.Cut(rest, "\n\t})\n")
			if !closed {
				break
			}

			literals = append(literals, literal)
			rest = rest[len(driver):]
		}
	}

	return literals
}

// TestEmitsTheObjectBodySetterAndItsRedaction: the free-form object is the one
// body kind neither emitter could write, so its setter is proven against the
// real descriptor rather than a synthetic one. The card details reach the live
// request as the caller sent them and the dry run as a marker, which is the
// only place the two branches are allowed to differ. The setter reads presence
// from the arguments because a map cannot carry proto3 `optional`.
func TestEmitsTheObjectBodySetterAndItsRedaction(t *testing.T) {
	t.Parallel()

	source := readGenerated(t,
		runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile))), "account.gen.go")

	if want := `body.SetObject("data")`; !strings.Contains(source, want) {
		t.Errorf("emitted body is missing %q", want)
	}

	live := handlerBody(t, source, "handleLinodeAccountPaymentMethodCreate")
	if want := `body, "account payment method create", payload)`; !strings.Contains(live, want) {
		t.Errorf("live call is missing the derived subject %q:\n%s", want, live)
	}

	if strings.Contains(live, "Redacting(") {
		t.Errorf("live call reports a stood-in body, which would send the marker:\n%s", live)
	}

	preview := handlerBody(t, source, "previewLinodeAccountPaymentMethodCreate")
	if want := `body.Redacting("data")`; !strings.Contains(preview, want) {
		t.Errorf("preview is missing %q:\n%s", want, preview)
	}
}

// TestEmitsTheItemStandInTheSecurityAnswersDeclare: the answers reach the live
// request as the caller sent them and the dry run with one member of each entry
// stood in for, which is the shape a whole-member redaction cannot report: the
// question ids beside them are what a caller checks before confirming.
func TestEmitsTheItemStandInTheSecurityAnswersDeclare(t *testing.T) {
	t.Parallel()

	source := readGenerated(t,
		runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile))), "profile.gen.go")

	live := handlerBody(t, source, "handleLinodeProfileSecurityQuestionAnswer")
	if strings.Contains(live, "StandingIn(") {
		t.Errorf("live call reports a stood-in body, which would send the text:\n%s", live)
	}

	preview := handlerBody(t, source, "previewLinodeProfileSecurityQuestionAnswer")
	if want := `body.StandingIn("security_questions", "response", "[redacted]")`; !strings.Contains(preview, want) {
		t.Errorf("preview is missing %q:\n%s", want, preview)
	}
}

// TestEmitsTheObjectListBodySetterTheGrantsSectionsDeclare: a repeated
// google.protobuf.Struct is the only array of objects a body can carry, and
// account user grants declare eleven of them. Every other repeated message
// kind stays refused, which is why the positive case is pinned against the
// real descriptor rather than a synthetic one.
func TestEmitsTheObjectListBodySetterTheGrantsSectionsDeclare(t *testing.T) {
	t.Parallel()

	source := readGenerated(t,
		runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile))), "account_user.gen.go")

	for _, want := range []string{
		`body.SetObject("global")`,
		`body.SetObjectList("linode")`,
		`body.SetObjectList("lkecluster")`,
	} {
		if !strings.Contains(source, want) {
			t.Errorf("emitted body is missing %q", want)
		}
	}

	// The typed reader is the other half of the same classification, so a
	// section reaching it would mean the free-form path lost a tool it owns.
	if strings.Contains(source, "SetMessageList") {
		t.Errorf("a free-form grant section reached the typed list reader:\n%s", source)
	}
}

// TestEmitsTheMessageListSetterTheShareGroupImagesDeclare: a repeated named
// message is the array of objects whose members the contract does fix, so the
// setter carries the item spec the reader holds each entry to. Pinned against
// the real descriptor, since the item shape is the proto's rather than a
// synthetic one.
func TestEmitsTheMessageListSetterTheShareGroupImagesDeclare(t *testing.T) {
	t.Parallel()

	source := readGenerated(t,
		runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile))),
		"image_sharegroup.gen.go")

	want := "body.SetMessageList(\"images\", []tools.ItemField{\n" +
		"\t\t{Name: \"id\", Kind: tools.ItemString, Required: true},\n" +
		"\t\t{Name: \"label\", Kind: tools.ItemString},\n" +
		"\t\t{Name: \"description\", Kind: tools.ItemString},\n" +
		"\t})"

	if !strings.Contains(source, want) {
		t.Errorf("emitted body is missing the item spec:\n%s", handlerBody(t, source, "linodeImageSharegroupCreateBody"))
	}

	// A free-form list has no members to name, so its setter takes only a name.
	if strings.Contains(source, `body.SetObjectList("images")`) {
		t.Errorf("a typed item list reached the free-form reader:\n%s", source)
	}
}

// TestEmitsTheNestedMessageSetterTheInterfaceArmsDeclare: an interface arm is
// the shape the recursive reader exists for, a named message whose own members
// carry named messages and lists of them. Pinned against the real descriptor at
// every depth, since declaration order there is wire order and a member read at
// the wrong depth would still compile.
func TestEmitsTheNestedMessageSetterTheInterfaceArmsDeclare(t *testing.T) {
	t.Parallel()

	source := readGenerated(t,
		runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile))),
		"instance.gen.go")

	want := "body.SetMessageOrNull(\"vpc\", []tools.ItemField{\n" +
		"\t\t{Name: \"subnet_id\", Kind: tools.ItemInt, Required: true},\n" +
		"\t\t{Name: \"ipv4\", Kind: tools.ItemMessage, Fields: []tools.ItemField{\n" +
		"\t\t\t{Name: \"addresses\", Kind: tools.ItemMessageList, Fields: []tools.ItemField{\n" +
		"\t\t\t\t{Name: \"address\", Kind: tools.ItemString, Required: true},\n" +
		"\t\t\t\t{Name: \"primary\", Kind: tools.ItemBool},\n" +
		"\t\t\t\t{Name: \"nat_1_1_address\", Kind: tools.ItemString},\n" +
		"\t\t\t}},\n" +
		"\t\t\t{Name: \"ranges\", Kind: tools.ItemMessageList, Fields: []tools.ItemField{\n" +
		"\t\t\t\t{Name: \"range\", Kind: tools.ItemString, Required: true},\n" +
		"\t\t\t}},\n" +
		"\t\t}},\n" +
		"\t})"

	if !strings.Contains(source, want) {
		t.Errorf("emitted body is missing the nested item spec:\n%s",
			handlerBody(t, source, "linodeInstanceInterfaceAddBody"))
	}

	// The arms accept the API's own "not this one" spelling, so none of them may
	// reach the setter that reads a null as absence.
	if strings.Contains(source, `body.SetMessage("vpc"`) {
		t.Errorf("a nullable arm reached the plain message reader:\n%s", source)
	}
}

// TestEmitsTheBodyRenameTheUpdateDeclares: linode_account_user_update is the one
// tool whose body renames an argument, because PUT /account/users/{username}
// reads the rename through a second "username" member that the path already
// spends. The argument keeps the proto field name, so only the emitted Rename
// puts the declared wire key on the body.
func TestEmitsTheBodyRenameTheUpdateDeclares(t *testing.T) {
	t.Parallel()

	source := readGenerated(t,
		runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile))), "account_user.gen.go")

	for _, want := range []string{
		`body.Rename("new_username", "username")`,
		`body.SetString("new_username")`,
	} {
		if !strings.Contains(source, want) {
			t.Errorf("emitted body is missing %q", want)
		}
	}

	live := handlerBody(t, source, "handleLinodeAccountUserUpdate")
	if strings.Contains(live, `body.SetString("username")`) {
		t.Errorf("the path username reached the body as an argument:\n%s", live)
	}
}

// TestEmitsTheStringMapBodySetterTheNodePoolLabelsDeclare: a map from string to
// string is the one typed map a body carries, and it classifies apart from the
// free-form object map the same declaration otherwise looks like. Pinned against
// the real descriptor, since both map shapes live on the same message.
func TestEmitsTheStringMapBodySetterTheNodePoolLabelsDeclare(t *testing.T) {
	t.Parallel()

	source := readGenerated(t,
		runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile))), "lke_pool.gen.go")

	for _, want := range []string{
		`body.SetStringMap("labels")`,
		`body.SetObject("autoscaler")`,
	} {
		if !strings.Contains(source, want) {
			t.Errorf("emitted body is missing %q", want)
		}
	}

	// The free-form reader would drop the check that every value is text, which
	// is the whole difference between the two map shapes.
	if strings.Contains(source, `body.SetObject("labels")`) {
		t.Errorf("a string map reached the free-form reader:\n%s", source)
	}
}

// TestEmitsTheListEchoTheReorderDeclares: the interface reorder is the one tool
// on the surface whose answer echoes a repeated argument back with its prose
// fully declared, so the read and the response member are pinned against the
// real descriptor. The API answers the reorder with an empty body, which is why
// the applied order has to come from the call.
func TestEmitsTheListEchoTheReorderDeclares(t *testing.T) {
	t.Parallel()

	source := readGenerated(t,
		runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile))),
		"instance.gen.go")

	for _, want := range []string{
		`ids := tools.EchoInt32s(request, "ids")`,
		"Ids:      ids,",
	} {
		if !strings.Contains(source, want) {
			t.Errorf("emitted handler is missing %q:\n%s",
				want, handlerBody(t, source, "handleLinodeInstanceConfigInterfaceReorder"))
		}
	}

	// A list read through the scalar accessor would answer 0 rather than the
	// order the caller sent, which is the shape this reader replaces.
	if strings.Contains(source, `request.GetInt("ids"`) {
		t.Errorf("a repeated echo reached the scalar reader:\n%s", source)
	}
}

// The decoded envelope's third shape: an answer whose members the API fills
// include one spelled like an argument and one repeating a message. The upgrade
// route picks the config profile when the caller names none, so echoing the
// argument back would report a profile the API may never have touched, and the
// interfaces it answers with were never in the call to echo.
func TestEmitsTheAPIFilledMembersTheInterfaceUpgradeDeclares(t *testing.T) {
	t.Parallel()

	const tool = "linode_instance_interface_upgrade"

	dir := runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile)))
	source := readGenerated(t, dir, "instance.gen.go")
	body := handlerBody(t, source, "handleLinodeInstanceInterfaceUpgrade")

	for _, want := range []string{
		`payload := &linodev1.InstanceInterfaceUpgradeWriteResponse{}`,
		`client.CallProtoRouteBody(ctx, "` + tool + `", []any{linodeID}, body, "instance interface upgrade", payload)`,
		`payload.Message = fmt.Sprintf("Linode %d interface upgrade initiated", linodeID)`,
		marshalPayload,
	} {
		if !strings.Contains(body, want) {
			t.Errorf("emitted mutation is missing %q:\n%s", want, body)
		}
	}

	for _, unwanted := range []string{"payload.ConfigId =", "payload.DryRun =", "payload.Interfaces ="} {
		if strings.Contains(body, unwanted) {
			t.Errorf("emitted mutation writes %q over what the decode placed:\n%s", unwanted, body)
		}
	}

	// The argument the API answers under a different key still reaches the wire
	// under the key the route reads.
	if !strings.Contains(source, `body.Rename("api_dry_run", "dry_run")`) {
		t.Errorf("emitted body does not rename api_dry_run to the wire key:\n%s", source)
	}
}

// TestEmitsTheItemKindsTheNodePoolsDeclare: LKENodePoolCreateItem is the one
// item message carrying members beyond scalars, an open autoscaler beside a tag
// list, so it is what proves the walker names both.
func TestEmitsTheItemKindsTheNodePoolsDeclare(t *testing.T) {
	t.Parallel()

	source := readGenerated(t,
		runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile))),
		"lke.gen.go")

	want := "body.SetMessageList(\"node_pools\", []tools.ItemField{\n" +
		"\t\t{Name: \"type\", Kind: tools.ItemString, Required: true},\n" +
		"\t\t{Name: \"count\", Kind: tools.ItemInt, Required: true},\n" +
		"\t\t{Name: \"autoscaler\", Kind: tools.ItemObject},\n" +
		"\t\t{Name: \"tags\", Kind: tools.ItemStringList},\n" +
		"\t})"

	if !strings.Contains(source, want) {
		t.Errorf("emitted body is missing the item spec:\n%s",
			handlerBody(t, source, "linodeLkeClusterCreateBody"))
	}
}

// TestEmitsTheNullableStringSetterTheManagedUpdatesDeclare: body_nullable on an
// optional string is what routes a field to the setter that keeps null and
// absent apart, and the Managed updates are the only tools declaring it. The
// plain setter beside them in the same body is what proves the routing is per
// field rather than per tool.
func TestEmitsTheNullableStringSetterTheManagedUpdatesDeclare(t *testing.T) {
	t.Parallel()

	source := readGenerated(t,
		runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile))),
		"managed.gen.go")

	for _, want := range []string{
		`body.SetStringOrNull("body")`,
		`body.SetStringOrNull("notes")`,
		`body.SetStringOrNull("region")`,
		`body.SetString("label")`,
	} {
		if !strings.Contains(handlerBody(t, source, "linodeManagedServiceUpdateBody"), want) {
			t.Errorf("emitted body is missing %q:\n%s", want,
				handlerBody(t, source, "linodeManagedServiceUpdateBody"))
		}
	}

	contact := handlerBody(t, source, "linodeManagedContactUpdateBody")
	if want := `body.SetStringOrNull("group")`; !strings.Contains(contact, want) {
		t.Errorf("emitted body is missing %q:\n%s", want, contact)
	}
}

// A read on a route that is not a GET is neither tier the route method alone
// would pick: the write tier's gate would make a read start demanding confirm,
// and the read tier sends no body at all. The presigned-URL create is the shape
// whose whole answer is the decode, so the cohort is the real list less that
// name.
func TestEmitsAReadThatSendsARequestBody(t *testing.T) {
	t.Parallel()

	const tool = "linode_object_storage_presigned_url_create"

	source := readGenerated(t,
		runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile))),
		"object_storage.gen.go")

	handler := handlerBody(t, source, "handleLinodeObjectStoragePresignedURLCreate")

	for _, want := range []string{
		`body, message := linodeObjectStoragePresignedURLCreateBody(request)`,
		`response := &linodev1.PresignedURLResponse{}`,
		`client.CallProtoRouteBody(ctx, "` + tool + `", []any{region, label}, body, ` +
			`"object storage presigned url create", response)`,
		`return tools.MarshalProtoToolResponse(response)`,
	} {
		if !strings.Contains(handler, want) {
			t.Errorf("emitted handler is missing %q:\n%s", want, handler)
		}
	}

	// The tier exists so a read stays a read: nothing here changes, so gating
	// or previewing the call would hold back an answer the caller can ask for
	// again.
	for _, unwanted := range []string{confirmGate, dryRunGate} {
		if strings.Contains(handler, unwanted) {
			t.Errorf("emitted handler carries %q:\n%s", unwanted, handler)
		}
	}

	if strings.Contains(source, "func previewLinodeObjectStoragePresignedURLCreate(") {
		t.Errorf("emitted source declares a preview for a read that changes nothing:\n%s", source)
	}

	// The body is the whole request, so every declared field has to reach it.
	for _, want := range []string{
		`body.PutString("name")`,
		`body.PutString("method")`,
		`body.SetInt("expires_in")`,
		`body.SetString("content_type")`,
	} {
		if !strings.Contains(source, want) {
			t.Errorf("emitted body is missing %q:\n%s", want,
				handlerBody(t, source, "linodeObjectStoragePresignedURLCreateBody"))
		}
	}
}

// The second body-read answer: the metric query wraps what it decoded in its
// own envelope, so the tier assembles the prose and the echo around the decode
// rather than answering with the decode alone. Decoding into the envelope
// directly would place the samples nowhere and report an empty metrics object
// over a call that succeeded.
func TestEmitsABodyReadThatAssemblesItsEnvelope(t *testing.T) {
	t.Parallel()

	const tool = "linode_monitor_service_metric_query"

	source := readGenerated(t,
		runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile))),
		"monitor.gen.go")

	handler := handlerBody(t, source, "handleLinodeMonitorServiceMetricQuery")

	for _, want := range []string{
		`body, message := linodeMonitorServiceMetricQueryBody(request)`,
		`payload := &structpb.Struct{}`,
		`client.CallProtoRouteBody(ctx, "` + tool + `", []any{serviceType}, body, ` +
			`"monitor service metric query", payload)`,
		`Message:     fmt.Sprintf("Monitor service metrics read for '%s'", serviceType)`,
		`ServiceType: serviceType,`,
		`Metrics:     payload,`,
	} {
		if !strings.Contains(handler, want) {
			t.Errorf("emitted handler is missing %q:\n%s", want, handler)
		}
	}

	// A route declaring no body member still sends one, which is what lets the
	// tier take a read whose whole request is the empty object.
	if want := `body := tools.NewWriteBody(request, 0)`; !strings.Contains(source, want) {
		t.Errorf("emitted body is missing %q:\n%s", want,
			handlerBody(t, source, "linodeMonitorServiceMetricQueryBody"))
	}

	for _, unwanted := range []string{confirmGate, dryRunGate} {
		if strings.Contains(handler, unwanted) {
			t.Errorf("emitted handler carries %q:\n%s", unwanted, handler)
		}
	}
}

// A read whose route answers with something no decode can place: the OAuth
// client thumbnail arrives as raw PNG bytes, so its declared transport owns the
// call and one member carries what the transfer brought back. Fetched the
// ordinary way, the image would reach protojson and the tool would report a
// parse failure over a call that succeeded.
func TestEmitsAReadWhoseTransportOwnsTheCall(t *testing.T) {
	t.Parallel()

	source := readGenerated(t,
		runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile))),
		"oauth_client_thumbnail.gen.go")

	handler := handlerBody(t, source, "handleLinodeAccountOauthClientThumbnailGet")

	for _, want := range []string{
		`transferred, err := client.CallRouteRawBodyRead(` +
			`ctx, "linode_account_oauth_client_thumbnail_get", []any{clientID}, "image/png")`,
		`return tools.MarshalProtoToolResponse(&linodev1.OAuthClientThumbnail{`,
		`ClientId:           clientID,`,
		`ThumbnailPngBase64: tools.Base64Text(transferred),`,
	} {
		if !strings.Contains(handler, want) {
			t.Errorf("emitted handler is missing %q:\n%s", want, handler)
		}
	}

	// The transport is the whole call, so nothing here builds the routed fetch
	// the tier writes for every other read.
	for _, unwanted := range []string{"client.CallProtoRoute", `query := ""`} {
		if strings.Contains(handler, unwanted) {
			t.Errorf("emitted handler carries %q:\n%s", unwanted, handler)
		}
	}
}

// The presign pair is the other assembled shape: the declared POST mints a URL
// and the transfer that follows it is the tool's own, so the handler renders one
// spec literal and reads the transfer's measurements into the answer.
func TestEmitsThePresignTransferTheContractDeclares(t *testing.T) {
	t.Parallel()

	source := readGenerated(t,
		runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile))),
		"object_storage.gen.go")

	handler := handlerBody(t, source, "handleLinodeObjectStorageObjectUpload")

	for _, want := range []string{
		`transferred, err := tools.RunPresignTransfer(ctx, client, &tools.PresignSpec{`,
		`Tool:        "linode_object_storage_object_upload",`,
		`Subject:     "object storage object upload",`,
		`Up:          true,`,
		`LocalPath:   request.GetString("source_path", ""),`,
		`ContentType: request.GetString("content_type", ""),`,
		`SizeBytes:  transferred.SizeBytes,`,
		`Etag:       transferred.ETag,`,
		`UploadMode: "single",`,
	} {
		if !strings.Contains(handler, want) {
			t.Errorf("emitted handler is missing %q:\n%s", want, handler)
		}
	}

	// The dry run measures the same source the transfer would send, inside
	// the walk the declared wording is filled in, and no hand-written body
	// stands between the declaration and the report.
	preview := handlerBody(t, source, "previewLinodeObjectStorageObjectUpload")

	for _, want := range []string{
		`tools.RunDeclaredTransportPreview(ctx, request, cfg, "linode_object_storage_object_upload", "POST", `,
		`body, "source_path",`,
		`func(transfer tools.PresignPreview) tools.DryRunDetails {`,
		`"transport:size_bytes": transfer.SizeBytes,`,
	} {
		if !strings.Contains(preview, want) {
			t.Errorf("emitted preview is missing %q:\n%s", want, preview)
		}
	}

	if strings.Contains(preview, "toolhooks.") {
		t.Errorf("emitted preview still reaches a hand-written body:\n%s", preview)
	}
}

// The marker shape: the S3-backed object list pages by a cursor its previous
// answer handed out, so the emitted tool must reach the cursor-carrying
// primitive and report what it comes back with. Read as any other list shape,
// is_truncated and next_marker would be dropped and a caller holding a
// truncated page would see the end of the collection.
func TestEmitsTheMarkerListTheEnvelopeDeclares(t *testing.T) {
	t.Parallel()

	dir := runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile)))
	source := readGenerated(t, dir, "object_storage.gen.go")

	for _, want := range []string{
		`tools.NewGeneratedMarkerListTool(`,
		`linode.ListProtoRouteMarker(ctx, client, "linode_object_storage_bucket_object_list", values,`,
		`tools.WithQueryArguments(request, "", "prefix", "delimiter", "marker", "page_size")`,
		`[]string{"prefix", "delimiter"},`,
		`IsTruncated: cursor.IsTruncated, NextMarker: tools.TextOrAbsent(cursor.NextMarker)`,
	} {
		if !strings.Contains(source, want) {
			t.Errorf("emitted source is missing %q", want)
		}
	}

	// The page controls are forwarded as declared rather than read, which is
	// the whole reason this route may publish page_size as text.
	for _, unwanted := range []string{
		`NewGeneratedSubresourceListTool(
		cfg,
		"linode_object_storage_bucket_object_list"`,
		`page, pageSize int) ([]*linodev1.ObjectStorageObject`,
	} {
		if strings.Contains(source, unwanted) {
			t.Errorf("emitted source reads the page controls: %q", unwanted)
		}
	}
}

// The cursor arguments say where a page starts, not which objects it holds, so
// the answer must not report them as the filter it was narrowed by.
func TestMarkerListEchoesNoCursorArgument(t *testing.T) {
	t.Parallel()

	dir := runGenFrom(t, writeHandwritten(t, readNames(t, handwrittenFile)))
	source := readGenerated(t, dir, "object_storage.gen.go")

	for _, unwanted := range []string{
		`[]string{"prefix", "delimiter", "marker"`,
		`"page_size"},`,
	} {
		if strings.Contains(source, unwanted) {
			t.Errorf("emitted echo carries a cursor argument: %q", unwanted)
		}
	}
}

// The plan/apply arguments are a promise a caller can plan a change and apply
// the plan, so the tier that advertises them has to run the flow. This pins the
// whole branch: the requested-gate that keeps an ordinary call out of it, the
// checks it shares with the live path, and the action the shared flow runs.
func TestEmitsTheStagedBranchAWriteAdvertises(t *testing.T) {
	t.Parallel()

	source := readGenerated(t, runGen(t), "instance.gen.go")

	for _, want := range []string{
		"func twoStageLinodeInstanceResize(ctx context.Context, request *mcp.CallToolRequest, cfg *config.Config) (*mcp.CallToolResult, error) {",
		"if !tools.TwoStageRequested(ctx, request) {",
		"staged, handled := tools.RunTwoStageWrite(ctx, request, cfg, &tools.DestructiveAction{",
		"Capability: profiles.CapWrite,",
		`return client.CallRouteBody(ctx, "linode_instance_resize", []any{instanceID}, body)`,
		"return tools.FetchCompositeState(ctx, client, []tools.CompositeCall{",
		`Tool:   "linode_instance_disk_list",`,
		`Fields: []string{"id", "size", "filesystem"},`,
		// The plan words the tool's own declared prose against the composite
		// member the prose reads through, so one wording serves both paths.
		`previewValues := map[string]string{`,
		`"state:type": tools.PreviewStateText(declared.Object("instance"), "type"),`,
		`details.SideEffects = []string{tools.PreviewSentence(previewValues, "Instance resizes from type {state:type} to {type};`,
	} {
		if !strings.Contains(source, want) {
			t.Errorf("emitted staged branch is missing %q", want)
		}
	}
}

// A plan is neither a preview nor a gated call, so the branch answers ahead of
// both. A call that fell to either would be answered as something else.
func TestStagedBranchRunsAheadOfThePreviewAndTheGate(t *testing.T) {
	t.Parallel()

	source := readGenerated(t, runGen(t), "instance.gen.go")

	handler := "func handleLinodeInstanceResize(ctx context.Context, request *mcp.CallToolRequest, cfg *config.Config) (*mcp.CallToolResult, error) {"

	opens := strings.Index(source, handler)
	if opens < 0 {
		t.Fatal("emitted tree has no resize handler to read")
	}

	body := source[opens+len(handler):]

	staged := strings.Index(body, "twoStageLinodeInstanceResize(ctx, request, cfg)")
	preview := strings.Index(body, "tools.IsDryRun(request)")
	gate := strings.Index(body, "tools.RequireConfirm(")

	if staged < 0 || preview < 0 || gate < 0 {
		t.Fatalf("handler is missing a branch: staged=%d preview=%d gate=%d", staged, preview, gate)
	}

	if staged > preview || preview > gate {
		t.Errorf("branches are out of order: staged=%d preview=%d gate=%d", staged, preview, gate)
	}
}

// stateReadDecode and readHandlerDecode find the message each side of a
// declared fetch decodes the raw body into: the state read at a preview or a
// plan, and the read tool's own handler.
var (
	stateReadDecode   = regexp.MustCompile(`state := &linodev1\.(\w+)\{\}\n\n\s+raw, err := client\.CallProtoRouteState\w*\(ctx, "([^"]+)"`)
	readHandlerDecode = regexp.MustCompile(`response := &linodev1\.(\w+)\{\}\n\n\tif err := client\.CallProtoRoute\w*\(ctx, "([^"]+)"`)
)

// TestEveryDeclaredFetchDecodesWhatItsReadDecodes: a declared fetch calls the
// read's own route, so it has to decode that route's body the same way the read
// does. A read answering a wrapper around the resource decodes the member and
// wraps it afterwards, and a fetch that skipped the member would project the
// raw body through a message modeling none of its fields and report an empty
// state. Only two tools name a payload member today, so nothing else would
// notice a third going missing.
func TestEveryDeclaredFetchDecodesWhatItsReadDecodes(t *testing.T) {
	t.Parallel()

	dir := runGen(t)

	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read emitted tree: %v", err)
	}

	sources := make([]string, 0, len(entries))
	for _, entry := range entries {
		sources = append(sources, readGenerated(t, dir, entry.Name()))
	}

	reads := make([][]string, 0, len(sources))
	for _, source := range sources {
		reads = append(reads, readHandlerDecode.FindAllStringSubmatch(source, -1)...)
	}

	decoded := make(map[string]string, len(reads))
	for _, match := range reads {
		decoded[match[2]] = match[1]
	}

	var fetches int

	// The three declared state forms decode through their own runtime rather
	// than the single-resource call, so each counted occurrence is one fetch.
	stateForms := regexp.MustCompile(
		`tools\.Fetch(?:CollectionScan|EnvelopeState|CompositeState)\(`,
	)
	for _, source := range sources {
		fetches += len(stateForms.FindAllString(source, -1))
	}

	for _, source := range sources {
		for _, match := range stateReadDecode.FindAllStringSubmatch(source, -1) {
			fetches++

			read := match[2]

			want, found := decoded[read]
			if !found {
				continue
			}

			if match[1] != want {
				t.Errorf("the fetch through %s decodes %s, but %s decodes %s: name the payload member",
					read, match[1], read, want)
			}
		}
	}

	// Every state route in the contract, so a scan that stopped matching cannot
	// pass by measuring nothing.
	const declaredFetches = 174

	if fetches != declaredFetches {
		t.Errorf("found %d declared fetch(es), want %d", fetches, declaredFetches)
	}
}

// envelopeStateQuery finds an envelope fetch that carries the page controls its
// tool publishes, which is the only form that previews the page the call itself
// asks for.
var envelopeStateQuery = regexp.MustCompile(
	`tools\.FetchEnvelopeState\(ctx, client, "([^"]+)".*tools\.StateReadQuery\(`,
)

// TestEveryEnvelopeFetchCarriesThePageControlsItPublishes: a replacement whose
// preview read page one while its own call published page two would describe a
// page the caller never asked about, and no behavior fixture can see it, since
// a preview's stub is matched on the path alone. The reads are named rather
// than counted: there are two, and both are page-forwarding replacements.
func TestEveryEnvelopeFetchCarriesThePageControlsItPublishes(t *testing.T) {
	t.Parallel()

	dir := runGen(t)

	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read emitted tree: %v", err)
	}

	reads := make([]string, 0, 2)

	for _, entry := range entries {
		source := readGenerated(t, dir, entry.Name())
		for _, match := range envelopeStateQuery.FindAllStringSubmatch(source, -1) {
			reads = append(reads, match[1])
		}
	}

	slices.Sort(reads)

	want := []string{"linode_instance_firewall_list", "linode_nodebalancer_firewall_list"}
	if !slices.Equal(reads, want) {
		t.Errorf("page-forwarding envelope fetches read %v, want %v", reads, want)
	}
}

// stateReadQuery finds a declared fetch that carries its read's query
// parameters on the call, which is the only form that addresses a resource a
// query names.
var stateReadQuery = regexp.MustCompile(`client\.CallProtoRouteStateQuery\(ctx, "([^"]+)"`)

// TestEveryQueryFillingFetchEmitsTheQueryCall: the contract-build refusal
// checks the declaration, not the emission, so an emitter that dropped back to
// the plain state call would ship a fetch silently reading the wrong resource,
// and no behavior fixture can see a query string. The count pins the emitted
// form the way declaredFetches does: a new query-filling row bumps it in the
// same change, and a regression empties it here by name.
func TestEveryQueryFillingFetchEmitsTheQueryCall(t *testing.T) {
	t.Parallel()

	dir := runGen(t)

	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read emitted tree: %v", err)
	}

	reads := make([]string, 0, 1)

	for _, entry := range entries {
		source := readGenerated(t, dir, entry.Name())
		for _, match := range stateReadQuery.FindAllStringSubmatch(source, -1) {
			reads = append(reads, match[1])
		}
	}

	const queryFillingFetches = 1

	if len(reads) != queryFillingFetches {
		t.Fatalf("found %d query-carrying fetch(es) %v, want %d", len(reads), reads, queryFillingFetches)
	}

	if reads[0] != "linode_object_storage_object_acl_get" {
		t.Errorf("query-carrying fetch reads %s, want linode_object_storage_object_acl_get", reads[0])
	}
}
