package main

import (
	"strings"

	"google.golang.org/protobuf/reflect/protoreflect"
)

// pyLineBudget is the line length ruff holds this repo to. The emitted tree is
// linted like hand-written code, so a line the renderer cannot fit fails the
// run.
const pyLineBudget = 88

// pyHeader marks the tree as emitted rather than written, and names the emitter
// a reader would go read: one run of go/cmd/toolgen writes both languages.
const pyHeader = "# Code generated by go/cmd/toolgen. DO NOT EDIT."

// pyPackage is the import root the registry binds the cohort under.
const pyPackage = "linodemcp.gentools"

// pySuffix marks the files this renderer owns.
const pySuffix = ".py"

// The flag spellings Python writes, which are the one rendering the two
// languages cannot share: Go prints a flag as true and Python as True.
const (
	pyTrue  = "True"
	pyFalse = "False"
)

// pyUncheckedGuard opens each step of an accumulated check, which runs only
// behind whatever the rules and the readers before it already found.
const pyUncheckedGuard = "    if not message:"

// pyDocClose is the line a multi-line docstring ends on, at the one indent
// every emitted definition sits at. A constant because goconst counts the
// literal across the whole emitter, not because two renderers could spell it
// differently.
const pyDocClose = `    """`

// The two lines every driver call opens with, which every tier spells alike.
const (
	pyDriverConfigLine    = "        cfg,"
	pyDriverArgumentsLine = "        arguments,"
)

// pyArgumentsMap is the request map every emitted read and reader is handed.
const pyArgumentsMap = "arguments"

// The branch keywords an accumulated check chains its slots with.
const (
	pyBranchIf   = "if"
	pyBranchElif = "elif"
)

// pyDocIndent is how far in a docstring's body sits, and pyProseIndent how far
// in the prose a factory and a gate wrap at. Both are the columns ruff leaves
// alone, since it cannot rewrap a string literal.
const (
	pyDocIndent   = 4
	pyProseIndent = 12
)

// pyReaderSentenceIndent is how far in ruff indents a reader call's arguments
// inside a mutation's accumulated check, which is where emitted sentences sit
// deepest. A split measured shallower overflows once ruff indents it.
const pyReaderSentenceIndent = 12

// pyReservedNames is every name Python's keyword.iskeyword or dir(builtins)
// answers to, space-delimited and space-bounded so one membership test covers
// the whole vocabulary. A path field named after one produces a local spelled
// exactly like it, which ruff refuses, so pyLocal suffixes the local instead.
const pyReservedNames = " " +
	"ArithmeticError AssertionError AttributeError BaseException " +
	"BaseExceptionGroup BlockingIOError BrokenPipeError BufferError " +
	"BytesWarning ChildProcessError ConnectionAbortedError ConnectionError " +
	"ConnectionRefusedError ConnectionResetError DeprecationWarning EOFError " +
	"Ellipsis EncodingWarning EnvironmentError Exception ExceptionGroup " +
	"False FileExistsError FileNotFoundError FloatingPointError " +
	"FutureWarning GeneratorExit IOError ImportError ImportWarning " +
	"IndentationError IndexError InterruptedError IsADirectoryError KeyError " +
	"KeyboardInterrupt LookupError MemoryError ModuleNotFoundError NameError " +
	"None NotADirectoryError NotImplemented NotImplementedError OSError " +
	"OverflowError PendingDeprecationWarning PermissionError " +
	"ProcessLookupError PythonFinalizationError RecursionError " +
	"ReferenceError ResourceWarning RuntimeError RuntimeWarning " +
	"StopAsyncIteration StopIteration SyntaxError SyntaxWarning SystemError " +
	"SystemExit TabError TimeoutError True TypeError UnboundLocalError " +
	"UnicodeDecodeError UnicodeEncodeError UnicodeError " +
	"UnicodeTranslateError UnicodeWarning UserWarning ValueError Warning " +
	"ZeroDivisionError _IncompleteInputError __build_class__ __debug__ " +
	"__doc__ __import__ __loader__ __name__ __package__ __spec__ abs aiter " +
	"all and anext any as ascii assert async await bin bool break breakpoint " +
	"bytearray bytes callable chr class classmethod compile complex continue " +
	"copyright credits def del delattr dict dir divmod elif else enumerate " +
	"eval except exec exit filter finally float for format from frozenset " +
	"getattr global globals hasattr hash help hex id if import in input int " +
	"is isinstance issubclass iter lambda len license list locals map max " +
	"memoryview min next nonlocal not object oct open or ord pass pow print " +
	"property quit raise range repr return reversed round set setattr slice " +
	"sorted staticmethod str sum super try tuple type vars while with yield " +
	"zip "

// pyReserved is whether the language already owns a name, which is what makes
// a local spelled that way a lint failure rather than a compile one.
func pyReserved(name string) bool {
	return strings.Contains(pyReservedNames, " "+name+" ")
}

// pyLocal is the local a handler reads one argument into.
func pyLocal(name string) string {
	if pyReserved(name) {
		return name + "_value"
	}

	return name
}

// pyFactoryName is the factory a tool registers through, which the registry
// finds by shape.
func pyFactoryName(tool string) string {
	return "create_" + tool + "_tool"
}

// pyHandlerName is the handler the registry pairs with the factory of the same
// tool.
func pyHandlerName(tool string) string {
	return "handle_" + tool
}

// pyBodyName is the body builder a tool's two branches share.
func pyBodyName(tool string) string {
	return "_" + tool + "_body"
}

// pyQuote is one Python string literal holding text. Contract prose carries
// quotes and braces of its own, so they are escaped rather than assumed absent.
func pyQuote(text string) string {
	escaped := strings.ReplaceAll(text, `\`, `\\`)
	escaped = strings.ReplaceAll(escaped, `"`, `\"`)

	return `"` + escaped + `"`
}

// pyEscaped is literal text as an f-string body: quotes and braces stand for
// themselves.
func pyEscaped(text string) string {
	escaped := strings.ReplaceAll(text, `\`, `\\`)
	escaped = strings.ReplaceAll(escaped, `"`, `\"`)
	escaped = strings.ReplaceAll(escaped, "{", "{{")

	return strings.ReplaceAll(escaped, "}", "}}")
}

// pyQuoteWrapped is one string literal, split across lines when it does not
// fit. The split is at spaces with the space kept on the line before it, so the
// pieces concatenate back to the exact sentence the contract declares.
func pyQuoteWrapped(text string, indent int) []string {
	return pyQuoteWrappedFor(text, indent, 0)
}

// pyQuoteWrappedFor is pyQuoteWrapped with columns held back for whatever the
// caller writes after the literal, which is the separator a list entry keeps.
func pyQuoteWrappedFor(text string, indent, reserved int) []string {
	pad := strings.Repeat(" ", indent)

	single := pad + pyQuote(text)
	if len(single)+reserved <= pyLineBudget {
		return []string{single}
	}

	lines := make([]string, 0)

	var current string

	for word := range strings.SplitSeq(text, " ") {
		candidate := current + word + " "
		// Measured through pyQuote, since escaping lengthens a segment past
		// what its raw text says.
		if current != "" && len(pad)+len(pyQuote(candidate))+reserved > pyLineBudget {
			lines = append(lines, pad+pyQuote(current))
			current = word + " "

			continue
		}

		current = candidate
	}

	return append(lines, pad+pyQuote(strings.TrimRight(current, " ")))
}

// pyProseWrapped is plain docstring prose split across lines at the indent a
// docstring's own body sits at. Unlike pyQuoteWrapped there is no literal around
// it, so the words carry no escaping and the pieces read as one paragraph rather
// than concatenating back into one value.
func pyProseWrapped(text string) []string {
	pad := strings.Repeat(" ", pyDocstringIndent)

	single := pad + text
	if len(single) <= pyLineBudget {
		return []string{single}
	}

	lines := make([]string, 0)
	held := make([]string, 0)
	width := len(pad)

	for word := range strings.SplitSeq(text, " ") {
		// The space before the word counts only once a word already stands on
		// the line, which is also what says the line cannot be emptied here.
		if len(held) > 0 && width+1+len(word) > pyLineBudget {
			lines = append(lines, pad+strings.Join(held, " "))
			held = held[:0]
			width = len(pad)
		}

		if len(held) > 0 {
			width++
		}

		held = append(held, word)
		width += len(word)
	}

	return append(lines, pad+strings.Join(held, " "))
}

// pySentenceArgument is one declared sentence as a call argument, split when it
// cannot fit. ruff format joins a call back onto one line when it fits, so
// splitting a short sentence would leave an implicit concatenation the linter
// refuses.
func pySentenceArgument(text string) string {
	return strings.Join(pyQuoteWrapped(text, pyReaderSentenceIndent), "\n")
}

// pyReaderExpression is one reader call, written a line per argument for ruff
// format to settle: it joins a call that fits and leaves a split sentence
// alone, which is the shape a long refusal needs.
func pyReaderExpression(helper string, arguments []string) string {
	var body strings.Builder

	body.Grow(len(arguments) * pyReaderSentenceIndent)

	for _, argument := range arguments {
		body.WriteString("    ")
		body.WriteString(argument)
		body.WriteString(",\n")
	}

	return helper + "(\n" + body.String() + ")"
}

// pyRepeated reports whether a field carries many values. A map carries the
// repeated label the same way a list does, which is what Python's is_repeated
// answers.
func pyRepeated(entry protoreflect.FieldDescriptor) bool {
	return entry.Cardinality() == protoreflect.Repeated
}

// pyMessageOf is the message a field carries, nil for a field holding a value.
func pyMessageOf(entry protoreflect.FieldDescriptor) protoreflect.MessageDescriptor {
	if entry.Kind() != protoreflect.MessageKind && entry.Kind() != protoreflect.GroupKind {
		return nil
	}

	return entry.Message()
}
