package main_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"testing"
)

// The tree `make proto` writes, and the formatter the arm renders through. Both
// are relative to this package directory because go test runs with that as cwd.
const (
	pythonPackageDir = "../../../python/src/linodemcp/gentools"
	pythonRuff       = "../../../python/.venv/bin/ruff"
)

// The emitter the tree names. One run of go/cmd/toolgen writes both
// languages, so the header a reader follows has to lead there.
const pythonGeneratedHeader = "# Code generated by go/cmd/toolgen. DO NOT EDIT."

// runPythonGen renders the Python tree into a temp directory.
func runPythonGen(t *testing.T) string {
	t.Helper()

	return runPythonGenInto(t, t.TempDir())
}

// runPythonGenInto renders the Python tree into a caller-owned directory, for
// the cases whose subject is what a run does to the directory it writes.
func runPythonGenInto(t *testing.T, out string) string {
	t.Helper()

	cmd := exec.CommandContext(t.Context(), "go", "run", ".",
		"-languages", writeLanguages(t, "python"),
		"-handwritten", handwrittenFile,
		"-schemas", schemaDir, "-python-out", out,
		"-python-answers-out", t.TempDir(), "-ruff", pythonRuff)

	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("toolgen failed: %v\n%s", err, output)
	}

	return out
}

// The whole acceptance of the Python arm: what it renders is what the shipped
// tree holds, byte for byte. `make proto` wrote that tree through this same
// arm, so a difference means the emitted bytes depend on something other than
// the contract. Every other case below pins one shape so a failure says which
// one moved, but this is the one that would catch a shape nobody pinned.
func TestPythonRendererMatchesTheEmittedTree(t *testing.T) {
	t.Parallel()

	dir := runPythonGen(t)

	rendered := pythonFiles(t, dir)
	if len(rendered) == 0 {
		t.Fatal("rendered no Python files, so this measured nothing")
	}

	if shipped := pythonFiles(t, pythonPackageDir); !slices.Equal(rendered, shipped) {
		t.Fatalf("rendered %v, and the emitted tree holds %v", rendered, shipped)
	}

	for _, name := range rendered {
		if readGenerated(t, dir, name) != readGenerated(t, pythonPackageDir, name) {
			t.Errorf("%s differs from the emitted tree", name)
		}
	}
}

// A module the cohort no longer produces leaves with it, and nothing else in
// the directory does. A factory left behind would keep registering a tool the
// contract stopped describing, and the tree is gitignored, so nothing else
// would notice.
func TestWrittenPythonTreeDropsAStaleModule(t *testing.T) {
	t.Parallel()

	out := t.TempDir()
	stale := filepath.Join(out, "old.py")
	kept := filepath.Join(out, "notes.txt")

	for _, path := range []string{stale, kept} {
		if err := os.WriteFile(path, []byte("# left over\n"), 0o600); err != nil {
			t.Fatalf("plant %s: %v", path, err)
		}
	}

	runPythonGenInto(t, out)

	if _, err := os.Stat(stale); !os.IsNotExist(err) {
		t.Error("a stale module survived the run that stopped producing it")
	}

	if _, err := os.Stat(kept); err != nil {
		t.Errorf("the run removed a file no renderer owns: %v", err)
	}

	if !strings.Contains(readGenerated(t, out, "__init__.py"), "__all__") {
		t.Error("the registry the run wrote does not export the cohort")
	}
}

func TestEveryEmittedPythonFileCarriesTheGeneratedHeader(t *testing.T) {
	t.Parallel()

	dir := runPythonGen(t)

	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read emitted tree: %v", err)
	}

	if len(entries) == 0 {
		t.Fatal("emitted tree is empty")
	}

	for _, entry := range entries {
		source := readGenerated(t, dir, entry.Name())
		if !strings.HasPrefix(source, pythonGeneratedHeader) {
			t.Errorf("%s does not open with the generated-by header", entry.Name())
		}
	}
}

// A factory nothing registers passes every gate that reads the contract and is
// still missing from the running server, so the registry is held to naming both
// halves of every tool the run emitted.
func TestPythonRegistryNamesBothHalvesOfEveryEmittedTool(t *testing.T) {
	t.Parallel()

	dir := runPythonGen(t)
	registry := readGenerated(t, dir, "__init__.py")

	var factories int

	for _, name := range pythonModules(t, dir) {
		for _, tool := range pythonToolNames(readGenerated(t, dir, name)) {
			factories++

			for _, want := range []string{
				"    create_" + tool + "_tool,", `    "create_` + tool + `_tool",`,
				"    handle_" + tool + ",", `    "handle_` + tool + `",`,
			} {
				if !strings.Contains(registry, want) {
					t.Errorf("registry is missing %q", want)
				}
			}
		}
	}

	if factories == 0 {
		t.Fatal("found no emitted factories, so this measured nothing")
	}
}

// No tool names a hand-written body any more, so the generated tree reaches
// none, and an import that comes back is held to a call the way it always was. The population this counts is the modules rather than the
// imports, because the imports are meant to be none and a guard on an empty
// set would fail on the state the migration was for.
func TestThePythonTreeReachesNoHandWrittenBody(t *testing.T) {
	t.Parallel()

	dir := runPythonGen(t)
	modules := pythonModules(t, dir)

	for _, name := range modules {
		source := readGenerated(t, dir, name)

		for _, body := range pythonHandWrittenImports(source) {
			t.Errorf("%s imports the hand-written %s", name, body)

			if strings.Count(source, body) < 2 {
				t.Errorf("%s imports %s and never calls it", name, body)
			}
		}
	}

	if len(modules) == 0 {
		t.Fatal("found no emitted modules, so this measured nothing")
	}
}

// Every handler answers the contract's own rules before it reads anything else,
// which is what keeps a refused argument from reaching a route.
func TestEveryPythonHandlerChecksTheContractRules(t *testing.T) {
	t.Parallel()

	dir := runPythonGen(t)

	var handlers int

	for _, name := range pythonModules(t, dir) {
		for _, handler := range pythonHandlers(readGenerated(t, dir, name)) {
			handlers++

			if !strings.Contains(handler, "check_constraints(") {
				t.Errorf("a handler in %s reads its arguments without the contract rules:\n%s",
					name, handler)
			}
		}
	}

	if handlers == 0 {
		t.Fatal("found no handlers, so this measured nothing")
	}
}

// A routeless tool lands on the meta tier and nowhere else: it answers the
// sentence its contract declares over the argument the template names, with the
// default that template carries, and takes no configuration to do it.
func TestEmitsThePythonMetaShellForARoutelessTool(t *testing.T) {
	t.Parallel()

	source := readGenerated(t, runPythonGen(t), "version.py")

	for _, want := range []string{
		"def create_hello_tool() -> tuple[Tool, Capability]:",
		"    ), Capability.Meta",
		"    Answers from local state and reaches no Linode route.",
		"async def handle_hello(arguments: dict[str, Any], _cfg: Config) -> list[TextContent]:",
		"from linodemcp.tools.argreader import tool_string",
		`    name = tool_string(arguments, "name", "World")`,
		"    return meta_response(",
		`        "linode.mcp.v1.HelloResponse",`,
	} {
		if !strings.Contains(source, want) {
			t.Errorf("emitted meta tool is missing %q:\n%s", want, source)
		}
	}
}

// A removal notes a missing id rather than answering it: when that sentence
// surfaces is the driver's job and differs by branch, ahead of a plan and
// behind the confirm gate on a live call.
func TestEmitsThePythonDestroyConfiguration(t *testing.T) {
	t.Parallel()

	source := readGenerated(t, runPythonGen(t), "domain.py")

	for _, want := range []string{
		`    domain_id, domain_id_error = destroy_id(arguments, "domain_id")`,
		"    async def fetch_state(client: RetryableClient) -> Any:",
		"    return await run_destructive_tool(",
		`        error_action="",`,
		"        fetch_state=fetch_state,",
		"        error=error,",
	} {
		if !strings.Contains(source, want) {
			t.Errorf("emitted removal is missing %q:\n%s", want, source)
		}
	}

	if strings.Contains(source, "return error_response(domain_id_error)") {
		t.Error("a removal answers its missing-id sentence where it reads it")
	}
}

// The shapes ruff 0.16.4 refuses when rendered any other way: a lone-slot
// guard folds instead of nesting, a split wording in a collection carries
// parentheses, an unread closure parameter carries the underscore, and a
// from-import lists constants first. Pinned here so a regression names the
// shape that moved rather than surfacing as a lint failure gates away.
func TestEmitsThePythonShapesTheLinterHoldsTo(t *testing.T) {
	t.Parallel()

	dir := runPythonGen(t)

	for name, want := range map[string]string{
		"vpc.py":       `    if not message and not arguments.get("vpc_id"):`,
		"placement.py": "    if not error and group_id_error:",
		"instance.py":  "    async def dependency_walk(_client: RetryableClient, state: Any)",
		"volume.py":    "    def preview_cautions(_state: Any) -> tuple[str, ...]:",
		"firewall.py":  "from linodemcp.tools.body import ITEM_STR, FoldMember, WriteBody",
		"account.py": "        warnings=(\n            (\n" +
			`                "Account cancellation is permanent`,
	} {
		if !strings.Contains(readGenerated(t, dir, name), want) {
			t.Errorf("%s is missing the linted shape %q", name, want)
		}
	}
}

// pythonFiles is every Python file a tree holds, sorted, the interpreter's
// caches left out.
func pythonFiles(t *testing.T, dir string) []string {
	t.Helper()

	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read emitted tree: %v", err)
	}

	found := make([]string, 0, len(entries))

	for _, entry := range entries {
		if !entry.IsDir() && filepath.Ext(entry.Name()) == ".py" {
			found = append(found, entry.Name())
		}
	}

	sort.Strings(found)

	return found
}

// pythonModules is every emitted module, the registry left out.
func pythonModules(t *testing.T, dir string) []string {
	t.Helper()

	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read emitted tree: %v", err)
	}

	found := make([]string, 0, len(entries))

	for _, entry := range entries {
		if entry.Name() != "__init__.py" && filepath.Ext(entry.Name()) == ".py" {
			found = append(found, entry.Name())
		}
	}

	return found
}

// pythonToolNames is every tool one emitted module declares a factory for.
func pythonToolNames(source string) []string {
	blocks := strings.Split(source, "\ndef create_")[1:]
	found := make([]string, 0, len(blocks))

	for _, block := range blocks {
		if name, _, cut := strings.Cut(block, "_tool() -> tuple[Tool, Capability]:"); cut {
			found = append(found, name)
		}
	}

	return found
}

// pythonHandWrittenImports is the per-tool bodies one emitted module imports.
// Each would be spelled `from linodemcp.tools.<tool> import <tool>_answer` on a
// line of its own, since such a body lived beside the tool it served.
func pythonHandWrittenImports(source string) []string {
	imports := make([]string, 0)

	for line := range strings.SplitSeq(source, "\n") {
		rest, found := strings.CutPrefix(line, "from linodemcp.tools.")
		if !found {
			continue
		}

		module, name, imported := strings.Cut(rest, " import ")
		if imported && strings.TrimSpace(name) == module+"_answer" {
			imports = append(imports, strings.TrimSpace(name))
		}
	}

	return imports
}

// pythonHandlers is every emitted handler body one module declares.
func pythonHandlers(source string) []string {
	blocks := strings.Split(source, "\nasync def handle_")[1:]
	found := make([]string, 0, len(blocks))

	for _, block := range blocks {
		body, _, _ := strings.Cut(block, "\n\n\ndef ")
		found = append(found, body)
	}

	return found
}
