// Code generated by audit test cleanup; DO NOT EDIT.

package audit_test

import (
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"os"
	"reflect"
	"strings"
	"testing"
)

func helperMessage(args []any) string {
	if len(args) == 0 {
		return ""
	}

	format, ok := args[0].(string)
	if ok {
		return ": " + fmt.Sprintf(format, args[1:]...)
	}

	return ": " + fmt.Sprint(args...)
}

func fail(tb testing.TB, msg string, args ...any) {
	tb.Helper()

	tb.Fatalf("%s%s", msg, helperMessage(args))
}

func checkEqual(tb testing.TB, expected, actual any, args ...any) bool {
	tb.Helper()

	if !reflect.DeepEqual(expected, actual) {
		tb.Errorf("expected %v, got %v%s", expected, actual, helperMessage(args))

		return false
	}

	return true
}

func mustEqual(tb testing.TB, expected, actual any, args ...any) {
	tb.Helper()

	if !checkEqual(tb, expected, actual, args...) {
		tb.FailNow()
	}
}

func checkLen(tb testing.TB, actual any, expected int, args ...any) bool {
	tb.Helper()

	actualValue := reflect.ValueOf(actual)
	if !actualValue.IsValid() {
		tb.Errorf("expected length %d, got invalid value%s", expected, helperMessage(args))

		return false
	}

	actualLength := actualValue.Len()
	if actualLength != expected {
		tb.Errorf("expected length %d, got %d%s", expected, actualLength, helperMessage(args))

		return false
	}

	return true
}

func mustLen(tb testing.TB, actual any, expected int, args ...any) {
	tb.Helper()

	if !checkLen(tb, actual, expected, args...) {
		tb.FailNow()
	}
}

func isEmpty(value any) bool {
	if value == nil {
		return true
	}

	actualValue := reflect.ValueOf(value)
	switch actualValue.Kind() {
	case reflect.Array, reflect.Chan, reflect.Map, reflect.Slice, reflect.String:
		return actualValue.Len() == 0
	case reflect.Bool:
		return !actualValue.Bool()
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return actualValue.Int() == 0
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return actualValue.Uint() == 0
	case reflect.Float32, reflect.Float64:
		return actualValue.Float() == 0
	default:
		zero := reflect.Zero(actualValue.Type()).Interface()

		return reflect.DeepEqual(value, zero)
	}
}

func isNil(value any) bool {
	if value == nil {
		return true
	}

	actualValue := reflect.ValueOf(value)
	switch actualValue.Kind() {
	case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice:
		return actualValue.IsNil()
	default:
		return false
	}
}

func checkTrue(tb testing.TB, actual bool, args ...any) bool {
	tb.Helper()

	if !actual {
		tb.Errorf("expected true%s", helperMessage(args))

		return false
	}

	return true
}

func mustTrue(tb testing.TB, actual bool, args ...any) {
	tb.Helper()

	if !checkTrue(tb, actual, args...) {
		tb.FailNow()
	}
}

func checkFalse(tb testing.TB, actual bool, args ...any) bool {
	tb.Helper()

	if actual {
		tb.Errorf("expected false%s", helperMessage(args))

		return false
	}

	return true
}

func checkNil(tb testing.TB, actual any, args ...any) bool {
	tb.Helper()

	if !isNil(actual) {
		tb.Errorf("expected nil, got %v%s", actual, helperMessage(args))

		return false
	}

	return true
}

func checkNotNil(tb testing.TB, actual any, args ...any) bool {
	tb.Helper()

	if isNil(actual) {
		tb.Errorf("expected non-nil value%s", helperMessage(args))

		return false
	}

	return true
}

func mustNotNil(tb testing.TB, actual any, args ...any) {
	tb.Helper()

	if !checkNotNil(tb, actual, args...) {
		tb.FailNow()
	}
}

func checkEmpty(tb testing.TB, actual any, args ...any) bool {
	tb.Helper()

	if !isEmpty(actual) {
		tb.Errorf("expected empty value, got %v%s", actual, helperMessage(args))

		return false
	}

	return true
}

func checkZero(tb testing.TB, actual any, args ...any) bool {
	tb.Helper()

	return checkEmpty(tb, actual, args...)
}

func checkNotZero(tb testing.TB, actual any, args ...any) bool {
	tb.Helper()

	if isEmpty(actual) {
		tb.Errorf("expected non-zero value%s", helperMessage(args))

		return false
	}

	return true
}

func checkPositive(tb testing.TB, actual any, args ...any) bool {
	tb.Helper()

	actualValue := reflect.ValueOf(actual)
	isPositive := false
	switch actualValue.Kind() {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		isPositive = actualValue.Int() > 0
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		isPositive = actualValue.Uint() > 0
	case reflect.Float32, reflect.Float64:
		isPositive = actualValue.Float() > 0
	default:
		isPositive = false
	}

	if !isPositive {
		tb.Errorf("expected positive value, got %v%s", actual, helperMessage(args))
	}

	return isPositive
}

func checkNoFileExists(tb testing.TB, path string, args ...any) bool {
	tb.Helper()

	_, err := os.Stat(path)
	if err == nil {
		tb.Errorf("expected file not to exist: %s%s", path, helperMessage(args))

		return false
	}

	if !errors.Is(err, os.ErrNotExist) {
		tb.Errorf("stat %s: %v%s", path, err, helperMessage(args))

		return false
	}

	return true
}

func checkFileExists(tb testing.TB, path string, args ...any) bool {
	tb.Helper()

	if _, err := os.Stat(path); err != nil {
		tb.Errorf("expected file to exist: %s: %v%s", path, err, helperMessage(args))

		return false
	}

	return true
}

func checkIsType(tb testing.TB, expected, actual any, args ...any) bool {
	tb.Helper()

	if reflect.TypeOf(expected) != reflect.TypeOf(actual) {
		tb.Errorf("expected type %T, got %T%s", expected, actual, helperMessage(args))

		return false
	}

	return true
}

func checkNotEqual(tb testing.TB, expected, actual any, args ...any) bool {
	tb.Helper()

	if reflect.DeepEqual(expected, actual) {
		tb.Errorf("expected values to differ, both were %v%s", actual, helperMessage(args))

		return false
	}

	return true
}

func contains(container, item any) bool {
	if text, ok := container.(string); ok {
		if substring, ok := item.(string); ok {
			return strings.Contains(text, substring)
		}
	}

	containerValue := reflect.ValueOf(container)
	switch containerValue.Kind() {
	case reflect.Map:
		return containerValue.MapIndex(reflect.ValueOf(item)).IsValid()
	case reflect.Slice, reflect.Array:
		for index := range containerValue.Len() {
			if reflect.DeepEqual(containerValue.Index(index).Interface(), item) {
				return true
			}
		}
	default:
		return false
	}

	return false
}

func checkContains(tb testing.TB, container, item any, args ...any) bool {
	tb.Helper()

	if !contains(container, item) {
		tb.Errorf("expected %v to contain %v%s", container, item, helperMessage(args))

		return false
	}

	return true
}

func checkNotContains(tb testing.TB, container, item any, args ...any) bool {
	tb.Helper()

	if contains(container, item) {
		tb.Errorf("expected %v not to contain %v%s", container, item, helperMessage(args))

		return false
	}

	return true
}

func checkErrorIs(tb testing.TB, err, target error, args ...any) bool {
	tb.Helper()

	if !errors.Is(err, target) {
		tb.Errorf("expected error %v to match %v%s", err, target, helperMessage(args))

		return false
	}

	return true
}

func mustErrorIs(tb testing.TB, err, target error, args ...any) {
	tb.Helper()

	if !checkErrorIs(tb, err, target, args...) {
		tb.FailNow()
	}
}

func mustNoError(tb testing.TB, err error, args ...any) {
	tb.Helper()

	if err != nil {
		fail(tb, fmt.Sprintf("unexpected error: %v", err), args...)
	}
}

func mustError(tb testing.TB, err error, args ...any) {
	tb.Helper()

	if err == nil {
		fail(tb, "expected error", args...)
	}
}

func mustNotPanics(tb testing.TB, fn func(), args ...any) {
	tb.Helper()

	defer func() {
		if recovered := recover(); recovered != nil {
			fail(tb, fmt.Sprintf("unexpected panic: %v", recovered), args...)
		}
	}()

	fn()
}

func toFloat64(value any) (float64, bool) {
	actualValue := reflect.ValueOf(value)
	switch actualValue.Kind() {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return float64(actualValue.Int()), true
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return float64(actualValue.Uint()), true
	case reflect.Float32, reflect.Float64:
		return actualValue.Convert(reflect.TypeFor[float64]()).Float(), true
	default:
		return 0, false
	}
}

func checkInDelta(tb testing.TB, expected, actual, delta any, args ...any) bool {
	tb.Helper()

	expectedFloat, expectedOK := toFloat64(expected)
	actualFloat, actualOK := toFloat64(actual)
	deltaFloat, deltaOK := toFloat64(delta)

	if !expectedOK || !actualOK || !deltaOK {
		tb.Errorf("expected numeric values for InDelta, got %T, %T, %T%s", expected, actual, delta, helperMessage(args))

		return false
	}

	if math.Abs(expectedFloat-actualFloat) > deltaFloat {
		tb.Errorf("expected %v and %v to be within %v%s", expected, actual, delta, helperMessage(args))

		return false
	}

	return true
}

func checkElementsMatch(tb testing.TB, expected, actual any, args ...any) bool {
	tb.Helper()

	expectedValue := reflect.ValueOf(expected)
	actualValue := reflect.ValueOf(actual)

	if expectedValue.Kind() != reflect.Slice || actualValue.Kind() != reflect.Slice || expectedValue.Len() != actualValue.Len() {
		tb.Errorf("expected matching slices, got %v and %v%s", expected, actual, helperMessage(args))

		return false
	}

	used := make([]bool, actualValue.Len())
	for expectedIndex := range expectedValue.Len() {
		found := false
		for actualIndex := range actualValue.Len() {
			if used[actualIndex] || !reflect.DeepEqual(expectedValue.Index(expectedIndex).Interface(), actualValue.Index(actualIndex).Interface()) {
				continue
			}

			used[actualIndex] = true
			found = true

			break
		}

		if !found {
			tb.Errorf("expected matching slices, got %v and %v%s", expected, actual, helperMessage(args))

			return false
		}
	}

	return true
}

func checkJSONEq(tb testing.TB, expected, actual string, args ...any) bool {
	tb.Helper()

	var expectedJSON any
	if err := json.Unmarshal([]byte(expected), &expectedJSON); err != nil {
		tb.Errorf("invalid expected JSON: %v%s", err, helperMessage(args))

		return false
	}

	var actualJSON any
	if err := json.Unmarshal([]byte(actual), &actualJSON); err != nil {
		tb.Errorf("invalid actual JSON: %v%s", err, helperMessage(args))

		return false
	}

	return checkEqual(tb, expectedJSON, actualJSON, args...)
}
