"""Offline tests for the dependency-refresh target.

update_deps.py rewrites the four surfaces that carry a declared version. These
tests pin the decisions that would be expensive to get wrong: which directories
count as a project, which pins are refused and why, and what a rewritten action
pin looks like. Nothing here reaches the network. The action tests replace the
tag lookup with a fixed map, and every other test either builds a small tree or
reads the real one.

The buf assertions are the load-bearing ones. Its version decides the bytes
`make proto` writes, so a run that proposed a bump would invalidate every
committed baseline at once.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from typing import TYPE_CHECKING

import pytest

if TYPE_CHECKING:
    from types import ModuleType

REPO_ROOT = Path(__file__).resolve().parents[3]
SCRIPTS_DIR = REPO_ROOT / "scripts"

OLD_SHA = "1111111111111111111111111111111111111111"
NEW_SHA = "2222222222222222222222222222222222222222"
PATCH_SHA = "3333333333333333333333333333333333333333"

CHECKOUT = "actions/checkout"
SLSA = "slsa-framework/slsa-github-generator"
SLSA_WORKFLOW = f"{SLSA}/.github/workflows/generator_generic_slsa3.yml"


def _load_script(name: str) -> ModuleType:
    if str(SCRIPTS_DIR) not in sys.path:
        sys.path.insert(0, str(SCRIPTS_DIR))
    spec = importlib.util.spec_from_file_location(name, SCRIPTS_DIR / f"{name}.py")
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    # @dataclass resolves field annotations through sys.modules[cls.__module__],
    # which is absent for a module loaded straight from a spec.
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


target = _load_script("update_deps")


def _fixed_tags(monkeypatch: pytest.MonkeyPatch, tags: dict[str, str]) -> None:
    """Replace the remote tag lookup, so no test reaches the network."""

    def lookup(_slug: str, _cache: dict[str, dict[str, str]]) -> dict[str, str]:
        return tags

    monkeypatch.setattr(target, "_remote_tags", lookup)


# --- The buf pin, which every byte-identity control in the repo rests on ---


def test_the_live_plan_refuses_buf_by_name_and_says_why() -> None:
    """A proposed buf bump would move every generated baseline at once."""
    changes = target.plan_tools(target.provisioning_files(), target.codegen_templates())
    buf = [change for change in changes if change.what.endswith("/buf")]

    assert [change.action for change in buf] == [target._REFUSE]
    assert buf[0].current == "v1.71.0"
    assert "byte-reproducible" in buf[0].note


def test_no_live_tool_change_proposes_moving_anything_named_buf() -> None:
    """The refusal is only worth something if no other arm updates it."""
    changes = target.plan_tools(target.provisioning_files(), target.codegen_templates())
    moving = [
        change.what
        for change in changes
        if change.action == target._UPDATE and "buf" in change.what
    ]

    assert moving == []


def test_the_live_plan_refuses_every_remote_codegen_plugin() -> None:
    """The plugin tags decide generated bytes the same way the buf pin does."""
    changes = target.plan_tools([], target.codegen_templates())
    refused = {change.what for change in changes if change.action == target._REFUSE}

    assert refused == {
        "buf.build/protocolbuffers/go",
        "buf.build/protocolbuffers/python",
        "buf.build/protocolbuffers/pyi",
    }


def test_the_live_python_plan_refuses_the_codegen_coupled_floors() -> None:
    """protobuf tracks the plugin tags and protovalidate supplies the messages."""
    changes = target.plan_python(target.uv_projects())
    refused = {change.what for change in changes if change.action == target._REFUSE}

    assert refused == {"protobuf", "protovalidate"}


# --- Discovery, which decides whether the run measured anything ---


def test_the_live_tree_carries_two_uv_projects_and_one_go_module() -> None:
    """Missing the second uv project is the easy failure on this surface."""
    assert [path.name for path in target.uv_projects()] == [
        "python",
        "techdocs-proof",
    ]
    assert [path.name for path in target.go_modules()] == ["go"]


def test_a_directory_counts_as_a_uv_project_only_with_a_lock_beside_it(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A pyproject alone is a declaration, not a locked project."""
    registry = tmp_path / "languages.txt"
    registry.write_text("# header\npython\tpython\tdump\n", encoding="utf-8")
    (tmp_path / "python").mkdir()
    (tmp_path / "python" / "pyproject.toml").write_text("", encoding="utf-8")
    tools = tmp_path / "tools"
    (tools / "proof").mkdir(parents=True)
    (tools / "proof" / "pyproject.toml").write_text("", encoding="utf-8")
    (tools / "proof" / "uv.lock").write_text("", encoding="utf-8")
    monkeypatch.setattr(target, "_ROOT", tmp_path)
    monkeypatch.setattr(target, "_LANGUAGES", registry)
    monkeypatch.setattr(target, "_TOOLS", tools)

    assert target.uv_projects() == [tools / "proof"]


def test_a_discovery_that_finds_nothing_fails_instead_of_reporting_clean(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A run that updated nothing because discovery broke is not a clean run."""
    monkeypatch.setattr(target, "go_modules", list)
    monkeypatch.setattr(sys, "argv", ["update_deps.py", "--dry-run"])

    with pytest.raises(SystemExit, match="covered nothing"):
        target.main()


# --- Tool pins ---


def test_prose_naming_an_install_command_is_not_a_call_site(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Both file kinds comment, and a Makefile recipe hides behind a leading @."""
    script = tmp_path / "ci-setup.sh"
    script.write_text(
        "# `go install example.com/prose@v9.9.9` in a sentence\n"
        "\t@# go run example.com/recipe@v8.8.8\n"
        "\tgo install mvdan.cc/gofumpt@latest\n",
        encoding="utf-8",
    )
    monkeypatch.setattr(target, "_ROOT", tmp_path)

    changes = target._pin_changes(script)

    assert [change.what for change in changes] == ["mvdan.cc/gofumpt"]
    assert changes[0].action == target._FLOAT


def test_a_written_down_version_with_no_resolver_is_reported_not_skipped(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A new hand-pinned tool must be loud rather than silently left behind."""
    script = tmp_path / "ci-setup.sh"
    script.write_text("go install example.com/tool@v1.2.3\n", encoding="utf-8")
    monkeypatch.setattr(target, "_ROOT", tmp_path)

    changes = target._pin_changes(script)

    assert [change.action for change in changes] == [target._UNKNOWN]


def test_a_version_the_target_cannot_move_fails_the_run(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    """The finding has to reach the exit code, not just the report."""
    unmovable = target.Change(
        where="scripts/ci-setup.sh",
        what="example.com/tool",
        current="v1.2.3",
        action=target._UNKNOWN,
        note=target._ODD_PIN_NOTE,
    )

    def one_finding(*_args: object) -> list[object]:
        return [unmovable]

    monkeypatch.setattr(target, "plan_tools", one_finding)
    monkeypatch.setattr(sys, "argv", ["update_deps.py", "--dry-run"])

    assert target.main() == 1
    assert "example.com/tool" in capsys.readouterr().out


# --- Shapes the parsed files are trusted to have ---


def test_a_string_where_a_list_belongs_is_dropped_rather_than_iterated() -> None:
    """`set.update` on a bare string adds its characters, one per letter.

    That is the quiet failure this guard exists for. A `matchDepNames` written
    as a string would have widened the digest exclusion into single letters,
    and the SLSA workflows would have started collecting digests they refuse.
    """
    assert target._strings(SLSA) == []
    assert target._strings(["a", 1, "b"]) == ["a", "b"]
    assert target._strings(None) == []


def test_a_lock_entry_that_is_not_a_table_never_reaches_the_version_map(
    tmp_path: Path,
) -> None:
    """`"name" in entry` on a string is a substring test, not a key test."""
    (tmp_path / "uv.lock").write_text(
        "package = [\n"
        '  "name-and-version-in-one-string",\n'
        '  { name = "Types_PyYAML", version = "6.0.2" },\n'
        '  { name = "no-version-here" },\n'
        "]\n",
        encoding="utf-8",
    )

    assert target._locked_versions(tmp_path) == {"types-pyyaml": "6.0.2"}


def test_a_pyproject_whose_dependencies_are_not_a_list_yields_nothing(
    tmp_path: Path,
) -> None:
    """Splitting a requirement string into characters is worse than no answer."""
    (tmp_path / "pyproject.toml").write_text(
        '[project]\ndependencies = "httpx>=0.28.1"\n', encoding="utf-8"
    )

    assert target._declared_requirements(tmp_path) == []


def test_optional_dependency_groups_are_read_alongside_the_main_list(
    tmp_path: Path,
) -> None:
    """Every extra counts, which is where ruff, mypy and the otel deps live."""
    (tmp_path / "pyproject.toml").write_text(
        "[project]\n"
        'dependencies = ["httpx>=0.28.1"]\n'
        "[project.optional-dependencies]\n"
        'dev = ["ruff>=0.16.1"]\n'
        'observability = ["prometheus-client>=0.26.0"]\n',
        encoding="utf-8",
    )

    assert target._declared_requirements(tmp_path) == [
        "httpx>=0.28.1",
        "ruff>=0.16.1",
        "prometheus-client>=0.26.0",
    ]


# --- Python floors ---


def test_a_bare_floor_rises_while_a_ceiling_or_exact_pin_stays_put() -> None:
    """Renovate's bump strategy moves a floor; the rest is a human decision."""
    text = (
        "dependencies = [\n"
        '    "httpx>=0.28.1",\n'
        '    "mcp>=2.0.0,<3.0",\n'
        '    "protovalidate==1.2.0",\n'
        "]\n"
    )
    wanted = {"httpx": "0.29.0", "mcp": "2.5.0", "protovalidate": "1.3.0"}

    rewritten, moved = target._rewrite_floors(text, wanted)

    assert '"httpx>=0.29.0",' in rewritten
    assert '"mcp>=2.0.0,<3.0",' in rewritten
    assert '"protovalidate==1.2.0",' in rewritten
    assert moved == ["httpx 0.28.1 -> 0.29.0"]


def test_a_floor_already_at_the_locked_version_is_left_alone() -> None:
    """Rewriting a line to itself would report a move nobody made."""
    text = 'dependencies = [\n    "httpx>=0.29.0",\n]\n'

    rewritten, moved = target._rewrite_floors(text, {"httpx": "0.29.0"})

    assert rewritten == text
    assert moved == []


def test_a_requirement_name_is_matched_after_normalizing_it() -> None:
    """uv.lock writes types-pyyaml where the pyproject writes types-PyYAML."""
    text = 'dependencies = [\n    "types-PyYAML>=6.0.1",\n]\n'

    rewritten, moved = target._rewrite_floors(text, {"types-pyyaml": "6.0.2"})

    assert '"types-PyYAML>=6.0.2",' in rewritten
    assert moved == ["types-PyYAML 6.0.1 -> 6.0.2"]


# --- Action pins ---


def test_a_digest_pin_moves_its_sha_and_its_comment_together(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Half a rewrite leaves the pin naming one version and running another."""
    _fixed_tags(monkeypatch, {"v7": OLD_SHA, "v8": NEW_SHA})
    line = f"      - uses: {CHECKOUT}@{OLD_SHA} # v7\n"

    rewritten, moved = target._bump_use(line, set(), {})

    assert rewritten == f"      - uses: {CHECKOUT}@{NEW_SHA} # v8\n"
    assert moved == [f"{CHECKOUT} v7 -> v8"]


def test_a_pin_stays_at_the_granularity_its_comment_is_written_with(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Tracking v7 means the newest v-major tag, not the newest tag of any shape."""
    _fixed_tags(
        monkeypatch,
        {"v7": OLD_SHA, "v8": NEW_SHA, "v8.1.2": PATCH_SHA, "nightly": PATCH_SHA},
    )
    line = f"      - uses: {CHECKOUT}@{OLD_SHA} # v7\n"

    rewritten, _ = target._bump_use(line, set(), {})

    assert rewritten == f"      - uses: {CHECKOUT}@{NEW_SHA} # v8\n"


def test_an_excluded_reusable_workflow_moves_its_tag_and_gains_no_digest(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """SLSA verifies its own ref and fails when that ref is a digest."""
    _fixed_tags(monkeypatch, {"v2.1.0": OLD_SHA, "v2.2.0": NEW_SHA})
    line = f"    uses: {SLSA_WORKFLOW}@v2.1.0\n"

    rewritten, moved = target._bump_use(line, {SLSA}, {})

    assert rewritten == f"    uses: {SLSA_WORKFLOW}@v2.2.0\n"
    assert NEW_SHA not in rewritten
    assert moved == [f"{SLSA} v2.1.0 -> v2.2.0"]


def test_a_pin_already_at_the_newest_tag_is_left_untouched(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """An unchanged line must not be reported as a move."""
    _fixed_tags(monkeypatch, {"v7": OLD_SHA})
    line = f"      - uses: {CHECKOUT}@{OLD_SHA} # v7\n"

    rewritten, moved = target._bump_use(line, set(), {})

    assert rewritten == line
    assert moved == []


def test_the_tag_only_exclusion_is_read_from_renovate_json() -> None:
    """One declaration of the SLSA rule serves both updaters."""
    assert SLSA in target.no_digest_deps()


def test_a_local_workflow_reference_carries_no_version_to_move() -> None:
    """A path in this repository is not a dependency."""
    change = target._action_change("w.yml", "./.github/workflows/x.yml", set())

    assert change.action == target._HOLD


def test_a_pin_whose_comment_is_not_a_version_is_reported() -> None:
    """The comment is the tracked ref, so an unreadable one has to be loud."""
    change = target._action_change("w.yml", f"{CHECKOUT}@{OLD_SHA} # nightly", set())

    assert change.action == target._UNKNOWN


# --- The whole plan, offline ---


def test_the_live_dry_run_plans_every_surface_and_writes_nothing(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    """The offline plan is what makes the target reviewable before it writes."""
    monkeypatch.setattr(sys, "argv", ["update_deps.py", "--dry-run"])

    assert target.main() == 0

    printed = capsys.readouterr().out
    for surface in (
        "go modules",
        "python dependencies",
        "tool versions",
        "github actions",
    ):
        assert surface in printed
    assert "nothing was written" in printed
