#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

mkdir -p "$tmpdir/bin" "$tmpdir/repo/go" "$tmpdir/repo/python" "$tmpdir/repo/scripts"
cat >"$tmpdir/bin/pre-commit" <<'STUB'
#!/usr/bin/env bash
set -euo pipefail
if [ "$#" -lt 1 ] || [ "$1" != "install" ]; then
  echo "unexpected pre-commit invocation: $*" >&2
  exit 64
fi
hook_type="pre-commit"
while [ "$#" -gt 0 ]; do
  case "$1" in
    --hook-type)
      hook_type="$2"
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done
hook_path="$(git rev-parse --git-path "hooks/${hook_type}")"
mkdir -p "$(dirname "$hook_path")"
printf '#!/usr/bin/env bash
# generated by pre-commit
' >"$hook_path"
chmod +x "$hook_path"
STUB
chmod +x "$tmpdir/bin/pre-commit"

cp "$repo_root/Makefile" "$tmpdir/repo/Makefile"
cp "$repo_root/go/Makefile" "$tmpdir/repo/go/Makefile"
cp "$repo_root/python/Makefile" "$tmpdir/repo/python/Makefile"
cp "$repo_root/scripts/git-hooks.sh" "$tmpdir/repo/scripts/git-hooks.sh"
chmod +x "$tmpdir/repo/scripts/git-hooks.sh"

cd "$tmpdir/repo"
git init -q
PATH="$tmpdir/bin:$PATH" make -C go _ensure-hooks >/tmp/linodemcp-go-hooks-test.log
PATH="$tmpdir/bin:$PATH" make check-hooks
rm -f "$(git rev-parse --git-path hooks/pre-push)"
if PATH="$tmpdir/bin:$PATH" make check-hooks >/tmp/linodemcp-hook-check.log 2>&1; then
	echo "expected make check-hooks to fail when pre-push hook is missing" >&2
	exit 1
fi
PATH="$tmpdir/bin:$PATH" make -C python _ensure-hooks >/tmp/linodemcp-python-hooks-test.log
PATH="$tmpdir/bin:$PATH" make check-hooks

grep -q 'pre-commit' "$(git rev-parse --git-path hooks/pre-commit)"
grep -q 'pre-commit' "$(git rev-parse --git-path hooks/pre-push)"
