#!/usr/bin/env python3
"""Emit the Python MCP tool factories and handlers the proto contract describes.

This is the Python half of the tool generator; go/cmd/toolgen is the Go half,
and both read the same compiled descriptors for the cohort in
docs/contracts/generated-tools.txt. A tool's route, tier, response message,
argument locations, filters, and prose all live on its *Input message, so
emitting the factory keeps the contract the only place those facts are written.

Each emitted handler names its tool and hands its validated path values to the
drivers in linodemcp.tools.drivers, which read everything else back out of the
contract at runtime.

The output tree is gitignored and rewritten whole on every run, the same way
linodemcp/genpb is: a stale module left behind by a removed cohort entry would
keep registering a tool long after its contract went away.

Reading descriptors needs the protobuf runtime and the generated modules, so
this resolves through python/.venv/bin/python when the running interpreter
cannot import them, the same fallback scripts/_toolroutes.py uses.

Usage: toolgen_py.py [-cohort PATH] [-out DIR] [-hooks PATH] [-languages PATH]
"""

from __future__ import annotations

import argparse
import importlib
import subprocess
import sys
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Iterable, Iterator, Sequence
    from types import ModuleType

    from google.protobuf.descriptor import Descriptor, FieldDescriptor

REPO_ROOT = Path(__file__).resolve().parents[1]
VENV_PYTHON = REPO_ROOT / "python" / ".venv" / "bin" / "python"
VENV_RUFF = REPO_ROOT / "python" / ".venv" / "bin" / "ruff"

_DEFAULT_COHORT = REPO_ROOT / "docs" / "contracts" / "generated-tools.txt"
_DEFAULT_OUT = REPO_ROOT / "python" / "src" / "linodemcp" / "gentools"
_DEFAULT_HOOKS = REPO_ROOT / "docs" / "contracts" / "tool-hooks.txt"
_DEFAULT_LANGUAGES = REPO_ROOT / "docs" / "contracts" / "languages.txt"

# Written out here because the emitted import lines name them.
_PACKAGE = "linodemcp.gentools"
_HOOKS_MODULE = "linodemcp.toolhooks"

# This emitter's column in the hook manifest.
_LANGUAGE = "python"

# The manifest's columns: tool, kind, language, function.
_HOOK_FIELDS = 4
_HOOK_KIND_VALIDATE = "validate"

# Suffix marking a filter argument that matches a substring of the field its
# name prefixes, rather than the whole of it.
_CONTAINS_SUFFIX = "_contains"

# Arguments that select a page instead of narrowing one. The shared pagination
# reader owns both, so neither becomes a client-side filter.
_PAGINATION_ARGS = frozenset({"page", "page_size"})

# The one name in a failure template that is not an input field.
_ERROR_PLACEHOLDER = "error"

_HEADER = "# Code generated by scripts/toolgen_py.py. DO NOT EDIT."

# The line length ruff holds this repo to. The emitted tree is linted like
# hand-written code, so a line the emitter cannot fit fails the run.
_LINE_BUDGET = 88

# The Capability member each declared tier registers under. Spelled out rather
# than derived from the enum value, so a new tier fails here instead of
# registering as something plausible.
_CAPABILITIES = {
    "TOOL_CAPABILITY_READ": "Read",
    "TOOL_CAPABILITY_WRITE": "Write",
    "TOOL_CAPABILITY_DESTROY": "Destroy",
    "TOOL_CAPABILITY_ADMIN": "Admin",
    "TOOL_CAPABILITY_META": "Meta",
}


class GenError(RuntimeError):
    """The contract cannot answer something the emitter needs.

    Every case names the tool and stops rather than emitting a factory that
    says less than the contract does.
    """


class Tier(Enum):
    """The shape of code one tool needs, read off its contract.

    Nothing declares a tier: a response with a single repeated field is a
    collection, and a collection addressed under a path id is a sub-resource
    collection.
    """

    GET = "get"
    LIST = "list"
    SUBRESOURCE_LIST = "subresource_list"


@dataclass(frozen=True)
class PathArg:
    """How one path argument is read out of a tool call.

    absent is the value meaning the caller omitted it, coerce the builtin the
    read goes through before it reaches the route. Both follow the field's
    declared type, so a slug id never reaches int().
    """

    absent: str
    coerce: str


@dataclass(frozen=True)
class ToolFilter:
    """One client-side filter: a query argument matched against an element field."""

    argument: str
    element_field: str
    contains: bool


@dataclass
class ToolContract:
    """Everything the descriptors say about one tool the emitter writes."""

    name: str
    source_file: str
    input_message: str
    description: str
    error_message: str
    capability: str
    method: str
    path_template: str
    slots: tuple[str, ...]
    path_fields: dict[str, FieldDescriptor]
    query_fields: list[FieldDescriptor]
    element: Descriptor | None
    tier: Tier
    path_args: dict[str, PathArg] = field(default_factory=dict)
    filters: list[ToolFilter] = field(default_factory=list)


def _routes() -> ModuleType:
    """The client-side contract reader, the same one the server reads through.

    Going through it rather than walking the descriptors keeps a tool from
    being generated off one reading of the contract and served off another.
    """
    return importlib.import_module("linodemcp.linode.routes")


def _options() -> ModuleType:
    """The generated options module, on the import path the reader above uses.

    A second import path gives the extensions different identities and every
    field's location reads back as unset.
    """
    return importlib.import_module("linodemcp.genpb.linode.mcp.v1.options_pb2")


def read_cohort(path: Path) -> list[str]:
    """The tool names the emitter owns, in file order."""
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


def read_languages(path: Path) -> set[str]:
    """The language names the registry declares."""
    found = {
        line.split("\t", maxsplit=1)[0].strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    }
    if not found:
        msg = f"{path} registers no languages"
        raise GenError(msg)
    return found


def read_hooks(
    path: Path, cohort: Iterable[str], languages: set[str]
) -> dict[str, str]:
    """The Python hooks the manifest declares, as {tool: function}.

    The whole manifest is checked, not only the Python lines. The Go emitter
    reads only its own, so this is the one place the file is held to being well
    formed.
    """
    if not path.exists():
        return {}

    generated = set(cohort)
    hooks: dict[str, str] = {}

    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue

        parts = line.split()
        if len(parts) != _HOOK_FIELDS:
            msg = f"{path}: malformed hook line: {line!r}"
            raise GenError(msg)

        tool, kind, language, function = parts
        _check_hook_line(path, languages, generated, (tool, kind, language))

        if language != _LANGUAGE:
            continue
        if tool in hooks:
            msg = f"{path}: {tool} declares two {_LANGUAGE} {kind} hooks"
            raise GenError(msg)
        hooks[tool] = function

    return hooks


def _check_hook_line(
    path: Path, languages: set[str], generated: set[str], line: tuple[str, str, str]
) -> None:
    """Report a hook line that names something nothing can act on."""
    tool, kind, language = line

    if kind != _HOOK_KIND_VALIDATE:
        msg = f"{path}: {tool} declares unknown hook kind {kind!r}"
        raise GenError(msg)
    if language not in languages:
        msg = f"{path}: {tool} declares unregistered hook language {language!r}"
        raise GenError(msg)
    if tool not in generated:
        msg = f"{path}: {tool} declares a hook and is not a generated tool"
        raise GenError(msg)


def resolve_hooks(hooks: dict[str, str], module_name: str = _HOOKS_MODULE) -> None:
    """Hold every declared Python hook to being implemented.

    The emitted call names the function directly, so a missing one fails at
    server start. Resolving it here moves that failure to the build, where the
    Go side's equivalent already lands as a compile error.
    """
    if not hooks:
        return

    try:
        module = importlib.import_module(module_name)
    except ImportError as exc:
        declared = ", ".join(sorted(hooks))
        msg = f"hooks declared for {declared} but {module_name} does not import: {exc}"
        raise GenError(msg) from exc

    for tool, function in sorted(hooks.items()):
        if not callable(getattr(module, function, None)):
            msg = f"{module_name} implements no {function}, the hook {tool} declares"
            raise GenError(msg)


def build_contract(tool: str) -> ToolContract:
    """Read one tool's whole declaration."""
    routes = _routes()
    declared = routes.contract_for(tool)
    route = routes.route_for(tool)

    if not declared.description:
        msg = f"{tool} declares no tool_description"
        raise GenError(msg)

    message = routes.input_descriptor(tool)
    path_fields, query_fields = _locate_fields(tool, message)
    element = _element_descriptor(tool, routes.response_descriptor(tool))
    tier = _tier(element, path_fields)

    built = ToolContract(
        name=tool,
        source_file=str(message.file.name),
        input_message=str(message.full_name),
        description=str(declared.description),
        error_message=str(declared.error_message),
        capability=_capability_member(
            tool, routes.capability_name(_capability(message))
        ),
        method=route.method,
        path_template=route.template,
        slots=tuple(route.slots),
        path_fields=path_fields,
        query_fields=query_fields,
        element=element,
        tier=tier,
    )
    _check_path_arity(built)
    built.path_args = {
        name: _path_arg(tool, entry) for name, entry in path_fields.items()
    }
    built.filters = _derive_filters(built)
    _check_messages(built)
    return built


def _path_arg(tool: str, entry: FieldDescriptor) -> PathArg:
    """How one path field is read, from the type it declares.

    A URL segment carries an integer id or a label, the same pair
    go/cmd/toolgen accepts. Anything else has no spelling in a path, so it
    fails by name.
    """
    if entry.type in {entry.TYPE_INT32, entry.TYPE_INT64}:
        return PathArg("0", "int")
    if entry.type == entry.TYPE_STRING:
        return PathArg('""', "str")

    msg = f"{tool} path field {entry.name} has no representation in a route path"
    raise GenError(msg)


def _capability(message: Descriptor) -> int:
    """The tier a tool is registered at."""
    return int(message.GetOptions().Extensions[_options().tool_capability])


def _capability_member(tool: str, declared: str) -> str:
    """The Capability member a declared tier registers under."""
    member = _CAPABILITIES.get(declared)
    if member is None:
        msg = f"{tool} declares {declared}, which no Capability member covers"
        raise GenError(msg)
    return member


def _locate_fields(
    tool: str, message: Descriptor
) -> tuple[dict[str, FieldDescriptor], list[FieldDescriptor]]:
    """Sort an input's fields by where the contract says they travel.

    Body and local fields are not collected: a local field never leaves the MCP
    layer, and no tier emitted so far sends a body.
    """
    options = _options()
    path: dict[str, FieldDescriptor] = {}
    query: list[FieldDescriptor] = []

    for entry in message.fields:
        location = entry.GetOptions().Extensions[options.field_location]
        if location == options.FIELD_LOCATION_UNSPECIFIED:
            msg = f"{tool} field {entry.name} declares no field_location"
            raise GenError(msg)
        if location == options.FIELD_LOCATION_PATH:
            path[entry.name] = entry
        elif location == options.FIELD_LOCATION_QUERY:
            query.append(entry)

    return path, query


def _element_descriptor(tool: str, response: Descriptor) -> Descriptor | None:
    """The element of the collection a response carries, None for one resource.

    A page is a count beside one repeated message field, not repetition on its
    own: a user's grants, an LKE pool's disks and nodes, and an instance's
    interfaces all repeat without being pages. Serving one of those through the
    list driver would answer with a count and a single section.
    """
    repeated = [
        entry
        for entry in response.fields
        if entry.is_repeated and entry.message_type is not None
    ]
    if "count" in response.fields_by_name and len(repeated) == 1:
        return repeated[0].message_type

    _check_not_a_page(tool, response, repeated)
    return None


def _check_not_a_page(
    tool: str, response: Descriptor, repeated: list[FieldDescriptor]
) -> None:
    """Confirm a response the page test rejected really is one resource.

    Every page envelope here is named ListResponse, so that spelling on some
    other shape means name and shape disagree. Serving it as a resource would
    answer with an empty collection rather than fail.
    """
    if not response.full_name.endswith("ListResponse"):
        return

    names = ", ".join(entry.name for entry in repeated) or "nothing"
    count = "a" if "count" in response.fields_by_name else "no"
    msg = (
        f"{tool} answers with {response.full_name}, which has {count} count"
        f" field and repeats {names}, so it is named a page and shaped otherwise"
    )
    raise GenError(msg)


def _tier(element: Descriptor | None, path_fields: dict[str, FieldDescriptor]) -> Tier:
    """Which shape of code the tool needs, from what the contract already says."""
    if element is None:
        return Tier.GET
    return Tier.SUBRESOURCE_LIST if path_fields else Tier.LIST


def _check_path_arity(built: ToolContract) -> None:
    """Report a route whose slots and PATH fields disagree.

    A slot with no field addresses the collection a resource sits in rather
    than the resource, and a field no slot names is read and then dropped.
    """
    if set(built.slots) != set(built.path_fields):
        slots = ", ".join(built.slots) or "none"
        fields = ", ".join(sorted(built.path_fields)) or "none"
        msg = f"{built.name} fills slots ({slots}) from PATH fields ({fields})"
        raise GenError(msg)


def _derive_filters(built: ToolContract) -> list[ToolFilter]:
    """Match every non-pagination query argument against an element field.

    An argument matching no element field is refused rather than dropped: a
    filter the tool advertises and never applies answers with the unfiltered
    page while claiming otherwise.
    """
    if built.element is None:
        return []

    found: list[ToolFilter] = []
    for entry in built.query_fields:
        if entry.name in _PAGINATION_ARGS:
            continue

        contains = entry.name.endswith(_CONTAINS_SUFFIX)
        target = entry.name.removesuffix(_CONTAINS_SUFFIX) if contains else entry.name
        found.append(
            ToolFilter(
                argument=entry.name,
                element_field=_filter_field(built, target),
                contains=contains,
            )
        )

    return found


def _filter_field(built: ToolContract, target: str) -> str:
    """The element field one filter reads, held to a type both languages match on.

    Go filters over a string accessor, so a filter on any other type would
    generate there and not compile.
    """
    element = built.element
    if element is None:
        msg = f"{built.name} declares a filter and answers with no collection"
        raise GenError(msg)

    entry = element.fields_by_name.get(target)
    if entry is None:
        msg = (
            f"{built.name} filters on {target}, which {element.full_name}"
            " has no field for"
        )
        raise GenError(msg)
    if entry.type != entry.TYPE_STRING:
        msg = (
            f"{built.name} filters on {element.full_name}.{target}, which is not"
            " a string, and only string fields match the same way in both languages"
        )
        raise GenError(msg)
    return str(entry.name)


def _check_messages(built: ToolContract) -> None:
    """Hold a tool's declared prose to naming things the handler can fill.

    A message reaching a client still carrying "{domain_id}" reads as a bug in
    the tool. GET must declare one at all, since its whole failure report is
    that sentence; the list tier answers the one shared list sentence and
    deliberately declares none.
    """
    if built.tier is Tier.GET and not built.error_message:
        msg = f"{built.name} declares no error_message to report a failure with"
        raise GenError(msg)

    fillable = set(built.path_fields) | {entry.name for entry in built.query_fields}
    for name in _placeholders(built.error_message):
        if name != _ERROR_PLACEHOLDER and name not in fillable:
            msg = f"{built.name} error_message names {name}, which is no input field"
            raise GenError(msg)


def _placeholders(template: str) -> Iterator[str]:
    """The placeholder names a message template carries, in template order."""
    rest = template
    while True:
        opened = rest.find("{")
        if opened < 0:
            return
        closed = rest.find("}", opened)
        if closed < 0:
            return
        yield rest[opened + 1 : closed]
        rest = rest[closed + 1 :]


def _quote(text: str) -> str:
    """One Python string literal holding text.

    Contract prose carries quotes and braces of its own, so they are escaped
    rather than assumed absent.
    """
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _quote_wrapped(text: str, indent: int) -> list[str]:
    """One string literal, split across lines when it does not fit.

    The split is at spaces, with the space kept on the line before it, so the
    pieces concatenate back to the exact sentence the contract declares.
    """
    pad = " " * indent
    single = pad + _quote(text)
    if len(single) <= _LINE_BUDGET:
        return [single]

    # Room for the padding, the two quotes, and the trailing space a word keeps.
    room = _LINE_BUDGET - indent - 4
    lines: list[str] = []
    current = ""

    for word in text.split(" "):
        candidate = f"{current}{word} "
        if current and len(candidate) > room:
            lines.append(pad + _quote(current))
            current = f"{word} "
            continue
        current = candidate

    return [*lines, pad + _quote(current.rstrip(" "))]


def _module_name(source_file: str) -> str:
    """The emitted module for a proto path: linode/mcp/v1/domain.proto is domain."""
    return Path(source_file).stem


def factory_name(tool: str) -> str:
    """The factory a tool registers through, which the registry finds by shape."""
    return f"create_{tool}_tool"


def handler_name(tool: str) -> str:
    """The handler the registry pairs with the factory of the same tool."""
    return f"handle_{tool}"


def render_module(contracts: Sequence[ToolContract], hooks: dict[str, str]) -> str:
    """One emitted module: the factories and handlers of one proto file."""
    body: list[str] = []
    for built in contracts:
        body.extend(_render_factory(built))
        body.append("")
        body.append("")
        body.extend(_render_handler(built, hooks.get(built.name, "")))
        body.append("")
        body.append("")

    source_files = sorted({built.source_file for built in contracts})
    doc = "Generated tool factories for " + ", ".join(source_files) + "."
    head = [
        _HEADER,
        f'"""{doc}"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import TYPE_CHECKING, Any",
        "",
        "from mcp.types import TextContent, Tool",
        "",
        *_render_imports(contracts, hooks),
        "",
        "if TYPE_CHECKING:",
        "    from linodemcp.config import Config",
        "",
        "",
    ]
    return "\n".join([*head, *body[:-2], ""])


def _finish(text: str, name: str) -> str:
    """Format the rendered text, then hold it to the line budget.

    ruff decides where the code breaks, the same way go/cmd/toolgen leans on
    go/format, so the generated tree passes the format gate hand-written code
    does. Prose is what ruff cannot rewrap, so a line still over the budget
    after formatting is a sentence too long to render and fails by name.
    """
    text = _formatted(text, name)

    for line in text.splitlines():
        if len(line) > _LINE_BUDGET:
            msg = f"emitted line over {_LINE_BUDGET} columns in {name}: {line!r}"
            raise GenError(msg)
    return text


def _formatted(text: str, name: str) -> str:
    """Rendered text as the repo's formatter would write it.

    The file name goes in so ruff resolves the same configuration it would for
    a file at that path, rather than its defaults.
    """
    if not VENV_RUFF.exists():
        msg = (
            f"{VENV_RUFF} missing; the emitted tree is formatted with the same"
            " ruff the repo lints with. Run `make -C python install-dev`."
        )
        raise GenError(msg)

    # Fixed argv, no shell; the formatter and the path are both repo-owned.
    result = subprocess.run(
        [str(VENV_RUFF), "format", "--stdin-filename", name, "-"],
        input=text,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        msg = f"formatting {name} failed:\n{result.stderr.strip()}"
        raise GenError(msg)

    return str(result.stdout)


def _render_imports(
    contracts: Sequence[ToolContract], hooks: dict[str, str]
) -> list[str]:
    """The first-party imports the rendered module takes.

    Only what the tiers present actually use, so an unused import cannot reach
    the emitted tree: it is linted like hand-written code rather than excused
    from it.
    """
    drivers = sorted(
        {
            "run_get_tool" if built.tier is Tier.GET else "run_list_tool"
            for built in contracts
        }
    )
    if any(built.filters for built in contracts):
        drivers = sorted([*drivers, "ListFilter", "MatchMode"])

    lines = ["from linodemcp.profiles import Capability"]
    lines.append("from linodemcp.tools.drivers import " + ", ".join(drivers))
    if any(built.path_fields for built in contracts):
        lines.append("from linodemcp.tools.helpers import error_response")
    lines.append("from linodemcp.tools.toolschemas import schema")
    if any(built.name in hooks for built in contracts):
        lines.append(f"from {_HOOKS_MODULE} import " + _hook_imports(contracts, hooks))
    return lines


def _hook_imports(contracts: Sequence[ToolContract], hooks: dict[str, str]) -> str:
    """The hook functions a rendered module calls, named directly so a missing
    one fails at import rather than on a tool call."""
    return ", ".join(
        sorted({hooks[built.name] for built in contracts if built.name in hooks})
    )


def _route_text(built: ToolContract) -> str:
    """The operation a tool performs, for the emitted doc comments, so a reader
    of the generated module sees it without opening the proto."""
    return f"{built.method} {built.path_template}"


def _render_factory(built: ToolContract) -> list[str]:
    """The factory: the tool a client sees, and the tier it registers at."""
    return [
        f"def {factory_name(built.name)}() -> tuple[Tool, Capability]:",
        f'    """Build {built.name}.',
        "",
        f"    Calls {_route_text(built)}.",
        '    """',
        "    return Tool(",
        f"        name={_quote(built.name)},",
        "        description=(",
        *_quote_wrapped(built.description, 12),
        "        ),",
        f"        input_schema=schema({_quote(built.input_message)}),",
        f"    ), Capability.{built.capability}",
    ]


def _render_handler(built: ToolContract, hook: str) -> list[str]:
    """The handler: the arguments the contract locates, then the driver call."""
    lines = [
        f"async def {handler_name(built.name)}(",
        "    arguments: dict[str, Any], cfg: Config",
        ") -> list[TextContent]:",
        f'    """Handle {built.name}.',
        "",
        f"    Calls {_route_text(built)}.",
        '    """',
    ]
    lines.extend(_render_arguments(built, hook))
    lines.extend(_render_driver_call(built))
    return lines


def _render_arguments(built: ToolContract, hook: str) -> list[str]:
    """Read the path values and refuse a call that omits one.

    A tool with a declared hook has none of this: the hook owns the whole
    argument check, which is the point of declaring one.
    """
    if not built.slots:
        return []

    lines: list[str] = []
    if hook:
        lines.extend(
            [
                f"    message = {hook}(arguments)",
                "    if message:",
                "        return error_response(message)",
                "",
            ]
        )

    lines.extend(
        f"    {slot} = arguments.get({_quote(slot)}, {built.path_args[slot].absent})"
        for slot in built.slots
    )
    if not hook:
        for slot in built.slots:
            lines.extend(
                [
                    f"    if not {slot}:",
                    f"        return error_response({_quote(slot + ' is required')})",
                ]
            )
    lines.append("")
    return lines


def _render_driver_call(built: ToolContract) -> list[str]:
    """The driver the tier runs through, named with what it cannot derive."""
    driver = "run_get_tool" if built.tier is Tier.GET else "run_list_tool"
    lines = [
        f"    return await {driver}(",
        "        cfg,",
        "        arguments,",
        f"        tool={_quote(built.name)},",
    ]
    if built.slots:
        values = ", ".join(
            f"{_quote(slot)}: {built.path_args[slot].coerce}({slot})"
            for slot in built.slots
        )
        lines.append(f"        path_values={{{values}}},")
    if built.filters:
        lines.append("        filters=(")
        lines.extend(f"            {_render_filter(entry)}," for entry in built.filters)
        lines.append("        ),")
    lines.append("    )")
    return lines


def _render_filter(entry: ToolFilter) -> str:
    """One ListFilter literal. The default mode is the substring match, so only
    the equality case names one."""
    mode = "" if entry.contains else ", MatchMode.EQUALS"
    return f"ListFilter({_quote(entry.argument)}, {_quote(entry.element_field)}{mode})"


def render_registry(contracts: Sequence[ToolContract]) -> str:
    """The package module the server reads its generated tools from.

    A generated tool nothing registers would pass every gate that reads the
    contract and still be missing from the running server, so the registration
    is emitted from the same cohort as the factories.
    """
    by_module: dict[str, list[str]] = {}
    exported: list[str] = []

    for built in sorted(contracts, key=lambda entry: entry.name):
        module = _module_name(built.source_file)
        names = [factory_name(built.name), handler_name(built.name)]
        by_module.setdefault(module, []).extend(names)
        exported.extend(names)

    lines = [
        _HEADER,
        '"""The tool factories scripts/toolgen_py.py emits from the proto contract.',
        "",
        "Nothing here is hand-written and nothing here survives a `make proto`:",
        "change the contract, not this tree.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]
    for module in sorted(by_module):
        imported = ",\n".join(f"    {name}" for name in sorted(by_module[module]))
        lines.append(f"from {_PACKAGE}.{module} import (\n{imported},\n)")

    listed = ",\n".join(f"    {_quote(name)}" for name in sorted(exported))
    lines.extend(["", f"__all__ = [\n{listed},\n]", ""])
    return "\n".join(lines)


def write_tree(out: Path, files: dict[str, str]) -> None:
    """Replace the emitted tree with files.

    Removing what was there first is what keeps a tool that left the cohort
    from leaving a factory behind, which would register a tool the contract no
    longer describes.
    """
    out.mkdir(parents=True, exist_ok=True)
    for stale in out.glob("*.py"):
        stale.unlink()
    for name, text in files.items():
        (out / name).write_text(text, encoding="utf-8")


def render_tree(
    contracts: Sequence[ToolContract], hooks: dict[str, str], out: Path
) -> dict[str, str]:
    """Every emitted file, keyed by name, in one dict so a failure writes none.

    out is where the tree lands, which the formatter needs to resolve the same
    configuration the linter will read the written files under.
    """
    grouped: dict[str, list[ToolContract]] = {}
    for built in contracts:
        grouped.setdefault(_module_name(built.source_file), []).append(built)

    files = {
        f"{module}.py": render_module(sorted(tools, key=lambda e: e.name), hooks)
        for module, tools in grouped.items()
    }
    files["__init__.py"] = render_registry(contracts)
    return {
        name: _finish(text, str(out / name)) for name, text in sorted(files.items())
    }


def generate(cohort: Path, out: Path, hooks_path: Path, languages_path: Path) -> int:
    """Read the cohort and write the tree, answering how many tools it holds."""
    tools = read_cohort(cohort)
    languages = read_languages(languages_path)
    hooks = read_hooks(hooks_path, tools, languages)
    resolve_hooks(hooks)

    contracts = [build_contract(tool) for tool in tools]
    write_tree(out, render_tree(contracts, hooks, out))
    return len(contracts)


def _through_venv() -> int:
    """Re-run under the venv interpreter, which has the protobuf runtime.

    The Makefile invokes this with plain python3, matching how it invokes the
    offline gates, and the descriptors need more than a bare interpreter has.
    """
    if not VENV_PYTHON.exists():
        msg = (
            "python/.venv missing; the tool contract is read from the generated"
            " descriptors. Run `make -C python install-dev`."
        )
        raise SystemExit(msg)

    # Fixed argv, no shell; the interpreter and the script are both repo-owned.
    result = subprocess.run(
        [str(VENV_PYTHON), str(Path(__file__).resolve()), *sys.argv[1:]],
        check=False,
    )
    return int(result.returncode)


def main(argv: Sequence[str] | None = None) -> int:
    """Emit the tree, or report the one thing that stopped it."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-cohort", type=Path, default=_DEFAULT_COHORT)
    parser.add_argument("-out", type=Path, default=_DEFAULT_OUT)
    parser.add_argument("-hooks", type=Path, default=_DEFAULT_HOOKS)
    parser.add_argument("-languages", type=Path, default=_DEFAULT_LANGUAGES)
    args = parser.parse_args(argv)

    try:
        count = generate(args.cohort, args.out, args.hooks, args.languages)
    except GenError as exc:
        sys.stderr.write(f"toolgen_py: {exc}\n")
        return 1

    sys.stderr.write(f"toolgen_py: emitted {count} tool(s) into {args.out}\n")
    return 0


if __name__ == "__main__":
    try:
        importlib.import_module("linodemcp.linode.routes")
    except ImportError:
        raise SystemExit(_through_venv()) from None

    raise SystemExit(main())
