#!/usr/bin/env python3
"""Refresh every dependency version this repository declares, in one command.

Five surfaces carry a declared version, and each one is found from a declared
source rather than from a path written here:

- Go modules: every language directory docs/contracts/languages.txt registers
  that carries a go.mod. `go get -u ./...` then `go mod tidy`. Every run first
  checks each go.mod require line against its own go.sum and fails when one has
  no module hash, because `go get -u` against a graph that does not resolve
  stacks a second failure on the first.
- Language versions: the `go` directive in each go.mod and `requires-python` in
  each uv project. These are reported and never rewritten. A language version
  is not a dependency; it is the floor every dependency resolves against, so it
  gets its own surface rather than one more line in a refresh diff.
- Python: every uv project, meaning a directory holding both a pyproject.toml
  and a uv.lock. That is the registered language directories plus the tool
  projects under tools/, so the comparator's own project is covered the same
  way `make tools-typecheck` covers it, and a third project arrives without an
  edit here. `uv lock --upgrade`, then the declared floors rise to what uv
  locked, then a plain `uv lock` so the requirement strings the lock records
  match the pyproject again.
- Tool versions: the provisioning surface, meaning scripts/*.sh plus the root
  Makefile and each registered language's Makefile, together with the codegen
  templates and the pre-commit hook revisions. Almost everything here floats at
  @latest by repo policy (scripts/ci-setup.sh states it), so this surface
  reports what floats, refuses the pins that must not move, and updates the
  revisions that are written down.
- GitHub Actions: every `uses:` line under .github/workflows. Renovate's
  helpers:pinGitHubActionDigests writes `owner/repo@<sha> # <tag>`, and that
  exact form is preserved: the sha and the trailing comment are rewritten
  together or the pin is wrong. The tag a pin follows is the comment, so a
  reference tracking `v7` stays on the newest `v7`-shaped tag rather than
  jumping to a three-part one.

buf is refused by name. Its version decides the bytes `make proto` writes, and
every baseline in this repository was captured under it, so a bump would move
the baselines instead of the code. The buf remote codegen plugins are refused
for the same reason.

Renovate already manages the four writable surfaces daily at 04:00 UTC with
branch automerge, so this target and Renovate write the same files. That
overlap is deliberate. It is also why every rewrite here copies Renovate's pin
form: a human diffing one against the other sees the same shape. Renovate has
custom managers for the language versions too, and it moves them where this
target only reports them.
docs/dependency-updates.md carries the rest of that story.

Nothing here touches git. The target rewrites files and stops; staging,
branching, and committing stay human work.

`--dry-run` makes no network call at all. It names every target discovery
found, the value each one declares now, and the disposition it would get, so
the plan can be read offline before anything rewrites a lock file. It cannot
name the version a bump would land on, because knowing that needs the network.

Never a `make check` gate: this needs the network and it writes. Run it via
`make update-deps` (or `make update-deps-dry-run`).

Usage: update_deps.py [--dry-run]
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tomllib
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, cast

import _hardgate

if TYPE_CHECKING:
    from collections.abc import Sequence

_ROOT = Path(__file__).resolve().parent.parent
_LANGUAGES = _ROOT / "docs" / "contracts" / "languages.txt"
_TOOLS = _ROOT / "tools"
_WORKFLOWS = _ROOT / ".github" / "workflows"
_RENOVATE = _ROOT / "renovate.json"
_PRECOMMIT = _ROOT / ".pre-commit-config.yaml"

# What this run decided about one declared version.
_UPDATE = "update"
_REFUSE = "refuse"
_HOLD = "hold"
_FLOAT = "float"
_UNKNOWN = "unknown"

_CODEGEN_REASON = (
    "codegen must stay byte-reproducible and every committed baseline was"
    " captured under this version"
)

# Tool versions that decide generated bytes. Bumping one moves the baselines
# instead of the code, so the buf pin and the plugins it drives are refused.
_PROTECTED_TOOLS = {
    "github.com/bufbuild/buf/cmd/buf": _CODEGEN_REASON,
    "buf.build/protocolbuffers/go": _CODEGEN_REASON,
    "buf.build/protocolbuffers/python": _CODEGEN_REASON,
    "buf.build/protocolbuffers/pyi": _CODEGEN_REASON,
}

# Python floors that answer to something other than "whatever released last".
_PROTECTED_PYTHON = {
    "protobuf": (
        "its floor tracks the buf python and pyi plugin tags in buf.gen.yaml;"
        " move the two together or every _pb2 import raises"
    ),
    "protovalidate": (
        "pinned exactly: the generated buf/validate messages come from this release"
    ),
}

_FLOAT_NOTE = "no declared version, so every run resolves the newest release"
_RUNTIME_NOTE = "resolved from the newest release at install time"
_PRECOMMIT_NOTE = "pre-commit autoupdate rewrites the rev"
_LOCAL_NOTE = "a path in this repository, which carries no version"
_ODD_PIN_NOTE = "a written-down version with no resolver here"
_ACTION_DIGEST_NOTE = "sha and the trailing version comment, rewritten together"
_ACTION_TAG_NOTE = "tag only: renovate.json keeps this one off digests"
_SPEC_NOTE = (
    "only a bare >= floor is rewritten here; a ceiling or an exact pin is a"
    " human decision"
)
_GO_LANGUAGE_NOTE = (
    "reported, not rewritten: the directive sets the lowest Go a build accepts,"
    " and raising it turns on analyzer rules the gates then fail on unchanged"
    " code"
)
_PYTHON_LANGUAGE_NOTE = (
    "reported, not rewritten: uv resolves every locked package against this"
    " floor, so moving it re-resolves the whole project"
)

_FIX = (
    "Float it at @latest the way scripts/ci-setup.sh floats the rest of the\n"
    "toolchain, or add it to the protected table in scripts/update_deps.py\n"
    "with the reason it must not move."
)

_GRAPH_FIX = (
    "Correct the require line rather than writing the missing sum. A version\n"
    "go.sum cannot cover is usually one no resolver would pick: a release the\n"
    "author retracted, or a module that renamed its path at that version.\n"
    "`go get` and `go mod tidy` both refuse to run while such a line is in the\n"
    "file, so the edit has to come first and `go mod tidy` settles the rest."
)

# `go install x@v`, `go run x@v`, and `npx pkg@v` are the three ways a tool
# version reaches the gates today.
_PIN = re.compile(
    r"\b(?:go install|go run|npx(?:\s+--?[\w-]+)*)\s+"
    r"(?P<ref>[A-Za-z0-9][^\s@]*)@(?P<version>[A-Za-z0-9]\S*)"
)

# scripts/ci-setup.sh resolves several binaries from whatever release is newest
# when it runs, through the releases/latest redirect or through the API. Those
# carry no version token, so they are reported rather than updated.
_RUNTIME = re.compile(
    r"latest_tag\s+(?P<redirect>[\w.-]+/[\w.-]+)"
    r"|api\.github\.com/repos/(?P<api>[\w.-]+/[\w.-]+)/releases/latest"
)

_REMOTE_PLUGIN = re.compile(r"^\s*-\s*remote:\s*(?P<ref>\S+)\s*$")
_PRECOMMIT_REPO = re.compile(r"^\s*-\s*repo:\s*(?P<repo>\S+)\s*$")
_PRECOMMIT_REV = re.compile(r"^\s*rev:\s*(?P<rev>\S+)\s*$")

_ANY_USES = re.compile(r"^(?P<lead>\s*(?:-\s+)?uses:\s*)(?P<value>\S.*?)\s*$")
_USES_VALUE = re.compile(
    r"^(?P<target>[^@\s]+)@(?P<ref>\S+)(?:\s*#\s*(?P<comment>\S+))?$"
)
_SHA = re.compile(r"^[0-9a-f]{40}$")
_VERSION_TAG = re.compile(r"^(?P<prefix>v?)(?P<numbers>\d+(?:\.\d+)*)$")

_FLOOR_LINE = re.compile(
    r'^(?P<lead>\s*")(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)'
    r'(?P<op>>=\s*)(?P<floor>[^"\s,;]+)(?P<tail>",?\s*)$'
)
_REQUIREMENT = re.compile(
    r"^(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)(?P<extras>\[[^\]]*\])?(?P<spec>.*)$"
)
_SIMPLE_FLOOR = re.compile(r"^>=\s*(?P<floor>[A-Za-z0-9][^\s,;]*)$")
_GO_DIRECTIVE = re.compile(r"^go\s+(?P<version>\d+(?:\.\d+)*)$")


@dataclass(frozen=True)
class Change:
    """One declared version and what this run decided to do with it."""

    where: str
    what: str
    current: str
    action: str
    note: str


@dataclass(frozen=True)
class Use:
    """One `uses:` reference, split into the parts a bump has to rewrite."""

    slug: str
    path: str
    ref: str
    tracked: str
    digest: bool


def _relative(path: Path) -> str:
    """Repository-relative path, which is how every report line names a file."""
    return str(path.relative_to(_ROOT))


def _code_lines(path: Path) -> list[str]:
    """A file's lines with the comment-only ones dropped.

    Makefile recipes hide behind a leading `@`, and both file kinds comment with
    `#`, so prose naming an install command does not read as a call site.
    """
    kept: list[str] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        stripped = raw.strip().lstrip("@").lstrip()
        if stripped and not stripped.startswith("#"):
            kept.append(raw)

    return kept


def _canonical(name: str) -> str:
    """PEP 503 normalized name, so a pyproject and a uv.lock entry agree."""
    return re.sub(r"[-_.]+", "-", name).lower()


def _items(value: object) -> list[object]:
    """A parsed TOML or JSON value as a list, empty when it is not one.

    tomllib and json both answer with Any, so a key that arrives in an
    unexpected shape would otherwise reach the rewriters as a shape nothing
    checked. Each cast below only restates what its isinstance just proved.
    """
    if not isinstance(value, list):
        return []

    return cast("list[object]", value)


def _table(value: object) -> dict[str, object]:
    """A parsed value as a string-keyed mapping, empty when it is not one."""
    if not isinstance(value, dict):
        return {}

    mapping = cast("dict[object, object]", value)

    return {key: item for key, item in mapping.items() if isinstance(key, str)}


def _strings(value: object) -> list[str]:
    """Every string in a value declared as a list of strings.

    Dropping a wrong shape rather than guessing at it matters most for
    `matchDepNames`: a bare string is iterable, so `set.update` on one would
    add its characters and quietly widen the digest exclusion into nonsense.
    """
    return [entry for entry in _items(value) if isinstance(entry, str)]


# --- Discovery, all of it from a declared source ---


def _language_dirs() -> list[Path]:
    """Working directory of every language the language registry names."""
    dirs: list[Path] = []
    for raw in _LANGUAGES.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        fields = line.split("\t")
        if line and not line.startswith("#") and len(fields) >= 2:
            dirs.append(_ROOT / fields[1])

    return dirs


def go_modules() -> list[Path]:
    """Registered language directories that carry a go.mod."""
    return [path for path in _language_dirs() if (path / "go.mod").is_file()]


def uv_projects() -> list[Path]:
    """Every uv project: the registered languages plus the tool projects.

    A directory qualifies by carrying both a pyproject.toml and a uv.lock, so
    tools/techdocs-proof is found the same way `make tools-typecheck` finds it.
    """
    candidates = list(_language_dirs())
    if _TOOLS.is_dir():
        candidates.extend(
            sorted(path.parent for path in _TOOLS.glob("*/pyproject.toml"))
        )

    return [
        path
        for path in candidates
        if (path / "pyproject.toml").is_file() and (path / "uv.lock").is_file()
    ]


def provisioning_files() -> list[Path]:
    """Every file that installs or runs a versioned tool for the gates."""
    files = [_ROOT / "Makefile", *sorted((_ROOT / "scripts").glob("*.sh"))]
    files.extend(path / "Makefile" for path in _language_dirs())

    return [path for path in files if path.is_file()]


def codegen_templates() -> list[Path]:
    """Every buf template, which is where the remote plugin tags are pinned."""
    return sorted(_ROOT.glob("buf.gen*.yaml"))


def workflow_files() -> list[Path]:
    """Every workflow file, which is where the action pins live."""
    if not _WORKFLOWS.is_dir():
        return []

    return sorted(
        path for path in _WORKFLOWS.iterdir() if path.suffix in {".yml", ".yaml"}
    )


def no_digest_deps() -> set[str]:
    """Action repositories renovate.json keeps on tags rather than digests.

    Read from renovate.json rather than restated here. The SLSA reusable
    workflows verify their own ref and fail when it is a digest, and one
    declaration of that fact is enough for both updaters.
    """
    config = _table(json.loads(_RENOVATE.read_text(encoding="utf-8")))
    names: set[str] = set()
    for entry in _items(config.get("packageRules")):
        rule = _table(entry)
        if rule.get("pinDigests") is False:
            names.update(_strings(rule.get("matchDepNames")))

    return names


# --- Planning: offline, one Change per declared version ---


def _require_lines(text: str) -> list[str]:
    """Every requirement line inside a go.mod `require (` block."""
    lines: list[str] = []
    inside = False
    for raw in text.splitlines():
        line = raw.strip()
        if line.startswith("require ("):
            inside = True
        elif line == ")":
            inside = False
        elif inside and line and not line.startswith("//"):
            lines.append(line)

    return lines


def _go_requirements(module: Path) -> tuple[int, int]:
    """Direct and indirect requirement counts a module's go.mod declares."""
    required = _require_lines((module / "go.mod").read_text(encoding="utf-8"))
    indirect = sum(1 for line in required if "// indirect" in line)

    return len(required) - indirect, indirect


def plan_go(modules: Sequence[Path]) -> list[Change]:
    """One change per Go module, since `go get -u` moves the whole module."""
    changes: list[Change] = []
    for module in modules:
        direct, indirect = _go_requirements(module)
        changes.append(
            Change(
                where=_relative(module / "go.mod"),
                what="every module requirement",
                current=f"{direct} direct, {indirect} indirect",
                action=_UPDATE,
                note="go get -u ./... then go mod tidy",
            )
        )

    return changes


def _sum_versions(module: Path) -> set[str]:
    """Every `path version` pair go.sum carries a hash for.

    A `/go.mod` line keeps that suffix in its version field, so it never reads
    as covering the source a graph-only dependency never fetched.
    """
    covered: set[str] = set()
    for raw in (module / "go.sum").read_text(encoding="utf-8").splitlines():
        fields = raw.split()
        if len(fields) == 3:
            covered.add(f"{fields[0]} {fields[1]}")

    return covered


def _uncovered(module: Path) -> list[str]:
    """Requirements this module's go.sum carries no module hash for."""
    covered = _sum_versions(module)
    where = _relative(module / "go.mod")
    declared = (module / "go.mod").read_text(encoding="utf-8")
    fields = (line.split() for line in _require_lines(declared))

    return [
        f"{where}: {found[0]} {found[1]} has no go.sum entry"
        for found in fields
        if len(found) >= 2 and f"{found[0]} {found[1]}" not in covered
    ]


def go_graph_findings(modules: Sequence[Path]) -> list[str]:
    """Every requirement whose module go.sum cannot cover, across all modules.

    It runs before anything writes, because `go get -u` against a graph that
    does not resolve stacks a second failure on the first. Reading two files
    answers it with no network call, so the dry run carries the check too.

    The shape it catches is narrow and it has already cost this repository a
    build: a require line naming a version no resolver would choose, while
    go.sum still holds the version one did.
    """
    findings: list[str] = []
    for module in modules:
        findings.extend(_uncovered(module))

    return findings


def _one_spelling(version: str) -> str:
    """A go directive with a trailing `.0` dropped, so one version reads one way.

    `go mod tidy` respells `go 1.26` as `go 1.26.0`; that is not drift.
    """
    parts = version.split(".")
    while len(parts) > 2 and parts[-1] == "0":
        parts.pop()

    return ".".join(parts)


def _go_language_change(module: Path) -> list[Change]:
    """The `go` directive a module declares, or nothing when it has none."""
    for raw in (module / "go.mod").read_text(encoding="utf-8").splitlines():
        found = _GO_DIRECTIVE.match(raw.strip())
        if found:
            return [
                Change(
                    where=_relative(module / "go.mod"),
                    what="go language directive",
                    current=_one_spelling(found.group("version")),
                    action=_HOLD,
                    note=_GO_LANGUAGE_NOTE,
                )
            ]

    return []


def _python_language_change(project: Path) -> list[Change]:
    """The `requires-python` floor a project declares, or nothing when absent."""
    parsed = tomllib.loads((project / "pyproject.toml").read_text(encoding="utf-8"))
    spec = _table(parsed.get("project")).get("requires-python")
    if not isinstance(spec, str):
        return []

    return [
        Change(
            where=_relative(project / "pyproject.toml"),
            what="requires-python",
            current=spec,
            action=_HOLD,
            note=_PYTHON_LANGUAGE_NOTE,
        )
    ]


def plan_languages(modules: Sequence[Path], projects: Sequence[Path]) -> list[Change]:
    """One row per declared language version, none of which this run moves.

    These two declarations were the only versions in the tree with no line in
    the report at all. Raising either one re-resolves everything below it, so
    they are named on their own surface where a reader sees them rather than
    folded in beside the requirement counts.
    """
    changes: list[Change] = []
    for module in modules:
        changes.extend(_go_language_change(module))
    for project in projects:
        changes.extend(_python_language_change(project))

    return changes


def _locked_versions(project: Path) -> dict[str, str]:
    """Package name to locked version, read from the project's uv.lock."""
    locked = _table(tomllib.loads((project / "uv.lock").read_text(encoding="utf-8")))
    versions: dict[str, str] = {}
    for entry in _items(locked.get("package")):
        package = _table(entry)
        name = package.get("name")
        version = package.get("version")
        if isinstance(name, str) and isinstance(version, str):
            versions[_canonical(name)] = version

    return versions


def _declared_requirements(project: Path) -> list[str]:
    """Every requirement string the project's pyproject declares."""
    text = (project / "pyproject.toml").read_text(encoding="utf-8")
    table = _table(_table(tomllib.loads(text)).get("project"))
    optional = _table(table.get("optional-dependencies"))
    groups = [table.get("dependencies"), *optional.values()]

    return [entry for group in groups for entry in _strings(group)]


def _floor_change(where: str, requirement: str, locked: dict[str, str]) -> Change:
    """Classify one requirement string against what uv has locked."""
    found = _REQUIREMENT.match(requirement.strip())
    if found is None:
        return Change(where, requirement, "", _UNKNOWN, "not a requirement string")

    name = _canonical(found.group("name"))
    spec = found.group("spec").strip()
    reason = _PROTECTED_PYTHON.get(name)
    if reason is not None:
        return Change(where, name, spec, _REFUSE, reason)
    if _SIMPLE_FLOOR.match(spec) is None:
        return Change(where, name, spec, _HOLD, _SPEC_NOTE)

    landing = locked.get(name, "nothing yet")

    return Change(
        where, name, spec, _UPDATE, f"floor rises to the locked version ({landing})"
    )


def _floor_changes(project: Path) -> list[Change]:
    """One change per declared requirement, with the reason when it is held."""
    locked = _locked_versions(project)
    where = _relative(project / "pyproject.toml")

    return [
        _floor_change(where, requirement, locked)
        for requirement in _declared_requirements(project)
    ]


def plan_python(projects: Sequence[Path]) -> list[Change]:
    """The lock refresh plus one change per declared dependency floor."""
    changes: list[Change] = []
    for project in projects:
        changes.append(
            Change(
                where=_relative(project / "uv.lock"),
                what="every locked package",
                current=f"{len(_locked_versions(project))} locked",
                action=_UPDATE,
                note="uv lock --upgrade, then uv lock once the floors move",
            )
        )
        changes.extend(_floor_changes(project))

    return changes


def _tool_change(where: str, ref: str, version: str) -> Change:
    """Classify one tool reference by the version it declares, if any."""
    reason = _PROTECTED_TOOLS.get(ref)
    if reason is not None:
        return Change(where, ref, version, _REFUSE, reason)
    if version in {"", "latest"}:
        return Change(where, ref, version, _FLOAT, _FLOAT_NOTE)

    return Change(where, ref, version, _UNKNOWN, _ODD_PIN_NOTE)


def _pin_changes(path: Path) -> list[Change]:
    """Every tool version one provisioning file declares or resolves."""
    where = _relative(path)
    changes: list[Change] = []
    for line in _code_lines(path):
        changes.extend(
            _tool_change(where, found.group("ref"), found.group("version"))
            for found in _PIN.finditer(line)
        )
        changes.extend(
            Change(
                where,
                found.group("redirect") or found.group("api"),
                "",
                _FLOAT,
                _RUNTIME_NOTE,
            )
            for found in _RUNTIME.finditer(line)
        )

    return changes


def _split_plugin(ref: str) -> tuple[str, str]:
    """A buf remote plugin reference split into plugin name and version tag."""
    plugin, separator, version = ref.rpartition(":")
    if separator and version:
        return plugin, version

    return ref, ""


def _plugin_changes(path: Path) -> list[Change]:
    """Every remote codegen plugin one buf template names."""
    where = _relative(path)
    changes: list[Change] = []
    for line in _code_lines(path):
        found = _REMOTE_PLUGIN.match(line)
        if found is not None:
            changes.append(_tool_change(where, *_split_plugin(found.group("ref"))))

    return changes


def _rev_change(where: str, repo: str, line: str) -> list[Change]:
    """The revision change for a `rev:` line, when the line is one."""
    found = _PRECOMMIT_REV.match(line)
    if found is None or repo in {"", "local"}:
        return []

    return [Change(where, repo, found.group("rev"), _UPDATE, _PRECOMMIT_NOTE)]


def _precommit_changes() -> list[Change]:
    """Every remote hook revision .pre-commit-config.yaml pins."""
    where = _relative(_PRECOMMIT)
    changes: list[Change] = []
    repo = ""
    for line in _code_lines(_PRECOMMIT):
        found = _PRECOMMIT_REPO.match(line)
        if found is not None:
            repo = found.group("repo")
        changes.extend(_rev_change(where, repo, line))

    return changes


def plan_tools(provisioning: Sequence[Path], templates: Sequence[Path]) -> list[Change]:
    """Every tool version the toolchain, the codegen, and the hooks declare."""
    changes: list[Change] = []
    for path in provisioning:
        changes.extend(_pin_changes(path))
    for path in templates:
        changes.extend(_plugin_changes(path))
    changes.extend(_precommit_changes())

    return changes


def _tag_shape(tag: str) -> tuple[str, int] | None:
    """The `v` prefix and component count a plain release tag is written with."""
    found = _VERSION_TAG.match(tag)
    if found is None:
        return None

    return found.group("prefix"), len(found.group("numbers").split("."))


def _version_key(tag: str) -> tuple[int, ...]:
    """A comparable tuple for a tag `_tag_shape` has already accepted."""
    found = _VERSION_TAG.match(tag)
    if found is None:
        return ()

    return tuple(int(part) for part in found.group("numbers").split("."))


def _parse_use(value: str) -> Use | None:
    """Split a `uses:` value, or None when it names a path in this repository."""
    found = _USES_VALUE.match(value)
    if found is None:
        return None

    target = found.group("target")
    parts = target.split("/")
    if target.startswith(".") or len(parts) < 2:
        return None

    ref = found.group("ref")
    digest = bool(_SHA.match(ref))
    comment = found.group("comment") or ""

    return Use(
        slug="/".join(parts[:2]),
        path="/".join(parts[2:]),
        ref=ref,
        tracked=comment if digest else ref,
        digest=digest,
    )


def _action_change(where: str, value: str, tag_only: set[str]) -> Change:
    """Classify one `uses:` value by the pin form it is written in."""
    use = _parse_use(value)
    if use is None:
        return Change(where, value, "", _HOLD, _LOCAL_NOTE)
    if _tag_shape(use.tracked) is None:
        return Change(where, use.slug, use.ref, _UNKNOWN, _ODD_PIN_NOTE)

    note = _ACTION_TAG_NOTE if use.slug in tag_only else _ACTION_DIGEST_NOTE

    return Change(where, use.slug, use.tracked, _UPDATE, note)


def _action_changes(path: Path, tag_only: set[str]) -> list[Change]:
    """Classify every action reference in one workflow file."""
    where = _relative(path)
    changes: list[Change] = []
    for line in _code_lines(path):
        found = _ANY_USES.match(line)
        if found is not None:
            changes.append(_action_change(where, found.group("value"), tag_only))

    return changes


def plan_actions(files: Sequence[Path], tag_only: set[str]) -> list[Change]:
    """Every `uses:` pin under .github/workflows, with how it is written."""
    changes: list[Change] = []
    for path in files:
        changes.extend(_action_changes(path, tag_only))

    return changes


# --- Applying: this half needs the network and writes ---


def _run(argv: Sequence[str], cwd: Path) -> str:
    """Run a command, failing loudly with everything it printed."""
    result = subprocess.run(
        list(argv), cwd=cwd, capture_output=True, text=True, check=False
    )
    if result.returncode != 0:
        joined = " ".join(argv)
        raise SystemExit(
            f"{joined} failed in {_relative(cwd)}:\n{result.stdout}{result.stderr}"
        )

    return result.stdout


def apply_go(modules: Sequence[Path]) -> list[str]:
    """Move every module requirement, then let go mod tidy settle the graph."""
    lines: list[str] = []
    for module in modules:
        _run(["go", "get", "-u", "./..."], module)
        _run(["go", "mod", "tidy"], module)
        lines.append(f"{_relative(module)}: go get -u ./... and go mod tidy done")

    return lines


def _raise_one(line: str, wanted: dict[str, str]) -> tuple[str, list[str]]:
    """One pyproject line with its floor raised, plus what moved on it."""
    found = _FLOOR_LINE.match(line.rstrip("\n"))
    if found is None:
        return line, []

    target = wanted.get(_canonical(found.group("name")))
    if target is None or target == found.group("floor"):
        return line, []

    ending = "\n" if line.endswith("\n") else ""
    rewritten = (
        f"{found.group('lead')}{found.group('name')}{found.group('op')}"
        f"{target}{found.group('tail')}{ending}"
    )

    return rewritten, [f"{found.group('name')} {found.group('floor')} -> {target}"]


def _rewrite_floors(text: str, wanted: dict[str, str]) -> tuple[str, list[str]]:
    """The pyproject text with every named floor raised, and what moved."""
    moved: list[str] = []
    out: list[str] = []
    for line in text.splitlines(keepends=True):
        rewritten, note = _raise_one(line, wanted)
        out.append(rewritten)
        moved.extend(note)

    return "".join(out), moved


def _raise_floors(project: Path) -> list[str]:
    """Rewrite every bare `>=` floor to the version uv has locked."""
    locked = _locked_versions(project)
    wanted = {
        change.what: locked[change.what]
        for change in _floor_changes(project)
        if change.action == _UPDATE and change.what in locked
    }
    pyproject = project / "pyproject.toml"
    rewritten, moved = _rewrite_floors(pyproject.read_text(encoding="utf-8"), wanted)
    if moved:
        pyproject.write_text(rewritten, encoding="utf-8")

    return moved


def apply_python(projects: Sequence[Path]) -> list[str]:
    """Refresh each lock, raise the floors uv moved, then reconcile the lock."""
    lines: list[str] = []
    for project in projects:
        _run(["uv", "lock", "--upgrade"], project)
        moved = _raise_floors(project)
        _run(["uv", "lock"], project)
        lines.append(
            f"{_relative(project)}: uv.lock upgraded, {len(moved)} floor(s) raised"
        )
        lines.extend(f"  {entry}" for entry in moved)

    return lines


def apply_tools() -> list[str]:
    """Move the hook revisions; every other tool version floats or is refused."""
    _run(["pre-commit", "autoupdate"], _ROOT)

    return [f"{_relative(_PRECOMMIT)}: pre-commit autoupdate done"]


def _peeled(listing: str) -> dict[str, str]:
    """Tag name to commit sha, preferring an annotated tag's peeled target."""
    shas: dict[str, str] = {}
    for raw in listing.splitlines():
        sha, _, ref = raw.partition("\t")
        name = ref.removeprefix("refs/tags/")
        if name.endswith("^{}"):
            shas[name.removesuffix("^{}")] = sha
        else:
            shas.setdefault(name, sha)

    return shas


def _remote_tags(slug: str, cache: dict[str, dict[str, str]]) -> dict[str, str]:
    """Every tag a repository publishes, mapped to the commit it names.

    `git ls-remote` rather than the REST API because the unauthenticated API
    quota is shared across CI runner IPs, which is the same reason
    scripts/ci-setup.sh reads the releases/latest redirect.
    """
    if slug not in cache:
        listing = _run(
            ["git", "ls-remote", "--tags", f"https://github.com/{slug}.git"], _ROOT
        )
        cache[slug] = _peeled(listing)

    return cache[slug]


def _newest_tag(tracked: str, tags: dict[str, str]) -> str | None:
    """The highest published tag written the same way as the tracked one."""
    shape = _tag_shape(tracked)
    candidates = [tag for tag in tags if _tag_shape(tag) == shape]
    if shape is None or not candidates:
        return None

    return max(candidates, key=_version_key)


def _pin(use: Use, tag: str, sha: str, tag_only: bool) -> str:
    """The `uses:` value for one reference at a new tag, in its own pin form."""
    target = f"{use.slug}/{use.path}" if use.path else use.slug
    if tag_only:
        return f"{target}@{tag}"

    return f"{target}@{sha} # {tag}"


def _bump_use(
    line: str, tag_only: set[str], cache: dict[str, dict[str, str]]
) -> tuple[str, list[str]]:
    """One workflow line with its action pin moved to the newest release tag."""
    found = _ANY_USES.match(line.rstrip("\n"))
    use = _parse_use(found.group("value")) if found is not None else None
    if found is None or use is None or _tag_shape(use.tracked) is None:
        return line, []

    tags = _remote_tags(use.slug, cache)
    newest = _newest_tag(use.tracked, tags)
    if newest is None:
        raise SystemExit(f"{use.slug} publishes no tag written like {use.tracked}")

    value = _pin(use, newest, tags[newest], use.slug in tag_only)
    if value == found.group("value"):
        return line, []

    ending = "\n" if line.endswith("\n") else ""

    return f"{found.group('lead')}{value}{ending}", [
        f"{use.slug} {use.tracked} -> {newest}"
    ]


def _bump_workflow(
    path: Path, tag_only: set[str], cache: dict[str, dict[str, str]]
) -> list[str]:
    """Rewrite one workflow file's action pins, reporting each move."""
    moved: list[str] = []
    out: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines(keepends=True):
        rewritten, note = _bump_use(line, tag_only, cache)
        out.append(rewritten)
        moved.extend(f"{_relative(path)}: {entry}" for entry in note)
    if moved:
        path.write_text("".join(out), encoding="utf-8")

    return moved


def apply_actions(files: Sequence[Path], tag_only: set[str]) -> list[str]:
    """Rewrite every action pin to the newest tag at its tracked granularity."""
    cache: dict[str, dict[str, str]] = {}
    lines: list[str] = []
    for path in files:
        lines.extend(_bump_workflow(path, tag_only, cache))

    return lines


# --- Reporting and entry point ---


def _render(surface: str, changes: Sequence[Change]) -> None:
    """Print one surface's plan, one line per declared version."""
    counts = Counter(change.action for change in changes)
    summary = ", ".join(f"{count} {action}" for action, count in sorted(counts.items()))
    _hardgate.say(f"\n{surface} ({len(changes)}: {summary})")
    for change in changes:
        named = [f"  {change.action:<7} {change.where}: {change.what}"]
        if change.current:
            named.append(change.current)
        _hardgate.say(f"{' '.join(named)} ({change.note})")


def _require_tools() -> None:
    """Refuse to start the write half without every tool it shells out to."""
    missing = [
        name for name in ("go", "uv", "pre-commit", "git") if shutil.which(name) is None
    ]
    if missing:
        raise SystemExit(
            f"update-deps needs {', '.join(missing)} on PATH"
            " (scripts/ci-setup.sh provisions the gate toolchain)"
        )


def _parse_args() -> bool:
    """Whether this run only reports; the write half needs the flag absent."""
    parser = argparse.ArgumentParser(
        description="Refresh every dependency version this repository declares."
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="report the plan and write nothing, with no network call",
    )

    return bool(parser.parse_args().dry_run)


def main() -> int:
    """Plan every surface, report it, and rewrite unless this is a dry run."""
    dry_run = _parse_args()

    modules = go_modules()
    projects = uv_projects()
    provisioning = provisioning_files()
    templates = codegen_templates()
    workflows = workflow_files()
    tag_only = no_digest_deps()

    _hardgate.measured("go module discovery", len(modules))
    _hardgate.measured("uv project discovery", len(projects))
    _hardgate.measured("provisioning file discovery", len(provisioning))
    _hardgate.measured("codegen template discovery", len(templates))
    _hardgate.measured("workflow file discovery", len(workflows))

    surfaces = [
        ("go modules", plan_go(modules)),
        ("language versions", plan_languages(modules, projects)),
        ("python dependencies", plan_python(projects)),
        ("tool versions", plan_tools(provisioning, templates)),
        ("github actions", plan_actions(workflows, tag_only)),
    ]
    for name, changes in surfaces:
        _hardgate.measured(f"{name} scan", len(changes))
        _render(name, changes)

    graph = go_graph_findings(modules)
    if graph:
        _hardgate.say("")
        return _hardgate.report("requirements go.sum cannot cover", graph, _GRAPH_FIX)

    findings = [
        f"{change.where}: {change.what} {change.current}"
        for _, changes in surfaces
        for change in changes
        if change.action == _UNKNOWN
    ]
    if findings:
        _hardgate.say("")
        return _hardgate.report("versions this target cannot move", findings, _FIX)

    if dry_run:
        _hardgate.say("\ndry run: nothing was written and no network call was made")
        return 0

    _require_tools()
    _hardgate.say("")
    for line in apply_go(modules):
        _hardgate.say(line)
    for line in apply_python(projects):
        _hardgate.say(line)
    for line in apply_tools():
        _hardgate.say(line)
    for line in apply_actions(workflows, tag_only):
        _hardgate.say(line)
    _hardgate.say("\nread the diff and commit it yourself; this never touches git")

    return 0


if __name__ == "__main__":
    sys.exit(main())
